### ISSUE TITLE
ABAP Boolean issue

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#1008]
Hi,
I upgraded to the latest 2Ui5 version.
Unfortunately, the ABAP boolean field bindings for e.g editable, visible,etc are not working anymore.
Error: "" is of type string, expected boolean for property "editable" of Element sap.m.DatePicker#__picker0.

My fields are of data element type "BOOLE_D". It seems with data element "ABAP_BOOLEAN" it works. 
Did you implement a check on the used data element?
Thanks,
Axel

**Comment by axelmohnen** [comment]
Hi @choper725,
do you know the tag ID? I have a lot of issues after the upgrade to the latest version :-(.
I'm thinking to switching back....

**Comment by choper725** [comment]
@axelmohnen @oblomov dev 
will surely know. cant remember if that the last one or one before that

**Comment by oblomov-dev** [comment]
yes which types are a boolean is defined here:
https://github.com/abap2UI5/abap2UI5/blob/d2f242d38e9471694bb8f3bd3c996cfc46f26bd8/src/01/01/z2ui5_cl_util_api.clas.abap#L396-L405

added now boole_d with https://github.com/abap2UI5/abap2UI5/pull/1011 so it should work now on your side again. but i recommend using abap_bool or xsdbool for booleans as it is also recommended in the ABAP styleguides.

**Comment by axelmohnen** [comment]
Hi @oblomov-dev,
it works again. Thanks a lot for the fast support!
Kind regards
Axel
