### ISSUE TITLE
Two-way binding on nested view doesn't work.

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#1009]
Hi,
I installed the latest ABAP2UI5 version today.
Unfortunately, the two-way binding on nested views doesn't work anymore.
Please find attached a demo app.
[ZAMOH_CL_DEMO_APP_065.txt](https://github.com/abap2UI5/abap2UI5/files/14604077/ZAMOH_CL_DEMO_APP_065.txt)

Thanks a lot.
Kind regards
Axel

**Comment by oblomov-dev** [comment]
thank you for finding the issue, updated demo 85 and could reproduce the it: 
<img width="1161" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/3a4e3bac-4c13-47f8-a1e9-c3740e42c6b6">

will try to fix it.

**Comment by choper725** [comment]
maybe got something to do with ?.CHECK_UPDATE_MODEL ??
seems it doesnt exist in PARAMS

**Comment by oblomov-dev** [comment]
checked it and it was only the way back. i missed some logic from before the json refactoring, added it now again: https://github.com/abap2UI5/abap2UI5/pull/1013

demo 65 works now:
<img width="1008" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/30ffa109-b710-4e79-908c-b8d1529b5827">

@axelmohnen you can try you example again.

**Comment by axelmohnen** [comment]
Hi @oblomov-dev,
it works again. Thanks a lot for the fast support!
Kind regards
Axel
