### ISSUE TITLE
Popover on nested views are not working.

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#1010]
Hi,
I installed the latest ABAP2UI5 version today.
Unfortunately, the Popover on nested views are not working.
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/dcc23555-a9f6-4e45-aed9-cd8629ff7f8a)

Please find attached a demo app:
[ZAMOH_CL_DEMO_APP_POPOVER.txt](https://github.com/abap2UI5/abap2UI5/files/14604183/ZAMOH_CL_DEMO_APP_POPOVER.txt)

Thanks a lot.
Kind regards
Axel

**Comment by oblomov-dev** [comment]
Thank you for finding this issue, added and reproduced with demo 147 in https://github.com/abap2UI5/abap2UI5-samples/commit/77be2cc9181a3fc3f0f070d4e9ce228c223ef414

Never checked this use case before, added this example therefore as a sample. will try to fix this.

**Comment by choper725** [comment]
@oblomov-dev 
should add view to popover display method ?? could work..
as it open only via id, as it looks only in the main view

**Comment by oblomov-dev** [comment]
yes or i am thinking of when the id can not be found in the main view, try nest1 next, then next2 etc. a bit more dirty but easier for the user. no extra importing parameter to set the specific view would be needed.

**Comment by choper725** [comment]
created a PR in here & in samples

updated popover login + popup logic.

demo 147 now examples of popover in every view:
main, nest, nest2, popup

**Comment by oblomov-dev** [comment]
cool, thank you very much! big help and one task less on my to do list :)
tests are all succesfully on my side! 
@axelmohnen you can give it a try.

**Comment by axelmohnen** [comment]
Hi @choper725 and @oblomov-dev,
it works again. Thanks a lot for the fast support!
Kind regards
Axel
