### ISSUE TITLE
events handling

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#1018]
@oblomov-dev 
new issue for event handling.
one use case is frontend event from backend event.
other one is to call js code not from any view.
and maybe chaining events ? can that be a thing ? chain multiple events from xml to be executed sync ??

**Comment by oblomov-dev** [comment]
ok added it quick & dirty as a first approach with https://github.com/abap2UI5/abap2UI5/pull/1019
you can use now:
```
client->follow_up_action( client->event_frontend( ... ) ).
```

(1) can you provide a sample for your use case that i can check the new functionality with frontend events?
(2) you can also send custom_js to the frontend, but not sure how to call it without eval. can you give also a sample for this?
(3) chaining events, yes i think somehow this might be possible. but i also try to keep abap2UI5 as simple as possible and don't want to make it more complex as needed and and stuff for very rare or only edge use cases. do you also have a good sample for this that i can check if this is needed?

Best regards.

**Comment by choper725** [comment]
follow_up_action happen right after a round trip. ?

**Comment by oblomov-dev** [comment]
Yes I thought this is what you need? But maybe you provide a sample first and then we can see. Feel also free to replace it to a position that fits better for your use case.

**Comment by choper725** [comment]
sure ill pr a sample of couple of tests on it.

**Comment by choper725** [comment]
getting this error upon any demo
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/788481ae-8478-4fe2-87ca-41b83ff9a3dc)

**Comment by oblomov-dev** [comment]
ah i see, should b e fixed with https://github.com/abap2UI5/abap2UI5/pull/1021

**Comment by choper725** [comment]
fixed some issues with the code:
now:
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/0fc42ae8-8a59-441f-8330-44a752dcb5dc)

added logic to handle custom js function from xml,(see demo 180 for use cases)  using Function:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function

let me know what you think of that...

**Comment by oblomov-dev** [comment]
thank you, try to find time in the next days to check it in detail but at first glance it looks good.

**Comment by oblomov-dev** [comment]
yes i think it looks fine as it is. but to be honest, i am also not an expert in these topics, so lets keep it like this until we find other solutions or new issues arise. do you need more functionalities or can we close this issue?
i adjusted the importing parameter slightly with https://github.com/abap2UI5/abap2UI5/pull/1031

**Comment by choper725** [comment]
ill update the http_get with the changes you made and close it here.

for now looks as expected..

**Comment by oblomov-dev** [comment]
ok great, i close this one, just create a new one if you need more changes in the future.
