### ISSUE TITLE
Feature or Help Request: CARD Element

### ISSUE THREAD

**Issue by Marchl-Woid** [abap2UI5/abap2UI5#1023]
Hello together,
a question, I've seen that there is an element CARD at the XML View class. Are these the Cards for a cockpit? Somthing like this:

https://ui5.sap.com/#/api/sap.f.Card

I try to build I sample, but I'm running in this error:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/9f509b56-ee72-4670-9fa1-37ac4fe0c224)

Maybe a UI5 Version topic.

My sample snippet would be:

```
    DATA(page) = z2ui5_cl_xml_view=>factory(
      )->shell(
      )->page(
            title = 'Demo'
            navbuttonpress = client->_event( 'BACK' )
            shownavbutton = xsdbool( client->get( )-s_draft-id_prev_app_stack IS NOT INITIAL )
       )->header_content(
            )->search_field(
*          value  = client->_bind_edit( mv_search_value )
      search = client->_event( 'ON_SEARCH' )
      change = client->_event( 'ON_SEARCH' )
      width  = `17.5rem`
      id     = `SEARCH`
       )->get_parent( ).



   DATA(card) = page->card(
*  EXPORTING
*    id             =
*    class          =
*    headerposition =
*    height         =
*    visible        =
*    width          =
*  RECEIVING
*    result         =
    ).


    card->header(
*  EXPORTING
*    ns     = `f`
*  RECEIVING
*    result =
    )->card_header(
      EXPORTING
*    id                  =
*    class               =
*    iconalt             =
*    iconbackgroundcolor =
*    icondisplayshape    =
*    iconinitials        =
*    iconsize            =
*    iconsrc             =
*    iconvisible         =
*    statustext          =
*    statusvisible       =
*    subtitle            =
*    subtitlemaxlines    =
        title               = 'Hello'
*    titlemaxlines       =
*    visible             =
*    datatimestamp       =
*    press               =
*  RECEIVING
*    result              =
    )..
```

**Comment by choper725** [comment]
hi @Marchl-Woid 
can you provide full code of your demo?

**Comment by Marchl-Woid** [comment]
Hi @choper725 
I just pulled the newest versions. Thanks in advance, currently when I try this sample this error:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/63e7db82-30ae-4ff0-b90b-86c35068b1a9)

**Comment by choper725** [comment]
as i see this tite control is available from > 1.92, what version you on ?

**Comment by Marchl-Woid** [comment]
Hm, as I see, it would be newer:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/8d206d78-5122-42ba-9df0-b4e0d4c9d786)

**Comment by choper725** [comment]
i see, well dont really know then..

any way, change the title( with label( in the list, and it should work for ya.

cheers

**Comment by Marchl-Woid** [comment]
oh, nice one :)
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/2878fbc3-e596-4e10-b455-a01312591678)
is working. Thanks a lot
