### ISSUE TITLE
t_arg in event

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#1026]
Hi @oblomov-dev

just a quick question, how many t_arg values can we pass in event handler ?
i remember it was max 3, is it still the case ?

**Comment by oblomov-dev** [comment]
it should be possible to add as much as you need, therefore i changed it to a string table once. 

but never used by myself for more than 4 i think till now. but as always, give it a try and send a sample if you run into problems.

**Comment by choper725** [comment]
works as you said, infinite number..
