### ISSUE TITLE
Tab-Navigating through UI Table with Input fields

### ISSUE THREAD

**Issue by LadwigDev** [abap2UI5/abap2UI5#1033]
Hi,
I have encountered a strange behaviour. When tab-navigating through a ui table with multiple input fields without changing anything everything works fine, the cursor is set to the next input field:

<img width="513" alt="Okay" src="https://github.com/abap2UI5/abap2UI5/assets/155659152/1bd1fec7-e7d3-4545-8f9f-3f947ff7cbb4">

However when a user edits an input field which triggers a change event and a view model update, sometimes (not always!) the focus is changed from the input field to the surrounding table cell:

<img width="341" alt="Not okay" src="https://github.com/abap2UI5/abap2UI5/assets/155659152/02f9574c-ad0a-4088-a9be-e77a52701ea8">

This is a problem because the user can't change multiple table entries one after the other fast and the usability of the app is worsened. Do you have an idea what could trigger this behaviour?

Best regards
Jan

**Comment by oblomov-dev** [comment]
Hi,
Yes focus handling is often complex in UI5. Never had this issue before but I can take a look to it. Is there a chance that you share a little sample app which reproduces your problem? Then I can easily check it on my side.
Best regards.

**Comment by oblomov-dev** [comment]
thank you, added you code as sample 172 and try to take a look to it in the next days.

**Comment by oblomov-dev** [comment]
That seems to be a general problem of the sap.ui.table:
https://community.sap.com/t5/technology-q-a/sap-ui-table-table-moving-focus-from-column-to-input-field-within-template/qaq-p/12564500

you can consider if changing the table to sap.m.table is an option for you.

anyway, i added some pure JavaScript to adjust the focus handling, check demo 172. After every backend roundtrip the position of the focus gets corrected. Maybe there are more elegant ways to solve this issue but for now it seems to work:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/b1a426f8-8a1a-4b97-b7da-cc48027e0b2c">
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/40ffffe1-c2c6-4079-afe6-57af641427ff">

**Comment by LadwigDev** [comment]
Hi @oblomov-dev 
great, thank you for your help, the custom JS solution works with my app! This is something I would not have been able to achieve as a pure ABAP developer without JS knowledge 😆 

Have a nice week!

Best regards
Jan
