### ISSUE TITLE
TreeTable state revisit - cannot open popovers/popups

### ISSUE THREAD

**Issue by ssocratous71** [abap2UI5/abap2UI5#1034]
Hi,
  I try the solution given in demmo 116, which works ok, but if you add a simple popover it crashes with dom undefined error. I am attaching a modify version of demo 116 to see the problem.

Regards,

S.Socratous
[z2ui5_cl_demo_app_116.txt](https://github.com/abap2UI5/abap2UI5/files/14692257/z2ui5_cl_demo_app_116.txt)

**Comment by choper725** [comment]
in the popver event you are not sending the source id in the t_arg.

see the popover demo in table or list.

**Comment by ssocratous71** [comment]
Event with passing the source id as argument is the same behaviour. Popups work find I checked it. The problem is with popovers

**Comment by ssocratous71** [comment]
Here is the demo modify using source id in case you want to check it.
[z2ui5_cl_demo_app_116.txt](https://github.com/abap2UI5/abap2UI5/files/14692635/z2ui5_cl_demo_app_116.txt)

**Comment by choper725** [comment]
your demo works on my side,

a change was made

change this line
client->follow_up_action( custom_js = `setState();` ).

to this
client->follow_up_action( val = `setState();` ).

ill PR this demo to the repo

**Comment by ssocratous71** [comment]
Hi,
  great! It works now after reloading the libraries an changing the above line.
Regards,

S.Socratous
