### ISSUE TITLE
ABAP Environment: XCO_CP_ABAP => CLASS type missmatch

### ISSUE THREAD

**Issue by Xexer** [abap2UI5/abap2UI5#1037]
Hello,
when using value help on start page (Step 4), I get an error "". In class Z2UI5_CL_STMPNCFCTN_API and method XCO_GET_CLASS_DESCRIPTION type missmatch. Casting i_classname to char30, it works.

Greetings 
Björn

**Comment by oblomov-dev** [comment]
thank you for the hint, should be fixed now with https://github.com/abap2UI5/abap2UI5/pull/1038

**Comment by oblomov-dev** [comment]
i close this, reopen if you need further support
