### ISSUE TITLE
demo 131

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#1044]
hi @oblomov-dev 
demo 131 gives error
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/aab5384b-459d-49f3-8464-4a560b0a16d1)

**Comment by oblomov-dev** [comment]
ah, i'll check this, thanks!

**Comment by oblomov-dev** [comment]
its dependend on the subapp using generic data references, separated now in extra demo, try to fix it soon:
<img width="1249" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/51372051-3fb1-4434-8300-595ec799e839">

**Comment by oblomov-dev** [comment]
@choper725 @abapsheep 
fixed now with https://github.com/abap2UI5/abap2UI5/pull/1047

**Comment by abapsheep** [comment]
Hi, 
I made a adjustment to App 132. I added some type ref to data selections and now it s dumping again.
I will send a PR
Thanks in advance.

**Comment by oblomov-dev** [comment]
fixed with https://github.com/abap2UI5/abap2UI5/pull/1065
