### ISSUE TITLE
SAP.M.TABLE - Sorting, grouping and filtering

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#1046]
Hi,

I have the requirement to implement a Sorting, grouping and filtering functionality on table column header level.
It should be similar to the Fiori element list report template. 
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/1ef9a38b-f6b4-4dea-9b79-063fb6dc21fc)

In the SAPUI5 samples I found the Column Menu example.
It's actually a popover with some buttons inside.

sap.ui.table.ColumnMenu
sap.m.table.ColumnMenu

![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/d6aec600-7936-4345-94c9-478b32b41b26)
[https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.p13n.Engine/code]

This could be a new and helpful 2UI5 build-in feature.
Do we have already something similar available? Didn't found it in the demos.

Thanks,
Axel

**Comment by choper725** [comment]
there is a demo for p13n, there are two implementations for it.
one its the deprecated persotable and the other its the p13n engine.
both are not working fully and need to be further developed.

check the demos for it.

either way ill implement columnmenu control in the xml view and make a small demo for it.

sorting is not a problem,
grouping and especially fitering are probebly harder to achive based on a sapui5 existing control without a specific cc.

ill see what can be done in that area tho..

cheers

**Comment by choper725** [comment]
see latest pr and demo 183,
started working on it..

**Comment by choper725** [comment]
hi @axelmohnen 
check demo 099 for view settings dialog, (latest pr in demo repo)
i think this may solve your issue,

still got more to do with the filtering on this demo, but in general you get what you need there i think
let me know.

cheers

**Comment by axelmohnen** [comment]
Hi @choper725,
thanks a lot! Didn't know about the "View settings dialog".
This solves my issue.
Unfortunately, sap.m.table.columnmenu doesn't exists for your release 1.108.x
Thanks,
Axel
