### ISSUE TITLE
Handling boolean with data elements

### ISSUE THREAD

**Issue by Marchl-Woid** [abap2UI5/abap2UI5#1050]
Hello together
I would need a hint, where to find it.

What I want to try: If you want to use an UI element expecting a boolean value like Switch Element, somewhere in the framework the type ABAP_BOOL in converted to a javascript bool.

My topic now is, when using a DDIC structures and there are fields with domain, for example, type flag or wdy_boolean, they can't be used for these UI element. (you get an error message, String element not allowed..). What I have to do in these cases, is to create a class local variable of the abap_bool and move the values between..

What I want to try, if this logic can be enhanced, that this is not necessary.... But I don't find the coding, where this is done... Can someone give me a hint?

**Comment by oblomov-dev** [comment]
yes it is done here:
https://github.com/abap2UI5/abap2UI5/blob/7851c5e03afe414b9e9081d5231127c15272170d/src/01/01/z2ui5_cl_util_api.clas.abap#L396

feel free to extend it and send a PR or just write here which types you need.

**Comment by Marchl-Woid** [comment]
@oblomov-dev I close it. Thanks for the info, i have an idea what to todo, but a little bussy at the moment

**Comment by oblomov-dev** [comment]
Yes no problem, just reopen if you need more help.
