### ISSUE TITLE
displayedBars not available for InteractiveBarChart

### ISSUE THREAD

**Issue by shivushedad** [abap2UI5/abap2UI5#1057]
We are trying to build an [interactive bar chart](https://sapui5.hana.ondemand.com/#/api/sap.suite.ui.microchart.InteractiveBarChart%23constructor) using abap2UI5 and cannot seem to override / set the value of displayedBars value to higher than the default value of 3.

Per the documentation linked above we were supposed to have the `displayedBars` property available to be passed when creating bar chart object. Am I missing anything?

**Comment by oblomov-dev** [comment]
Hi @shivushedad,
so far you do it right, you can just overwrite the property in the backend and then the frontend uses this updated value.
Can you share a little sample app with your problem? Then we can take a look to it and see how to fix it.
Best regards.

**Comment by shivushedad** [comment]
I copied [Z2UI5_CL_DEMO_APP_016](https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_016.clas.abap) from the [abap2UI5-samples](https://github.com/abap2UI5/abap2UI5-samples.git) repo and tried to add `displayedBars` at [line 65](https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_016.clas.abap#L65) and I get a syntax error indicating `Formal parameter "DISPLAYEDBARS" does not exist.`

![image](https://github.com/abap2UI5/abap2UI5/assets/29564211/70090334-abf0-4422-951c-def0f41b3a3c)

**Comment by oblomov-dev** [comment]
added now the property with https://github.com/abap2UI5/abap2UI5/pull/1061
check out the demo 16 again.

If you are familiar with GitHub and PRs, feel free to extend the XML View Class with the properties you need and sent a PR.

**Comment by shivushedad** [comment]
@oblomov-dev thank you for the PR. I am now able to see the `displayedBars` property available.
Closing the issue.
