### ISSUE TITLE
Sample 190/191 not working.

### ISSUE THREAD

**Issue by abapsheep** [abap2UI5/abap2UI5#1072]
Deep Structures are not working. See Sample 190/191
Thanks in advance.

**Comment by oblomov-dev** [comment]
thank you for the sample, i will check this!

**Comment by oblomov-dev** [comment]
fixed with https://github.com/abap2UI5/abap2UI5/pull/1085

**Comment by abapsheep** [comment]
Works now.

Thanks alot

**Comment by abapsheep** [comment]
Works now,
thanks alot!
