### ISSUE TITLE
Refresh charts with new data

### ISSUE THREAD

**Issue by jelliottp** [abap2UI5/abap2UI5#1074]
I'm working on a page with donut, bar and line charts. I'm adding a multi-select box to allow user to filter.

How can I update the charts with the new data?  I am able to capture the filter data and execute all the queries to update my tables, and I handle the event and call `client->view_model_update( ).` but it does not work. What am I missing? 

Example, we initially populate the donut chart segments for example in a loop using table data.
```
DATA(donut_chart) = grid->flex_box(
        width          = '30rem'
        height         = '18rem'
        alignitems     = 'Start'
        justifycontent = 'SpaceBetween'
            )->items( 
                )->interact_donut_chart( displayedsegments = CONV string( lines( counts ) )
                    )->segments( ).

LOOP AT counts ASSIGNING FIELD-SYMBOL(<count>).
      DATA percent TYPE p LENGTH 3 DECIMALS 2.
      percent = <count>-count / total_count * 100.

      donut_chart->interact_donut_chart_segment(
          label          = <count>-text
          value          = CONV string( percent )
          displayedvalue = |{ percent }%|).
ENDLOOP.
```

**Comment by choper725** [comment]
you need to bind the percent value instead of looping and assign data, if you call the render method again upon filter it will work for you but its not the way to do it

**Comment by jelliottp** [comment]
> you need to bind the percent value instead of looping and assign data, if you call the render method again upon filter it will work for you but its not the way to do it if you want help share the demo

How do you bind the percent/label values for individual segments from table data? The number of segments can change based on the number of rows.

**Comment by choper725** [comment]
you are right, its not possible o bind items to tab to a segment (as far as i understand), but you can bind the percent value to the property of each segment, and in the filter event recalculate the percent and update the model

**Comment by jelliottp** [comment]
> pull latest pr #1075 and demo repo, and check demo 013. last chart got your code binded to the model fully..
> 
> let me know if you need something else ?

Ah, yes with those new properties this makes sense now how it can be done. Let me try this out.

**Comment by choper725** [comment]
can we close this ?
