### ISSUE TITLE
CX_SY_REF_IS_INITIAL

### ISSUE THREAD

**Issue by Nuube** [abap2UI5/abap2UI5#1076]
Hi,

forgive me if my question is stupid. These are my first steps with OO ABAP.

I cloned the abap2UI5 repository using ABAPgit Standalone and tried to start the Z2UI5_CL_APP_HELLO_WORLD~MAIN method from SE80. But the only result is get is a error pop-up- Probably something is missing in the system setup?.

![image](https://github.com/abap2UI5/abap2UI5/assets/25643142/1fc2e566-bb2a-4e4d-a182-98215db6ec7f)

**Comment by oblomov-dev** [comment]
No problem, we all started like this ;)

abap2UI5 runs in the browser, therefore you need to create an http service. you can follow this guideline:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/01_installation/create_http_on_prem.md
alternatively just install this project (an http service is also included in this abapgit project):
https://github.com/abap2UI5/abap2UI5-proxy_app_launchpad

let me know if you need more help.

**Comment by Nuube** [comment]
Thanks for the help. 

Using the ABAPGIT failed. I will try to do it manually.

![image](https://github.com/abap2UI5/abap2UI5/assets/25643142/30a90190-a63e-415b-b935-6f850d61023e)

**Comment by oblomov-dev** [comment]
i think your release is too low, try the http handler code snippet implementation from the downport repository, you can find it here:
https://github.com/abap2UI5/abap2UI5-downport?tab=readme-ov-file#handler-implementation

**Comment by Nuube** [comment]
![image](https://github.com/abap2UI5/abap2UI5/assets/25643142/be2c8fac-1ab8-4cbf-9c34-f2379fac37bc)

I found the error message reasonable: The switch statement needs to check the return type of every alternative. 

The older version i consider much better programming style because it is much more readable/maintainable exactly out this reason

**Comment by Nuube** [comment]
It compiles with the older code version. I installed the service, but it does not provide data:

![image](https://github.com/abap2UI5/abap2UI5/assets/25643142/a498a33a-1943-4524-a64e-886600ae0a66)

**Comment by Nuube** [comment]
Ok I found the cause for the empty service: In SICF the service must be set to "SSL", otherwise the service test opens a http and not a https connections, which does not deliver any data.

![image](https://github.com/abap2UI5/abap2UI5/assets/25643142/6f7d841b-6ca8-4d01-8716-89f17fcd6568)
