### ISSUE TITLE
 Package 01 has a subpackage with the same name

### ISSUE THREAD

**Issue by Yogeshwaran2002** [abap2UI5/abap2UI5#1077]
Hi I am trying to clone repository in my btp cloud enviroinment but getting this error while pull.
Check the screenshot
![image](https://github.com/abap2UI5/abap2UI5/assets/69333905/1b47bfb8-fd08-40a1-8177-81441dd0767c)

**Comment by Yogeshwaran2002** [comment]
Hi,
I use Full Folder logic and my Package name is : ZABAP2UI5_YOGI

**Comment by oblomov-dev** [comment]
maybe the package name is too long, try something shorter like: Z2UI5YOGI or Z2UI5YG

and if this does not work try folder login prefix.

**Comment by oblomov-dev** [comment]
if your run into problems with abap2UI5, the best way is always to create an issues here. Everything concerning abap2UI5 is collected here which makes it easy for everyone to find a solution or give help.

feel free to add me on linkedin, maybe i will post more abap2UI5 stuff in the future also there: 
www.linkedin.com/in/lars-kaldewey
