### ISSUE TITLE
Error Generic Tile -> Numeric Content

### ISSUE THREAD

**Issue by Marchl-Woid** [abap2UI5/abap2UI5#1084]
Hello together
I would need a hint againt.
I want to use the Tile with a numeric content. If the number is below a specific value, is should be e.g. red.
 
My problem is the color.

If I do it this way
valueColor = 'Critical'
it works fine. 
If I bind it to an attribute type string I get this error:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/e01dd3a0-1574-48c7-9bcc-4013c19d3276)

The code snippet would be:

  ```
 io_content->generic_tile(
           class     = 'sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout'
           header    = 'Demo Tile'
           subheader = 'Sub Header
           frametype = 'OneByHalf'
           press     = io_client->_event( val = 'SELECTED' )  )
        )->get( )->tile_content(
          )->numeric_content( value = io_client->_bind( me->as_wrklst-restdays ) icon = 'sap-icon://bo-strategy-management' withmargin = abap_false indicator = 'Up'  formatterValue = abap_true
                              valueColor = io_client->_bind( me->as_wrklst-color_restdays ) ).
```
What I can't figure out, how to convert the string value "Critical" to the expected type via binding:
 valueColor = io_client->_bind( me->as_wrklst-color_restdays ) 

Thx in advance

**Comment by choper725** [comment]
set default value for
as_wrklst-color_restdays to ‘Neutral’

it will work

**Comment by Marchl-Woid** [comment]
HI @choper725 
worked. Thanks for the quick help
