### ISSUE TITLE
Syntax error in sample repo

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1106]
Due to latest renaming
![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/0999fe26-029d-4163-bd84-883f9288ab55)

**Comment by oblomov-dev** [comment]
@larshp thanks for the hint. checked it and updated the samples after, but i should better work with branches having the same name and the merge it in parallel.

@christianguenter2 on my system it works fine:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/46ebec78-2886-4d5e-9e3d-26d037e61779">

and the repository seems also to be updated correctly e.g.:
https://github.com/abap2UI5/abap2UI5-samples/blob/24a5d826058f200b2630c3558f7523f6f941adc4/src/z2ui5_cl_demo_app_159.clas.abap#L91
did you pulled the latest version?

**Comment by christianguenter2** [comment]
Hm, at least I thought I did. But seems my fork was outdated. Never mind, sorry.
