### ISSUE TITLE
Get IP Address in the App class/ Access to HTTP header fields in App class.

### ISSUE THREAD

**Issue by Dev4Develop** [abap2UI5/abap2UI5#1120]
Hi ,

I'm trying to develop a sample application which collects the IP address of the user. 

I could see the remote address as header field in Handler class but Is there a way to get the same my own class?

![image](https://github.com/abap2UI5/abap2UI5/assets/137146462/b3fc95d8-70ca-4f21-acd8-793093f9bdfc)

Is it a good idea to add _server_ as an importing parameter to MAIN method in the interface . Do suggest any alternative solution if any.  
![image](https://github.com/abap2UI5/abap2UI5/assets/137146462/9b9b2525-9a53-471f-84aa-332324a9d8dd)

**Comment by oblomov-dev** [comment]
hi @Dev4Develop,

yes being able to use more frontend infos e.g. IP adress is a good idea, so thanks for the issue!

At the moment i am not sure whats the best way to import these information to abap2UI5, the server object differs from abap standard to abap for cloud so i can not just import the server object (which would be the easiest way).

Maybe as a quick workaround you can add the server object to your handler as a static object, eg.:
```abap
CLASS z2ui5_cl_launchpad_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_http_extension .
    CLASS-DATA server TYPE REF TO if_http_server.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z2ui5_cl_launchpad_handler IMPLEMENTATION.


  METHOD if_http_extension~handle_request.

    z2ui5_cl_launchpad_handler=>server = server.

    DATA(lt_config) = VALUE z2ui5_if_types=>ty_t_name_value(
          (  n = `data-sap-ui-theme`         v = `sap_belize` )
          (  n = `src`                       v = `https://ui5.sap.com/1.116.0/resources/sap-ui-core.js` ) "<- adjusted ( for example to load from sap cdn)
          (  n = `data-sap-ui-libs`          v = `sap.m` )
          (  n = `data-sap-ui-bindingSyntax` v = `complex` )
          (  n = `data-sap-ui-frameOptions`  v = `trusted` )
          (  n = `data-sap-ui-compatVersion` v = `edge` ) ).

    DATA(lv_resp) = SWITCH #( server->request->get_method( )
    WHEN 'GET'  THEN z2ui5_cl_http_handler=>http_get( )
      " WHEN 'GET'  THEN z2ui5_cl_http_handler=>http_get( value #( t_config = lt_config ) )
       WHEN 'POST' THEN z2ui5_cl_http_handler=>http_post( server->request->get_cdata( ) ) ).

    server->response->set_header_field( name = `cache-control` value = `no-cache` ).
    server->response->set_cdata( lv_resp ).
    server->response->set_status( code = 200 reason = `success` ).

  ENDMETHOD.

ENDCLASS.
```
and then use it in your app with:
```abap
CLASS z2ui5_cl_demo_app_001 DEFINITION PUBLIC.

  PUBLIC SECTION.

    INTERFACES z2ui5_if_app.

    DATA product  TYPE string.
    DATA quantity TYPE string.
    DATA check_initialized TYPE abap_bool.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS Z2UI5_CL_DEMO_APP_001 IMPLEMENTATION.


  METHOD z2ui5_if_app~main.

      z2ui5_cl_launchpad_handler=>server->request->get_header_field....
```

Does this work for you?

I will check if there are more elegant solutions or let me know if you have ideas.

Best regards.

**Comment by Dev4Develop** [comment]
Thanks for quick response. 

`z2ui5_cl_launchpad_handler=>server->request->get_header_field.`

Unfortunately above solution didnt work. Athough the static object is assigned in handler class, server object is INITIAL during button click event. 

![image](https://github.com/abap2UI5/abap2UI5/assets/137146462/36da5644-8fc4-43c4-80cd-3aa99236ec27)

we can achieve through IMPORT and EXPORT Memory but I'm figuring out the better approach.

**Comment by oblomov-dev** [comment]
hi @Dev4Develop,

checked it on my side with demo 001, it works, the server object is bound and can be used inside the app:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/bed9c860-36f2-4165-a955-e273e1f59a5e">

maybe you overlooked something? 

best regards.

**Comment by oblomov-dev** [comment]
ah copy line 12-14 to line 3. you fill the server object too late (its after the POST implementation).

as a side note, the if condition is not needed, its a rest service and will be always not bound.

**Comment by Dev4Develop** [comment]
Awesome. It's working. Thanks.

**Comment by oblomov-dev** [comment]
good to hear that it works! i will close this issue, we will keep the solution as it is for now, no plans to extend abap2UI5 with the server object. We can better keep it small and compatible with both language versions. but just reopen this issue that we can talk again about this if more functionality is needed in the future.
