### ISSUE TITLE
Error when testing the launchpad extension

### ISSUE THREAD

**Issue by mschmidma** [abap2UI5/abap2UI5#1123]
![error_launchpad Extension](https://github.com/abap2UI5/abap2UI5/assets/169126137/fe82a295-dd70-41ae-a32f-1eaf613cebd1)
Hi!
I installed the launchpad extension app zabap2ui5 and service z2ui5 one week ago and it did work great for a few days. But a few days ago, I updated the 3 packages (abap2ui5, samples and launchpad...) and since then, the launchpad app is hanging up, even when I test it in SICF as a single service test.

Anybody else having this weird behaviour?
Anyhow, I'm sure this project is becoming really great fun and I can't wait to have the first app productive :-) :-)

thank you so much,
Michael

**Comment by oblomov-dev** [comment]
hi @mschmidma,
thanks for this isue, there was a bug created by the latest changes. fixed it now with:
https://github.com/abap2UI5/abap2UI5/pull/1124

you can pull the new version and try again.

best regards.
