### ISSUE TITLE
Sample code for on-prem http handler doesn't compile 

### ISSUE THREAD

**Issue by dantof** [abap2UI5/abap2UI5#1126]
Hi,
Code from the documentation:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/01_installation/create_http_on_prem.md

uses non existing class:  **z2ui5_cl_fw_http_handler**
I guess the correct class name would be **z2ui5_cl_http_handler**

Minor thing but may be discouraging for newcomers.

Thanks for great project :-)
Daniel

**Comment by oblomov-dev** [comment]
Oh yes, thanks for the hint! 🙏
Feel free to send a PR or otherwise I will fix it in the next days.

**Comment by oblomov-dev** [comment]
fixed with https://github.com/abap2UI5/abap2UI5-documentation/commit/160947d98a6736f8f48f5a1aef8f8a5dacb0b0bc
