### ISSUE TITLE
sap.ui.Device.system

### ISSUE THREAD

**Issue by Astepmail** [abap2UI5/abap2UI5#1132]
Hi!
Is there a way to get sap.ui.Device.system values?

**Comment by Astepmail** [comment]
I try 
)->label( `{= $sap.ui.Device.system.desktop}`)
return Undefined

**Comment by choper725** [comment]
im not sure if binding expression works like that… will need to look

**Comment by oblomov-dev** [comment]
Thank you for checking this @choper725. would be nice if removing the $ solves the issue. If not, we could also extend the CC for frontend information. However, if it works out of the box without additional changes, that would be even better.

**Comment by choper725** [comment]
just figured, didnt checked, will do soon

**Comment by Astepmail** [comment]
without $ also doesn't work

**Comment by choper725** [comment]
so probebly enhance the frontend information cc will do the trick

**Comment by Astepmail** [comment]
Z2UI5_CL_CC_INFO ?

**Comment by oblomov-dev** [comment]
yes Z2UI5_CL_CC_INFO , this is the right place, you can also check sample: Z2UI5_CL_DEMO_APP_122

you just need to extend the class with the property you need. Feel free to give it a try, if you run into problems, let us know.

**Comment by Astepmail** [comment]
Thanks!

**Comment by oblomov-dev** [comment]
fyi updated the cc.info and sample with latest PR, check demo 122 again.
