### ISSUE TITLE
Launch your abap2UI5 Apps using SAP Build Workzone Launchpad

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5#1137]
Hi,

I have configured everything as described in the documentation. 
[Docu ](https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/ext-business_technology_platform/04_build_workzone_configuration.md)
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/64e0bc05-62a4-418a-b6af-2ba30679256b)
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/714de053-2494-4a45-a866-0b0988e7c47e)

When I open the app I get the following error:

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/d63c8a78-aefa-4eaf-ad23-ce97d3aea9b6)

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
Could reproduce the error and updated some launchpad functionality today, do the following:

Pull the latest abap2UI5 version to your on premise system.
Pull the abap2UI5 on premise launchpad plugin (you need this for the http handler) to your on premise system.
Deploy the app of the new version of the btp_workzone_plugin to your BTP.

Let me know if it works out now, or if there are further bugs.

**Comment by Th0masMa** [comment]
hi @oblomov-dev ,

i use not a premise System. i use the ABAP Trail Cloud System.
I pull the latest abap2ui5 version in my ABAP Trail Cloud System.
I deploy the new version of btp_workzone_plugin.

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/3e48a2b0-c255-40ce-9caf-5b287c243cf1)

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
ah okay, so far i only tested with S/4 Public, S/4 Private & ECC.

The problem with the ABAP Trial Cloud is that you don't have the permission to create communication arrangements. For example i see no way how to add an ABAP Trial with BasicAuth as a destination to a subaccount. Or did you made it to add it as a destination (besides the automatic way)? 

So far i think it is not possible to use it for external communication, but i recommend to use a real trial system, where you are allowed to have external communication, for example:
https://www.nuveplatform.com/pricing
And you can setup a BTP connection easily:
https://www.nuveplatform.com/blog/btp-to-on-prem

**Comment by Th0masMa** [comment]
Hallo,

i created a Destination in my BTP Trail..

[image: image.png]
[image: image.png]

[image: image.png]

**Comment by oblomov-dev** [comment]
fyi i think your screenshots didn't make it to github.

<img width="562" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/119be218-4e3e-423b-ba86-e82a013d255e">

**Comment by Th0masMa** [comment]
Hi @oblomov-dev ,

i change the image.

**Comment by oblomov-dev** [comment]
HI @Th0masMa,

i gave it  a try a while ago with ABAP Trial, but i did not make it work. Do you use your trial user in the destination or did you create a new communication scenario? As far as i understand it (but i could be wrong) you need a new communication scenario.

Check out this tutorial:
https://developers.sap.com/tutorials/abap-environment-create-http-service.html 
Especially step 7 and 11, you need a communication scenario and communication user which you can use in the destination. But in my tests it was not posssible to create this in ABAP Trial. Or does it work on your side?

Best regards.

**Comment by oblomov-dev** [comment]
updated the repository and collected now all information here:
https://www.linkedin.com/pulse/abap2ui5-integration-sap-business-technology-platform-13-installation-lf1re

feel free to give it a try again, but make sure not to use SAP BTP ABAP Trial. i close this issue, just create a new one or reopen if you have still problems.
