### ISSUE TITLE
flexibility service question

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#1147]
hi all, does anyone know how we can get flexibility service to work with this project, running from sicf, not from launchpad or cloud ??

any ideas ? been trying to get variant manager to work out of the box …

been trying to bootstrap this
https://sapui5.hana.ondemand.com/sdk/#/topic/642dab291a7b47ec9d46c39b3c482aba

but i was reading that maybe this should be added also some value to manifest.json, but i dont think this project runs with component.js or manifest.json

https://sapui5.hana.ondemand.com/sdk/#/topic/f1430c0337534d469da3a56307ff76af

**Comment by oblomov-dev** [comment]
yes this project is limited to an ui5 one pager, as we have to send it initially with the first http get request and does not use a component.js and manifest.json so far.

but we can extend the one pager, for example here they added an xml view:
https://blog.mypro.de/2015/08/27/openui5-one-pager/

or here they added a controller and a custom controlr:
https://gist.github.com/nzamani/7b5f767de011a77d2e27884d4cffb849

never needed it before so not sure if it works, but maybe its also possible to add a component.js or manifest.json like this to the abap2UI5 one pager?

**Comment by choper725** [comment]
well thats might worth a try, as adding persistence for variant management will be a great step forward

**Comment by oblomov-dev** [comment]
mhh too bad, I hoped it could maybe work like this. will give it a try next time i touch this area, but also not sure if i have more luck.

**Comment by oblomov-dev** [comment]
another option could be doing everything in the backend without using any UI5 specific functions here, maybe interesting for you:
https://github.com/abap2UI5/abap2UI5-samples/pull/207
will later check it.

**Comment by oblomov-dev** [comment]
any news here? otherwise i will close this one.

having flexibilty service in abap2UI5 would be amazing, but i don't see actual a way how to integrate it. but we can keep it in mind for the future.

layout management, and persist UI properties of for example tables can be realized with a pure backend approach like here (WIP):
https://github.com/abap2UI5-addons/layout-variant-management

this approach can also be extend for other controls than tables. or maybe in the future save a layout for the UI of complete pages. we will see...

**Comment by choper725** [comment]
well making flexibility service work out of the box will be amazing, i was trying to test it on non flp enviorment, tought it will do something,
but i do think this approach will work in flp .. just cant test it.

**Comment by oblomov-dev** [comment]
ah you made it work? feel free to share a sample if you made some progress.
