### ISSUE TITLE
Suggestion behavior on input field (z2ui5_cl_demo_app_060) 

### ISSUE THREAD

**Issue by obluhm** [abap2UI5/abap2UI5#1154]
Hello,
We are on Abap2UI5 Version 1.129.0 and we try to make use of the functionality of an input field with suggestion in ABAP2UI5. Fortunately we recognized the strange/wrong behavior also in the example z2ui5_cl_demo_app_060. Therefore we will describe the problem here with demo 60.

If you enter the String “bel” in the input field of z2ui5_cl_demo_app_060 you receive the following suggestion list:

![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/4b2a089b-6674-472c-b270-a222c0d77231)
 
At first glance you can see the suggestion list proposes all entries of colum “Name” starting with “bel”.
Lets try something like “usian”. This should be found, as this pattern is contained in “Belarusian”.
Result of suggestion list for “usian”

![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/18bfff21-7227-4323-9993-4fe4775e47ff)
 
Looks like it does not find the entries. Lets debug it. Break point on model update:

![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/e6576f5b-cb5b-46f1-a417-3ff037450c92)

Range pattern is correctly filled with CP and wildcards before and after the searched string:

![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/69f96824-60f9-4aa8-921b-5c04979d0bca)
 
Strange wise, table mt_suggestion_out is filled correct as well:
 
![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/c3d24b54-cbd7-4d0e-a8a2-007463964587)

But the suggestion list is not displayed this on the input field.
Any help on this to fix it?
Regards Oliver

**Comment by choper725** [comment]
will try take a look at this

**Comment by axelmohnen** [comment]
It seems this is an SAPUI5 issue, because the input field (sap.m.inut) is using by default the function "wordStartsWithValue"  (sap.m.inputUtils.inputsDefaultFilter).
`function (wordStartsWithValue) {
	"use strict";

	/**
	 * The default filter function for one and two-value. It checks whether the item text begins with the typed value.
	 *
	 * @param {string} sValue the current filter string.
	 * @param {sap.ui.core.Item} oItem the filtered list item.
	 * @param {boolean} bFilterAdditionalText true, if the item should be filtered by additional text
	 * @returns {boolean} true for items that start with the parameter sValue, false for non matching items.
	 */
	var defaultFilterFn = function (sValue, oItem, bFilterAdditionalText) {
		if (!oItem) {
			return false;
		}

		if (oItem.isA("sap.ui.core.ListItem") && bFilterAdditionalText && wordStartsWithValue(oItem.getAdditionalText(), sValue)) {
			return true;
		}

		return wordStartsWithValue(oItem.getText(), sValue);
	};` 

sap.m.input has a method called "setFilterFunction" in order to set a custom filter callback function.
Is it possible to set this "FilterFunction" in ABAP2UI5 like an event?

Do we have to create a CC for this?

Thanks,
Axel

**Comment by choper725** [comment]
its possiblw doing it without a cc,
will evetually be more convinent with cc but you can call a method of an xml via html tag, ill do a demo for it.

**Comment by choper725** [comment]
please check demos 002 and 060.

**Comment by axelmohnen** [comment]
Hi @choper725,
you example works perfectly. Nice to see what we could do with 2UI5 :-)

If we are using the "SUGGEST" event in the backend for filtering, we could even simplify the scripting part.
`      DATA(lv_script) = `   debugger;` && |\n| &&
                  `function setInputFIlter(){` && |\n| &&
                  ` var inp = sap.z2ui5.oView.byId('suggInput');` && |\n| &&
                  ` inp.setFilterFunction(function(sValue, oItem){` && |\n| &&
                  `         return true;` && |\n| &&
                  ` });` && |\n| &&
                  `}`.`

We need just to return a simple "TRUE" in order to avoid filtering on frontend side. 
Otherwise we are filtering twice (backend and frontend).

**Comment by choper725** [comment]
yes tou are correct suggest event trigger before filter.. nice, youll pr the demo ?

**Comment by choper725** [comment]
better make a new one and ill revert back demo 60 for a simple use case

**Comment by axelmohnen** [comment]
I created a PR for the new demo Z2UI5_CL_DEMO_APP_201.
[https://github.com/abap2UI5/abap2UI5-samples/pull/208]

**Comment by choper725** [comment]
@axelmohnen have you seen the PR's on your SH repo ??

**Comment by axelmohnen** [comment]
@choper725 : No I didn't see the PR's. I didn't receive any notification from GITHUB.
I will have a look asap....
Thanks

**Comment by oblomov-dev** [comment]
thank you for your work @choper725 @axelmohnen 🙏

does this work on your end @obluhm? can we close this issue?

**Comment by obluhm** [comment]
Hi @oblomov-dev 
thanks for your work. It's working now. 
And many thanks for the abap2UI5 Framework.
:-)
