### ISSUE TITLE
z2ui5_if_client->message_box_display - Text type changed from clike to string | Causes compatibly problmes 

### ISSUE THREAD

**Issue by obluhm** [abap2UI5/abap2UI5#1155]
Hi,
in release 1.127.0 the text type of the message_box_display has been changed from clike to string:
![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/f03408a2-c413-469e-959a-3ecddd7c89b4)

![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/a02e2bc2-43e1-4652-bf2a-3aba4ce07886)

This is causing errors also in the abap2UI5:

![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/900431c9-03ba-43e9-991f-a79d484fe178)

Regards Oliver

**Comment by choper725** [comment]
thx ill fix it

**Comment by oblomov-dev** [comment]
mhh message_box_display is in the interface z2ui5_if_client and part of abap2UI5, so better fix it here?

@choper725 fyi: if you just edit a message, no one gets informed, better write a second comment instead, then i can see it in my inbox again.

**Comment by choper725** [comment]
fixed it with, #1156 
changed string to clike, like it was,
checked the messages and its working.. (demo 002)

@obluhm let me know if that fixes it on your end..

**Comment by obluhm** [comment]
Hi Choper
just tested the message boxes in my environment after update to the latest version and it works again.
Thanks for your support.
