### ISSUE TITLE
Is focus change without rerendering possible?

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1158]
I'd like to change the focus to another input after submit field without rerendering the whole view. I created [this](https://gitlab.com/christianguenter/abap2ui5_test_focus.git) minimal sample app and tried to solve it via binding.
https://gitlab.com/christianguenter/abap2ui5_test_focus/-/blob/df359995d479c09d440031e126bfa35fb429c29d/src/zcl_test_focus_app.clas.abap#L55
Binding works but focus isn't changed after submit.

Focus still on first Input.
![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/ef48eb33-3166-46c3-87bd-dadc9f1d47fa)
![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/5e97bc0e-8f80-49f9-85e1-e93268cdcf5c)

Is there a way to achieve this **without** rerendering? Am I missing the obvious or maybe I'm doing it completely wrong?
Thanks in advance.

**Comment by oblomov-dev** [comment]
yes it was a bug, quickly fixed it, there might be some rework but it think it should work for now.
https://github.com/abap2UI5/abap2UI5/pull/1159

and thank you for the clean & small example! very helpfull. added it as sample 189, feel free to contribute to the samples repository if you find further bugs etc. always helpful for testing to have as much examples as possible.
https://github.com/abap2UI5/abap2UI5-samples/pull/203

**Comment by christianguenter2** [comment]
Well that's what I call a stunningly fast feedback & fix. Thanks a lot @oblomov-dev!
While the demo app works as expected I struggle with my custom app.

I get this error:
![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/80ec95cc-f158-4e2a-b07b-42cd09f1583e)

Any idea? 
Btw. somehow I'm not able to debug the JS attached to $metadata in Chrome. Any pointer how I can do this?

**Comment by oblomov-dev** [comment]
ah i also saw this in the other focus app example, i'll try to find a fix.

**Comment by oblomov-dev** [comment]
you can check again, did https://github.com/abap2UI5/abap2UI5/pull/1160

**Comment by christianguenter2** [comment]
Amazing. Works now as expected.
Well done and thank you very much.
