### ISSUE TITLE
[Info] OpenUI5 2.x Compatibility

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1161]
we have to take care of the deprecated APIs:
https://ui5.sap.com/#/topic/798dd9abcae24c8194922615191ab3f5
https://ui5.sap.com/#/topic/2acafbfcc2cb47e8aac6d2e32399af10
etc.

Checked abap2UI5 with the ui5-linter and made some fixes:
https://github.com/SAP/ui5-linter

@choper725 fyi:
changed the sdk check here:
https://github.com/abap2UI5/abap2UI5/blob/a78952d43d58874520d53085afdd63a0ceb5928c/src/01/02/z2ui5_cl_core_http_get.clas.abap#L432

and changed the openById function:
https://github.com/abap2UI5/abap2UI5/blob/a78952d43d58874520d53085afdd63a0ceb5928c/src/01/02/z2ui5_cl_core_http_get.clas.abap#L169

Maybe check on your end if it still works? I don't have a sample for this use case and can not test it by myself. Is there a chance for a sample or any infos of how i can reproduce this case?

In general, abap2UI5 seems on a good way for OpenUI5 2.x 😎

**Comment by choper725** [comment]
ok @oblomov-dev 

the sdk part should be easy to check.

the byid change its just a fallback upon not finding any id on any view.. dont think it should happen ever, but its there.

what is the plan with the delracations?
we got attachinit method deprecated and we use it no?
can we scan what we use that is on that list and should be fixed??

**Comment by oblomov-dev** [comment]
yes its good to have it, safety first :)

the plan is basically just check what is on the list and replace it with the new APIs. You can also do it automatically with the ui-linter. I did it yesterday and by now all looks good! also checked it a while ago, for example attachInit is not in use anymore.

furthermore started add Unit Testing for v.2.x here:
https://github.com/abap2UI5/abap2UI5/blob/3dea0409490ee3c15bd82c82b17b45957ac4600f/src/01/02/z2ui5_cl_core_http_get.clas.testclasses.abap#L87

Helps that no one can push accidentally incompatible v2 changes to abap2UI5. Feel free to extend!

**Comment by choper725** [comment]
oh i see,
ill look into it, we might have some deprecated code in the cc if i remember correctly..

any way, thx for informing about it

**Comment by oblomov-dev** [comment]
ah good point, i did not check the cc so far! but nothing urgent, just if you make changes there anyway, feel free to also check for 2.x syntax. then there is less work to do when the UI5 2.0 gets released.

**Comment by choper725** [comment]
great!
