### ISSUE TITLE
error in util_api -> GET_COMPS_BY_DATA

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#1168]
hi @oblomov-dev 
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/7adb4b81-bcc8-43ee-92f0-1460f7187c87)

**Comment by oblomov-dev** [comment]
oh fixed with https://github.com/abap2UI5/abap2UI5/pull/1169

**Comment by choper725** [comment]
well i run on abap 7.50
dref data->* to field symbol did the trick on my end
