### ISSUE TITLE
Wizard Branching Steps

### ISSUE THREAD

**Issue by Marchl-Woid** [abap2UI5/abap2UI5#1175]
Hello together 
I would need again a hint:

What I want to do is something like this:
https://ui5.sap.com/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.m.sample.WizardBranching&sap-ui-xx-sample-lib=sap.m&sap-ui-xx-sample-origin=.&sap-ui-xx-dk-origin=https%3A%2F%2Fui5.sap.com&sap-ui-theme=sap_horizon&sap-ui-rtl=false&sap-ui-density=sapUiSizeCompact

I want to generate brancing steps in the wizard. 
Basis for it I used Z2UI5_CL_DEMO_APP_175:

I adapted a accordingly:

![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/b9f7d670-b42a-4534-a36d-86e4362cb1eb)

` METHOD display_view.

    DATA(lr_view) = z2ui5_cl_xml_view=>factory( ).

    lr_view = lr_view->shell( )->page( id = `page_main`
             title          = 'abap2UI5 - Demo Wizard Control'
             navbuttonpress = client->_event( 'BACK' )
             shownavbutton = xsdbool( client->get( )-s_draft-id_prev_app_stack IS NOT INITIAL ) ).

    DATA(lr_wizard) = lr_view->wizard( enablebranching = abap_true ).
    DATA(lr_wiz_step1) = lr_wizard->wizard_step(  title = 'Step1'  validated  = abap_true nextstep = 'Step2' ).
    lr_wiz_step1->message_strip( text = 'STEP1' ).

    av_next = 'Step22'.
    DATA(lr_wiz_step2) = lr_wizard->wizard_step( id = 'Step2'
                                                 title              = 'Step2'
                                                 validated          = abap_true
                                                 subsequentSteps = 'Step22, Step23'
                                                 nextStep = client->_bind_edit( av_next ) ).

    lr_wiz_step2->message_strip( text = 'STEP2' ).
    lr_wiz_step2->button(
        text             = 'Press Step 2.2'
        press            = client->_event('STEP_22' ) ).
    lr_wiz_step2->button(
        text             = 'Press Step 2.3'
        press            = client->_event('STEP_23' ) ).

    DATA(lr_wiz_step22) = lr_wizard->wizard_step( id = 'Step22'
                                                 title              = 'Step2.2'
                                                 validated          = abap_true ).

    lr_wiz_step22->message_strip( text = 'STEP22' ).

    DATA(lr_wiz_step23) = lr_wizard->wizard_step( id = 'Step23'
                                                 title              = 'Step2.3'
                                                 validated          = abap_true ).

    lr_wiz_step23->message_strip( text = 'STEP23' ).

    client->view_display( lr_view->stringify( ) ).

  ENDMETHOD.`

The problem is this part:
`  DATA(lr_wiz_step2) = lr_wizard->wizard_step( id = 'Step2'
                                                 title              = 'Step2'
                                                 validated          = abap_true
                                                 subsequentSteps = 'Step22, Step23'
                                                 nextStep = client->_bind_edit( av_next ) ).`

When I try to solve the topic of the followup step via binding I get this error:

![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/8fde6f46-b69b-453e-b439-91e33d4179a7)

When I remove the binding:
`  
DATA(lr_wiz_step2) = lr_wizard->wizard_step( id = 'Step2'
                                                 title              = 'Step2'
                                                 validated          = abap_true
                                                 subsequentSteps = 'Step22, Step23'
                                                nextStep = 'Step22' ).
`

This version works, but then I can't control the brancing step....

Does anyone has a hint?

**Comment by choper725** [comment]
i could help if you share your demo and ill try to make it work

**Comment by Marchl-Woid** [comment]
HI @choper725 
thanks for your answer. I hadn't time yet to play aroud more since your answer:

My Current version:
```
CLASS z2ui5_cl_demo_app_175 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_serializable_object .
    INTERFACES z2ui5_if_app .

    DATA av_next TYPE string VALUE 'Step22' ##NO_TEXT.
    DATA av_init TYPE abap_boolean .
  PROTECTED SECTION.
    METHODS display_view
      IMPORTING
        client TYPE REF TO z2ui5_if_client.
  PRIVATE SECTION.
ENDCLASS.



CLASS z2ui5_cl_demo_app_175 IMPLEMENTATION.


  METHOD z2ui5_if_app~main.

    IF av_init EQ abap_false.
      display_view( client ).
      av_init = 'X'.
      RETURN.
    ENDIF.


    CASE client->get( )-event.
      WHEN 'BACK'.
        client->nav_app_leave( ).
      WHEN 'STEP_22'.

        av_next = 'STEP_22'.
      WHEN 'STEP_23'.

        av_next = 'STEP_23'.
    ENDCASE.
    client->view_model_update( ).
  ENDMETHOD.


  METHOD display_view.

    DATA(lr_view) = z2ui5_cl_xml_view=>factory( ).

    lr_view = lr_view->shell( )->page( id = `page_main`
             title          = 'abap2UI5 - Demo Wizard Control'
             navbuttonpress = client->_event( 'BACK' )
             shownavbutton = xsdbool( client->get( )-s_draft-id_prev_app_stack IS NOT INITIAL ) ).

    DATA(lr_wizard) = lr_view->wizard( enablebranching = abap_true ).
    DATA(lr_wiz_step1) = lr_wizard->wizard_step(  title = 'Step1'  validated  = abap_true nextstep = 'Step2' ).
    lr_wiz_step1->message_strip( text = 'STEP1' ).


    av_next = 'Step22'.
    DATA(lr_wiz_step2) = lr_wizard->wizard_step( id = 'Step2'
                                                 title              = 'Step2'
                                                 validated          = abap_true
                                                 subsequentSteps = 'Step22, Step23'
*                                                 nextStep = 'Step22' ).
                                                 nextStep = client->_bind_edit( av_next ) ).

    lr_wiz_step2->message_strip( text = 'STEP2' ).
    lr_wiz_step2->button(
*      EXPORTING
        text             = 'Press Step 2.2'
        press            = client->_event('STEP_22' ) ).
    lr_wiz_step2->button(
*      EXPORTING
        text             = 'Press Step 2.3'
        press            = client->_event('STEP_23' ) ).


    DATA(lr_wiz_step22) = lr_wizard->wizard_step( id = 'Step22'
                                                 title              = 'Step2.2'
                                                 validated          = abap_true ).

    lr_wiz_step22->message_strip( text = 'STEP22' ).


    DATA(lr_wiz_step23) = lr_wizard->wizard_step( id = 'Step23'
                                                 title              = 'Step2.3'
                                                 validated          = abap_true ).

    lr_wiz_step23->message_strip( text = 'STEP23' ).


    DATA(lr_wiz_step3) = lr_wizard->wizard_step( title              = 'Step3'
                                                 validated          = abap_true ).

    lr_wiz_step3->message_strip( text = 'STEP3' ).

*
    client->view_display( lr_view->stringify( ) ).

  ENDMETHOD.
ENDCLASS.

```

The topic is, the binding in the nextstep at Step 2, for branching in step 2.2 or 2.3. The idea would be something like:
Step 1 -> Step 2 -> Step 2.2 or Step 2.3 -> Step 3

I hope I have more time the next days :)


Regrads

**Comment by choper725** [comment]
nextStep is an aggregation, not sure why tho it wont accept a bind...

anyway, powerfull framework we have here :)

check demo 202 of new PR in demo repo once merged..

**Comment by christianguenter2** [comment]
@choper725 amazing!
Funny coincidence that I need exactly this feature right now :-)
Do you think it's possible to wrap the js in kind of CC so we won't have to repeat it in every app?

**Comment by oblomov-dev** [comment]
great work @choper725 and thank you for all PRs. big help! added the demo 202 now to the overview with https://github.com/abap2UI5/abap2UI5-samples/pull/213

**Comment by choper725** [comment]
> great work @choper725 and thank you for all PRs. big help! added the demo 202 now to the overview with [abap2UI5/abap2UI5-samples#213](https://github.com/abap2UI5/abap2UI5-samples/pull/213)

np @oblomov-dev im all in on this project :)



> @choper725 amazing! Funny coincidence that I need exactly this feature right now :-) Do you think it's possible to wrap the js in kind of CC so we won't have to repeat it in every app?

well of course its possible, but, this wizard holds alot of functionality via JS only, like reseting the steps and goto nextStep, of even if you want to implement wizard in a popup, like done in this demo
https://sapui5.hana.ondemand.com/resources/sap/ui/documentation/sdk/index.html?sap-ui-xx-sample-id=sap.m.sample.WizardSingleStep&sap-ui-xx-sample-lib=sap.m&sap-ui-xx-sample-origin=.&sap-ui-xx-dk-origin=https%3A%2F%2Fsapui5.hana.ondemand.com&sap-ui-theme=sap_horizon&sap-ui-rtl=false&sap-ui-density=sapUiSizeCompact

notice to next and previous step buttons.

so imo getting this control to a CC will be doint him wrong .. as it hold alot of different use cases.

**Comment by Marchl-Woid** [comment]
Hi @choper725 
I just installed the latest version. Exactly what I tried to do :) Thanks for your, that I would never have found out :)
