### ISSUE TITLE
Incompatibility - LP Title replaced with backend function

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1177]
@axelmohnen fyi i think you used the title function.

I deleted the set title function at the frontend:
https://github.com/abap2UI5/abap2UI5-connector_sap_fiori_launchpad/blob/f437eed2c18f2f9f58ed38d849a134e4655306cc/src/02/zabap2ui5.wapa.controller_-view1.controller.js#L12

But it can be set now on app level oin the backend with:
```abap
data(lt_params) = client->get( )-t_comp_params.
page->_z2ui5( )->lp_title(  lt_params[ n = `APP_TITLE` ]-v. ).
```
I changed it to stay consistent with the abap2UI5 approach: keep the frontend as small as possible and put all logic to the abap layer. Hope this works for you.

check out this for more launchpad infos:
https://www.linkedin.com/pulse/abap2ui5-host-your-apps-sap-fiori-launchpad-23-features-abap2ui5-upche/?trackingId=21HxoNP8IR4m1GCD35QzKA%3D%3D

Best regards.

**Comment by axelmohnen** [comment]
@oblomov-dev . Thanks for the info. I saw already your new blog on LinkedIn. It sounds really good the new features!
I will test it as soon as we will switch to the latest ABAP2UI5 version.

**Comment by oblomov-dev** [comment]
great, i will close this one, just create a new issue if you run into problems.
