### ISSUE TITLE
binding logic - removing bind_clear method

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1182]
simplified the binding logic, so calls of the bind_clear method are not needed anymore. deactivated the code of z2ui5_if_client~_bind_clear with https://github.com/abap2UI5/abap2UI5/pull/1179

all samples work correctly.

@choper725 i think you also use this function? maybe you can check your apps and let me know if there are any problems.

**Comment by choper725** [comment]
so now it happen by default?
we had a demo with two classes we used that cant remember the number, something with nested view and an input..

**Comment by oblomov-dev** [comment]
Yea it should happen per default when it is needed, so manuel method call needed anymore. 

Ah yes I remember, I will check later if I find it

**Comment by choper725** [comment]
its z2ui5_cl_demo_app_104, seems to work good ..

**Comment by oblomov-dev** [comment]
thanks for finding this sample, refactored it and removed the bind_clear call. also added this sample to the overview 000 that it can be find in the future.

but after switching the table entries, the input gets deleted. not sure if its a bug or if it was like this before?

**Comment by choper725** [comment]
demo104 is not a table ? its a flexible column layout and input..

what demo are you refering ?

**Comment by oblomov-dev** [comment]
ah of course master-detail is what i mean! but this input gets deleted after switching:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/70a66cba-ba8b-425c-8b8d-5a197154c2ec">

Not sure if this was intended

**Comment by choper725** [comment]
it was like that if i rmember correctly

**Comment by oblomov-dev** [comment]
ok nice, thanks for the info, then everything seems to work with the new simplified binding logic and i can close this one. 👍
