### ISSUE TITLE
F4-Help Popup

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1191]
continues https://github.com/abap2UI5/abap2UI5/issues/1184 @abapsheep 

Got this warning:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/eabb3a7f-e8d9-4b37-9022-d7f9a44bd5e1">
Updated then the data element guid, to abap.char(32). 

But this destroyed demo 204, therefore switched this demo to the field t100-arbgb.

Now (and i am not sure if this problem existed before) the value is not written back after choosing it in the popup:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/66da18f3-4159-4ec2-85dc-1ea405d16449">

After pressing the input is still empty:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/0f452f28-c4b6-48ba-9543-452ac70f0f75">
Do you have the same problems on your end?

btw. also added a shell container to the demo.

**Comment by abapsheep** [comment]
Previously the F4 help was linked to the GUID field, now it is linked to ARBGB. However, this still had to be adjusted here. ![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/d33dfd0e-4f1b-4fb7-a180-cafcc3032e26)
PR will follow in a sec.

**Comment by abapsheep** [comment]
PR was now merged, I hope this solved alle problems.

**Comment by oblomov-dev** [comment]
nice, works now on my end, thank you!

<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/a9df2e52-47a4-4651-99c8-b6660066afb6">

**Comment by oblomov-dev** [comment]
to keep the issues small, I close this one now. just open a new one if more functionality is needed or new bugs are found.
