### ISSUE TITLE
Layout Popup

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1193]
continues https://github.com/abap2UI5/abap2UI5/issues/1184 @abapsheep @choper725 

Is someone using the old v1 layout with reduced funcitonality or can it be replced by the new one of @abapsheep?

some buttons seem not to work:
* when i press edit nothing happens
* when i press folder and go back then everything is closed

<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/1b4c928f-6706-4c91-9382-4e6eed5e12f3">

**Comment by choper725** [comment]
im not using it, but removing it is a breaking change..
probebly a new ver. for it will be suitable

**Comment by choper725** [comment]
@abapsheep  once opening select layout popup and hitting Back, the F4 is not opening anymore..

**Comment by choper725** [comment]
plus once saving layout and hitting Okay,

column texts seems to dissapear
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/ecc027b0-b13f-4001-aa8f-ade0d3fc52fc)

![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/fa4c5f08-f04a-44d3-a815-279a005d6975)

**Comment by abapsheep** [comment]
Hello everyone,
A brief explanation. 
![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/3e2521eb-2915-4e3f-9f37-16055bf44c7d)

1. the "ROW" column shows the technical names of the components. No dictionary texts are displayed here. Could I add this if you want? 
2. the layout has three functions EDIT / SELECT / DELETE. these functions can be called via the three buttons pen, folder and trash can. Depending on the context you are in, the corresponding button is colored blue.
3. in edit mode there are OKAY and CLOSE (previously BACK). Close exits the popup and the layout is not adjusted. OKAY accepts the changes. 
4. the layout can be saved via Save. 

I have not managed to set up the popup with tabs. Unfortunately I have to work with version 1.96.20 and am therefore somewhat limited. Maybe you have an idea how to make the function more user-friendly. I look forward to your feedback :) 


About your problem @choper725: 
When I call up Sample 204 and call F4 and then enter the layout, I can leave the layout via BACK or ESC and end up in the F4 help again. I can then also leave this via ESC or by selecting an entry. I can then call the F4 help again and also the layout.
I have not managed to make the texts disappear either...


In Sample 200 I had the problem that when I jump back and forth between the EDIT/SELECT/DELETE functions in the layout, I can no longer get to "on_after_layout" in my calling app. client->get( )-check_on_navigated returns a false here, but I would expect a true. (@oblomov-dev)

**Comment by oblomov-dev** [comment]
@abapsheep concerning the bug: can not reproduce the error, you just rerender the view but stay in the same popup, thats why no on_navigate is triggered when pressing EDIT/SELECT/DELETE. when you press back, the control flow goes to the previous stack app, which is for some reason also the popup v2 (and not the calling sample app). maybe there is something wrong earlier in the control flow?

**Comment by choper725** [comment]
@abapsheep the first error is once i hit back from select layout ir closes both the popup and i cant press the valuehelp on the input anymore until refresh of the entire page

the second one just happen at random, maybe ot got to do somwthing with abap version ? im on 7.5

**Comment by abapsheep** [comment]
@oblomov-dev I adjusted the App accordingly and now it works. https://github.com/abap2UI5/abap2UI5/pull/1199

**Comment by abapsheep** [comment]
@choper725 I have been klicking around for 5 minutes, I finaly could reproduce the column texts issue and fixed it. 

I cloud not reproduce the navigation Error ... Maybe have another try with the updated Version? When https://github.com/abap2UI5/abap2UI5/pull/1199 is merged.

**Comment by choper725** [comment]
sure ill test once merged

**Comment by oblomov-dev** [comment]
Thank you for the updates @abapsheep merged.

**Comment by choper725** [comment]
looks good on my end now..

**Comment by oblomov-dev** [comment]
everything works also on my end now. to keep the issues small I will close this one. But these layouts are a bigger topic and we could add a lot more stuff, so feel free to open a new issue as soon as we need more functionality.
