### ISSUE TITLE
Suggestion: Add MessageBox Samples for "Confirm" and "Alert" in abap2UI5 (Z2UI5_CL_DEMO_APP_008)

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1206]
Hi guys,

I would like to propose adding two MessageBox samples in abap2UI5, similar to the ones available in the UI5 Demo Kit. The samples are for "Confirm" and "Alert" messages.

Current State in UI5 Demo Kit and abap2UI5:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/66d330de-6b9f-48d9-90e0-61bc91628f7b)

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/4f11c87b-3cf2-4557-9a54-e099d8b6f5fb)

Updated abap2UI5 Samples:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/cd638d5a-0eb5-44f8-b913-c3c335579ef5)

Result After Execution:

-  Confirm MessageBox Execution Result:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/134e5e0e-6a92-4892-954b-3b5303062e5b)

-  Alert MessageBox Execution Result:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/28c17423-a611-45e8-a812-db5b24f9c717)

Adding these examples will allow us to align it closer to the UI5 Demo Kit, and they can serve as a guide for developers to implement similar functionalities in their applications.

I have submitted PR https://github.com/abap2UI5/abap2UI5-samples/pull/226 to implement this change. In case there are any questions or comments, please feel free to reach out.

Thank you for considering this suggestion.

Best regards,

Francisco Milán

**Comment by choper725** [comment]
i think there are check demo 002 footer

**Comment by francisco-milan** [comment]
Hi @choper725,

Thank you for your recommendation. I checked the footer of demo 002, and indeed, all the different types of MessageBox are demonstrated there.

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/5de4d2a6-280f-420e-8ac8-3184f23d9a7e)

However, I would like to suggest that, as much as possible, we align our abap2UI5 examples with those in the UI5 Demo Kit. By doing this, it will be easier for people already familiar with that site to find what they are looking for when they need to work with abap2UI5.

Replicating the examples from the UI5 Demo Kit will facilitate the transition and make it more intuitive for users to adopt abap2UI5.
Thanks again for your input.

Best,

Francisco Milán

**Comment by oblomov-dev** [comment]
Hi @francisco-milan,

good idea! making everything as similar as in the demo kit is a very good plan. 

the sample repository grew very fast and i did not expect in the beginning we will end up at a certain point with more than 200. so thank you again also @choper725  ;)

you will find a lot of stuff here and there which needs to be refactored, naming, unused code etc. always feel free to make corrections and bring it closer to the demo kit, this is a big help for us. PRs are merged.

Best regards.

**Comment by francisco-milan** [comment]
Hi @oblomov-dev,

Thank you for the positive feedback! I appreciate your support and encouragement.

Before closing this issue, I would like to make a few more changes to ensure that Sample 002 aligns more closely with the sample in the UI5 Demo Kit. I will be submitting a new PR soon to address these adjustments.

Best,
Francisco Milán.

**Comment by francisco-milan** [comment]
New PR has been submitted https://github.com/abap2UI5/abap2UI5-samples/pull/229

Best,

Francisco Milán.

**Comment by oblomov-dev** [comment]
@francisco-milan thank you, merged 🙏
