### ISSUE TITLE
Fix Typo in Demo 002

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1207]
Hi guys,

  I would like to fix a small typo that I found in the Class  "z2ui5_cl_demo_app_002", as you can see in the image below, there is a letter "s" missing in the word "suggestion".

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/049ca338-f15c-4f7b-aadd-72de3bf8f904)

Apart from that, I noticed that we have the words "GREY" and "grey" displayed as part of the list of suggestions in the box, for consistency sake I would like to propose changing those words to "GRAY" and "gray" respectively, as those words also appear in other sections of this demo.

I have created PR https://github.com/abap2UI5/abap2UI5-samples/pull/228 to address the points mentioned above.
In case you have any comments, feel free to share them.

Best,

Francisco Milán.

**Comment by oblomov-dev** [comment]
Thank you! 🙏

And again as i mentioned in the other issue, this samples repository grew fast and there was always a lack of time to make everything 100% correct. I am sure you will find a lot more bugs in this direction, feel always free to correct, refactor or create new ones. This is a big help!

Best regards.
