### ISSUE TITLE
Dynamic Title in Launchpad connector doesn't work

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#1209]
Hi,
I'm using the demo 188 in order to test the dynamic title in FLP.
The default title "abap2ui5" gets not replaced by the dynamic title value of variable "mv_title".
I installed the latest versions 1.130 (main, demo and FLP connector).

![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/eeac7823-3fcf-475e-9abd-421a41c60b8c)

![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/c1f170da-e0ad-4914-90ad-e4cf85f5c567)

Thanks,
Axel

**Comment by oblomov-dev** [comment]
thanks for the issue, i accidentally deleted to much, fixed it now, please try again.

**Comment by axelmohnen** [comment]
Hi @oblomov-dev ,
thank you for the fast reply.
Unfortunately, the fix doesn't work.

The object "z2ui5" (line 13) doesn't exist. Do you mean "sap.z2ui5" instead?
But, also for "sap.z2ui5" it won't work, because the object get's initialized again (line 25).
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/e50c2385-f32d-48ef-9587-6774933400f9)
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/86f64a69-e38e-4b3e-b6e8-b6652121d3e5)

Thanks,
Axel

**Comment by oblomov-dev** [comment]
thanks for the test, some things get mixed up here. adjusted now everything to sap.z2ui5 and also update the mai repo with https://github.com/abap2UI5/abap2UI5/pull/1210

please update connector+abap2UI5 and try again.

**Comment by axelmohnen** [comment]
Hi @oblomov-dev,
The dynamic title and the start parameter transfer works perfectly now! 
I will close the issue.
Thanks again :-)
