### ISSUE TITLE
Customizing Transport Request

### ISSUE THREAD

**Issue by abapsheep** [abap2UI5/abap2UI5#1220]
Hello everyone,

with my last PR I have added a new prototype app with which you can easily and quickly save changes to customizing tables in a transport. (z2ui5_cl_pop_transport).

The app lets you select all open customizing transport orders assigned to you in a pop-up.

![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/26cab583-ad24-43f3-a341-76e60d3029a0)

Changed data, the corresponding table name and a transport request can be transferred via a method. The changes are then transferred to the transport. 

![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/b35c434c-36fc-4402-ae76-3b42809ad8ff)

The whole thing works wonderfully on an OnPrem system. I have built in switches for the OnPrem and the Cloud world in the app. 

![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/f8ce1b68-4569-405c-8b1c-6896d12ca566)

I still managed to read open transport requests in the cloud, but I failed to save changes. Is this function of interest to any of you? Would anyone like to help me get the function completely cloud-ready?

**Comment by choper725** [comment]
@oblomov-dev i think abapsheep issues on his apps should be tagged in the README

**Comment by oblomov-dev** [comment]
@abapsheep unfortunately never did this in steampunk so far...
@choper725 what do you mean exactly? mark that this is on prem only till now?

**Comment by choper725** [comment]
yea, and also the layout and sh ones to put on readme

**Comment by oblomov-dev** [comment]
yes readme is very packed already, but maybe it makes sense to make an extra section in the samples repository, there is the differentiation between:
openUI5 - sapui5
old sdks - newer sdks etc.
and there is also an "under construction" section. as far as i see it, the layout popup is cloud ready. just f4 and TRs by now are not, i will put them to the "in construction" section and rearange them soon. but also hope we will solve the issues :)

**Comment by oblomov-dev** [comment]
@abapsheep maybe we can make the following adjustments:
(1) put the TR logic to the util_api class
(2) delete all business logic from the popup and consider using popup_to_select instead
(3) creating a sample to see how to call popup_to_select with TR information

**Comment by choper725** [comment]
> yes readme is very packed already, but maybe it makes sense to make an extra section in the samples repository, there is the differentiation between: openUI5 - sapui5 old sdks - newer sdks etc. maybe adding: on-prem only - cloud ready and there is also an "under construction" section. as far as i see it, the layout popup is cloud ready. just f4 and TRs by now are not, i will put them to the "in construction" section and rearange them soon. but also hope we will solve the issues :)

sound right, just dont want to scroll around issues to find those manuels

**Comment by oblomov-dev** [comment]
adjusted with https://github.com/abap2UI5/abap2UI5-samples/pull/235
