### ISSUE TITLE
 Step Input Control - Resizing Not Supported

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1223]
Hi everyone,

The Step Input control currently cannot be resized. To address this issue, I have opened a new Pull Request that introduces the ability to adjust its size. You can find the PR here: #1222.

Please review the changes and let me know if any modifications or additional information are needed.

Currently, the Step Input looks like this (in Demo 041):

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/fbc8d121-68ec-4a49-a8da-2e58641b8fb1)

After the change, we will be able to have something like this:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/7cd31a82-e6ec-457d-b949-5a64adce8895)

Thank you for your time and consideration.

Best regards,

Francisco Milán

**Comment by oblomov-dev** [comment]
good idea! thank you!
