### ISSUE TITLE
Close Button and Custom Icons for Message Strip Control

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1225]
Hi everyone,

I've noticed two issues with the Message Strip control:

-  The close button is not enabled.
-  Custom icons can't be used.

To address these, I have opened a new Pull Request (#1224) that introduces the ability to enable the close button and use custom icons.

Please review the changes and let me know if any modifications or additional information are needed.

After these changes, we will be able to have something like this:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/6b942ae1-0edf-4fec-95cd-c07de6b80abf)

Thank you for your time and consideration.

Best regards,
Francisco Milán

**Comment by francisco-milan** [comment]
I forgot to mention that I got this idea after looking at the UI5 Demo Kit documentation.

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/25135f60-e985-42a0-94eb-968400fb2bc6)

**Comment by oblomov-dev** [comment]
yes there are still a lot of attributes which need to be added, i also missed this one till now, thank you!
