### ISSUE TITLE
linkedIn

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1227]
trying out linkedin with abap2UI5 content at the moment, eg:
https://www.linkedin.com/posts/abap2ui5_abap-sapui5-opensource-activity-7210630218036752384-couW
or here:
https://www.linkedin.com/pulse/abap2ui5-integration-sap-business-technology-platform-13-installation-lf1re

probably will post from time to time more abap2UI5 stuff there, so everyone feel free to follow:
https://www.linkedin.com/company/abap2ui5

@choper725 if i post something about the topics you PR (eg. Chart.js) - if you want to be mentioned as the contributor, just let me know your linkedIn name (here or via PM). if this is not your wish, of course no problem, just want to make sure having asked

**Comment by choper725** [comment]
not on there :) go at it, its fine !
