### ISSUE TITLE
Deployment of Z2UI5_CL_CORE_HTTP_GET failed

### ISSUE THREAD

**Issue by GA887809** [abap2UI5/abap2UI5#1228]
Hi,
during the deployment of the downport framework I´m getting the following errors:
![image](https://github.com/abap2UI5/abap2UI5/assets/165759140/b6ae7704-1fd1-4779-ae6d-a04bbe5f3748)

Our system, were we deployed the framework is a SAP Solution Manager with the following releases:
![image](https://github.com/abap2UI5/abap2UI5/assets/165759140/e018e8b6-6951-4052-aaad-de952954743a)

Do you know a solution for this problem?

Thanks and kindly regards
Andre

**Comment by oblomov-dev** [comment]
Hi Andre,

did you already check these manual steps?
https://github.com/abap2UI5/abap2UI5-downport?tab=readme-ov-file#manual-steps--known-issues

You need to delete the ImageMapster class, it is not necessary for the main functionality and just optional.

best regards.

**Comment by cwildt** [comment]
You could copy the source code from the repository and insert it into the class on your system.
Then add ` ``. result = result && ` up to 100 lines below the start of the statement.

![image](https://github.com/user-attachments/assets/562d5922-d3aa-456e-9e57-16ef0219fbef)

**Comment by oblomov-dev** [comment]
@cwildt thank you for the hint, i shortened now the http_get method with https://github.com/abap2UI5/abap2UI5/pull/1268 if this is not enough, i recommend to further split the command the way you showed it.

Additionally the imagemapster class is now automatically deleted in the downport branch with
https://github.com/abap2UI5/abap2UI5/pull/1267

I'll close this, just reopen or create a new issue if you have further problems @GA887809
