### ISSUE TITLE
New Sample Based on UI5 Demo Kit (Flex Box - Basic Alignment)

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1234]
Hi Team,

I have submitted PR <a href="https://github.com/abap2UI5/abap2UI5-samples/pull/237">#237</a> for a new sample based on this one: <a href = "https://github.com/YOUR-REPO/abap2UI5/commit/7b8a27077e37a31fb6f470d53c7bcf013442373b2ff348a851e3983e515a55ea">Flex Box - Basic Alignment (from UI5 Demo Kit)</a>

I have placed the new sample here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/fb61cc12-44c7-478b-ab8d-626c1bddca08)

It looks like this:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/7d0b7d65-8601-4572-a06f-f2a5aed64a0f)

Please review and let me know if there are any improvements or changes needed.

Best regards,

Francisco Milan.

**Comment by oblomov-dev** [comment]
sample looks nice, this is exactly what is need for the sample repository, thank you 🙏
