### ISSUE TITLE
New Sample based on Text - Max Lines from UI5 Demo Kit

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1235]
Hi Team,

I have submitted PR <a href ="https://github.com/abap2UI5/abap2UI5-samples/pull/238">#238</a> to introduce a new sample based on the <a href="https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.Text/sample/sap.m.sample.TextMaxLines">Text - Max Lines example from the UI5 Demo Kit</a>.

The new sample can be found here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/a89901f8-8fae-4d57-a5c5-a84bef5e310e)

It looks like this:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/b59a5145-0903-4709-882f-b769224fda35)

Please review it and let me know if any improvements or changes are needed.

Best regards,

Francisco Milan

**Comment by oblomov-dev** [comment]
looks great, thank you! its merged now.
