### ISSUE TITLE
New Sample based on Radio Button from UI5 Demo Kit

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1236]
Hi Team,

I’m excited to share that I’ve submitted PR <a href="https://github.com/abap2UI5/abap2UI5-samples/pull/239">#239</a> featuring a new demo for the Radio Button control. This example builds on the <a href="https://ui5.sap.com/#/entity/sap.m.RadioButton/sample/sap.m.sample.RadioButton">Radio Button sample from the UI5 Demo Kit</a>.

The new sample can be found here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/c21a99fc-278e-4de3-b0c8-7f2221072940)

Here’s a preview:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/ed2ad4c7-97fe-46d7-bc76-d5b46807006d)

I look forward to your feedback and suggestions for improvements!

Best regards,

Francisco Milan

**Comment by choper725** [comment]
looks greak francisco !!

**Comment by oblomov-dev** [comment]
Nice! Thank you 🙏 PR merged.
