### ISSUE TITLE
New Sample: Implementing a Radio Button Group

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1239]
Hi Team,

I have submitted PR https://github.com/abap2UI5/abap2UI5-samples/pull/240 featuring a new demo for the abap2UI5 Radio Button Group. This example is based on the [sample from the UI5 Demo Kit](https://sapui5.hana.ondemand.com/#/entity/sap.m.RadioButtonGroup/sample/sap.m.sample.RadioButtonGroup).

You can find the new sample here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/9a514887-8ca4-4846-aeee-3b8deaaf9fe8)

Here’s a preview:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/f79b4124-6b7a-4a50-948a-2130676e413e)

Please let me know if you have any suggestions for improvements!

Best regards,

Francisco Milan

**Comment by oblomov-dev** [comment]
Nice, merged, again great work! thank you 🙏
