### ISSUE TITLE
New Sample: InfoLabel

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1240]
Hi Team,

I’ve submitted PR https://github.com/abap2UI5/abap2UI5-samples/pull/241 with a new demo showcasing the InfoLabel control. This example is inspired by the <a href="https://sapui5.hana.ondemand.com/#/entity/sap.tnt.InfoLabel/sample/sap.tnt.sample.InfoLabel">UI5 Demo Kit</a> and demonstrates its usage effectively.

You can find the new sample here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/361b9e1b-f1cc-4eee-a089-a779589ef8b1)

Here’s a preview:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/7415a2f5-d080-4093-82ad-2de83e56af36)

I’d love to hear your thoughts or suggestions for any enhancements!

Best regards,

Francisco Milan

**Comment by choper725** [comment]
💪🏻💪🏻

**Comment by oblomov-dev** [comment]
Hi @francisco-milan 
thanks again for the sample. Yes i think these samples are exactly what we need, making it easy for everyone to learn how to use abap2UI5 and providing abap snippets which can be easily copy&pasted. Maybe at a certain point we have the same samples as in the original UI5 sample repository and we can arrange them in a similar way or add a search function. But we'll see.
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/1f76eeaa-7436-4913-bf68-b3a14d9027b1">

Best regards.
