### ISSUE TITLE
New Sample: Input Types

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1242]
Hi Team,

I’ve submitted PR [abap2UI5/abap2UI5-samples#241](https://github.com/abap2UI5/abap2UI5-samples/pull/242) with a new demo showcasing the use of abap2UI5 Input Types. This example is inspired by the <a href="https://sapui5.hana.ondemand.com/#/entity/sap.m.Input/sample/sap.m.sample.InputTypes">UI5 Demo Kit</a> and effectively demonstrates its usage.

You can find the new sample here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/35b01551-1472-4be9-8df0-abe785d39afb)

Here’s a preview:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/a3ce06aa-e604-484a-853c-eab33325bfe6)

I’d love to hear your thoughts or suggestions for any enhancements!

Best regards,
Francisco Milan

**Comment by oblomov-dev** [comment]
nice, thank you!

**Comment by oblomov-dev** [comment]
PR is just merged.
