### ISSUE TITLE
New Demo: Input Password

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1244]
Hi Team,

I’ve submitted PR https://github.com/abap2UI5/abap2UI5-samples/pull/245 with a new demo showcasing the use of abap2UI5 Input Password. This example is inspired by the [UI5 Demo Kit](https://sapui5.hana.ondemand.com/#/entity/sap.m.Input/sample/sap.m.sample.InputPassword).

You can find the new demo here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/5cb40b85-c514-4522-84e9-e56f38272345)

And here’s a sneak peek:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/a13755e9-90ed-40be-82c4-4b9706aabd50)

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/3a895543-1c9c-45e7-85e1-f6941748fa70)

I'm eager to hear your feedback or any suggestions for improvements!

Best regards,
Francisco Milan

**Comment by oblomov-dev** [comment]
nice, thank you, PR merged!
