### ISSUE TITLE
New Demo: Standalone Icon Tab Header

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1245]
Hi Team,

I've just submitted a PR (Pull Request) for abap2UI5/abap2UI5-samples#246. This PR introduces a new demo featuring the Standalone Icon Tab Header, inspired by the <a href="https://sapui5.hana.ondemand.com/#/entity/sap.m.IconTabHeader/sample/sap.m.sample.IconTabHeader">UI5 Demo Kit</a>.

You can find the new demo here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/93f90e9f-c0b8-4f3b-954b-849da5704a87)

Here's a preview:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/2a1fbb36-d792-47d1-a0ed-b5e8f2c1a1cd)

I look forward to your feedback and suggestions for further improvements!

Best regards,
Francisco Milan

**Comment by oblomov-dev** [comment]
Thank you, merged 🙏
