### ISSUE TITLE
New Demo: Busy Indicator

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1249]
Hi Team,

I’ve submitted PR abap2UI5/abap2UI5-samples#249 with a new demo showcasing the use of the Busy Indicator. This example is inspired by the <a href="https://sapui5.hana.ondemand.com/#/entity/sap.m.BusyIndicator/sample/sap.m.sample.BusyIndicator">UI5 Demo Kit</a>.

You can find the new demo here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/eeb32cb8-1693-413b-88cd-c4ef9b19f150)

And here’s a sneak peek:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/dce8151f-b0f5-4c71-9f50-4a0fe315298c)

Please let me know in case you have any suggestions for improvements!

Best regards,
Francisco Milan

**Comment by oblomov-dev** [comment]
Nice, thank you, PR is merged!
