### ISSUE TITLE
New Sample: Action List Item

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1252]
Hi Team,

I’ve submitted PR abap2UI5/abap2UI5-samples#250 with a new demo featuring the Action List Control. This example demonstrates how to use this control effectively, inspired by the <a href="https://sapui5.hana.ondemand.com/#/entity/sap.m.ActionListItem/sample/sap.m.sample.ActionListItem">UI5 Demo Kit</a>.

You can find the new demo here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/bc6996c8-caaa-4690-87b8-e2686a2a2239)

And here’s a sneak peek:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/228ba1bd-f7fe-4b5a-91bb-d006a26195ec)

Please let me know if you have any suggestions for improvements!

Best regards,
Francisco Milan

**Comment by oblomov-dev** [comment]
Thank you, PR merged 🙏
