### ISSUE TITLE
New Sample: Title Toolbar

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1253]
Hi Team,

I've submitted PR <a href="https://github.com/abap2UI5/abap2UI5-samples/pull/251">abap2UI5/abap2UI5-samples#251</a> with a new demo showcasing the Title Control. This example demonstrates how to place a Title inside a Toolbar/OverflowToolbar and it is based on the <a href="https://sapui5.hana.ondemand.com/#/entity/sap.m.OverflowToolbar/sample/sap.m.sample.TitleToolBar">UI5 Demo Kit</a>.

You can find the new demo here:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/645a8b03-fbd1-40d9-a527-b36c398c69da)

And here’s a sneak peek:

![image](https://github.com/abap2UI5/abap2UI5/assets/36721657/f1cef1c5-f31c-4afd-bb57-7fbb204a8441)

Looking forward to your feedback!

Best regards,
Francisco Milan

**Comment by oblomov-dev** [comment]
Nice, thanks again
