### ISSUE TITLE
Error in Demo Z2UI5_CL_DEMO_APP_090

### ISSUE THREAD

**Issue by obluhm** [abap2UI5/abap2UI5#1260]
Hi gens,
first thanks to all of you managing this fantastic framework.

My current problem concerns the demo popup of Z2UI5_CL_DEMO_APP_090. I want to make use of the "Open P13N Dialog"  :
![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/236d9c95-5f1f-41c7-9a51-ff93f8e973bc)

![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/8490ee77-0eaa-427a-b7b6-73db47a61406)

When I use it only once it works fine. The popup appears and I can change values on it. But when I press the open button once again in the same session, I get an internal server error :

![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/f2cc179b-9da3-479a-b390-75c33240d316)

It complains that I am using two different mapper.

I guess it belong to this line in the code:
![image](https://github.com/abap2UI5/abap2UI5/assets/171541931/a5a9a5d7-16b2-437d-a37e-22d1c9e75f14)

custom_mapper = z2ui5_cl_ajson_mapping=>create_lower_case( )

Can anybody help in understanding the problem. I thought the popup gets destroyed after closing and is not reusing anything.

Thanks in advance.
Oliver

**Comment by oblomov-dev** [comment]
thanks for finding this, there war a bug, should be fixed now with:
https://github.com/abap2UI5/abap2UI5/pull/1265

**Comment by obluhm** [comment]
Thanks for for the correction. The demo runs fine again.
Oliver
