### ISSUE TITLE
Syntax error in the Launchpad handler class - Z2UI5_CL_LAUNCHPAD_HANDLER~IF_HTTP_EXTENSION~HANDLE_REQUEST

### ISSUE THREAD

**Issue by mail4deep2000** [abap2UI5/abap2UI5#1262]
Method z2ui5_cl_http_handler=>main does not exist and results in syntax errors.

**Comment by oblomov-dev** [comment]
which version do you have? on the newest ones it does exist:
https://github.com/abap2UI5/abap2UI5/blob/c47f9ee7c1759421afb4616f56970b6c87f3b8f0/src/02/z2ui5_cl_http_handler.clas.abap#L19

**Comment by oblomov-dev** [comment]
i clode this one, i guess you just pulled an outdated version. but reopen if you have further questions.
