### ISSUE TITLE
Question Richt Text Editor

### ISSUE THREAD

**Issue by Marchl-Woid** [abap2UI5/abap2UI5#1264]
Hello togehter
I tried playing around with the richt text editor. Maybe I am doning something wrong, but when starting the Demo the Editor appears for the glimps of a second and then vanished

![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/2b36d94d-7810-4893-b6b2-4e19748cbe54)

As I have seen, this is the editor vom SAP UI5 and in Open UI5 there is no alternativ.... Has someone implemented (maybe) an alternativ rich text editor as cc?

**Comment by oblomov-dev** [comment]
On my side it works correctly, after a small delay the editor is displayed:
<img width="1339" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/b0ea8e40-8479-4955-9688-26edce2adce6">

The UI5 Rich Text Editor, is based on:
https://www.tiny.cloud/

This original editor has a lot more functionlity and it should be no problem putting it into a custom control and make it usable with abap2UI5.

**Comment by Marchl-Woid** [comment]
HI @oblomov-dev 
seems that the demo Z2UI5_CL_DEMO_APP_106 has a problem on my system.
I have simplified the ui and now it works

```
  data(lo_p) =  view->shell(
            )->page(
                    title          = 'abap2UI5 - Rich Text Editor'
                    navbuttonpress = client->_event( val = 'BACK' )
                    shownavbutton = xsdbool( client->get( )-s_draft-id_prev_app_stack IS NOT INITIAL )
                )->header_content(
                    )->link(
                        text = 'Source_Code'

                        target = '_blank'
                )->get_parent(
                ).


               lo_p->rich_text_editor( width = `100%`
                                        height = `400px`
                                        value = client->_bind_edit( mv_value )
                                        customtoolbar = abap_true
                                        showGroupFont = abap_true
                                        showGroupLink = abap_true
                                        showGroupInsert = abap_true
                                        wrapping = abap_false
                       ).

      client->view_display( view->stringify( ) ).
```
Thanks for the quick answer. But I will have a look maybe as a cc
