### ISSUE TITLE
New Sample: Page, Toolbar & Bar.

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1266]
Hi Team,

I've just submitted a new PR <a href="https://github.com/abap2UI5/abap2UI5-samples/pull/264">https://github.com/abap2UI5/abap2UI5-samples/pull/264</a> for another sample that is based on a demo from the [UI5 Demo Kit](https://sapui5.hana.ondemand.com/#/entity/sap.m.Page/sample/sap.m.sample.Page).

You can find the new sample here:

![image](https://github.com/user-attachments/assets/bc5da0a0-8c27-4205-ab6c-fa253f13a1fe)

Here's a sneak peek of the demo:

![image](https://github.com/user-attachments/assets/adb52108-b65e-4026-9b7f-e50146642c8d)

I’m eager to hear your thoughts and feedback!

Best regards,
Francisco Milan

**Comment by oblomov-dev** [comment]
thank you, looks great, merged!
