### ISSUE TITLE
dateRangeSelection: minDate binding doesn't work

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1271]
Hello folks,

this week I struggled a bit with dateRangeSelection control. Therefore I tried to replicate this demo app in our samples repo.
https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.DateRangeSelection/sample/sap.m.sample.DateRangeSelection/code
https://github.com/christianguenter2/abap2UI5-samples/blob/c5798ee5c40c1f1d69dca3574464dc43ff368f64/src/z2ui5_cl_demo_app_228.clas.abap

![grafik](https://github.com/user-attachments/assets/19f2ac7d-0d7e-496f-94c3-f98f5bcf628f)

Basic value binding works but now I struggle with minValue. This is what I tried so far:
https://github.com/christianguenter2/abap2UI5-samples/blob/c5798ee5c40c1f1d69dca3574464dc43ff368f64/src/z2ui5_cl_demo_app_228.clas.abap#L86-L94

but results in
![grafik](https://github.com/user-attachments/assets/55dfe75c-884b-4ce5-9664-63391396f154)

Most likely I'm doing something completely wrong here. Any hints how I could make that work?

**Comment by choper725** [comment]
should ne a js date object, check gantt chart demo or planning calender demo to see how its done

**Comment by christianguenter2** [comment]
@choper725 thanks. That helped a lot.
