### ISSUE TITLE
New Sample: Numeric Content Without Margins

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1272]
Hi Team,

I've just submitted a new PR abap2UI5/abap2UI5-samples#265, featuring a new sample that demonstrates how to display numeric content without margins. This example showcases the Numeric Content control aligned to the left and top, ensuring no margins are present. This demo is based on the sample from the UI5 Demo Kit: [Numeric Content Without Margin](https://sapui5.hana.ondemand.com/#/entity/sap.m.NumericContent/sample/sap.m.sample.NumericContentWithoutMargin/code).

You can find the new sample here:

![image](https://github.com/user-attachments/assets/fc3d706e-e6ea-47bf-9743-1225d3e0c23e)

Here's a sneak peek of the demo:

![image](https://github.com/user-attachments/assets/e6d16b7d-7a0d-44eb-b910-e486a4c266c8)

I'm looking forward to your thoughts and feedback!

Best regards,
Francisco Milan

**Comment by oblomov-dev** [comment]
Nice looks as always great, thank you for your work, merged.🙏
