### ISSUE TITLE
Error running abap2ui5 samples with gantt chart

### ISSUE THREAD

**Issue by schocker4** [abap2UI5/abap2UI5#1278]
Hi there,

I tried to test the gantt chart samples
- Z2UI5_CL_DEMO_APP_076

I got following error:
"openui5 SDK is loaded, module: 'sap/gantt/simple/GanttChartContainer.js' is not availabe in openui5"

With sample
- Z2UI5_CL_DEMO_APP_179
I got following error:

"openui5 SDK is loaded, module: 'sap/gantt/simple/ContainerToolbar.js' is not availabe in openui5".
Other samples are running without problems.

Can you help please.
Axel

**Comment by choper725** [comment]
openui5 sdk soes not have gantt chart control, only the ui5 sdk does

**Comment by schocker4** [comment]
Okay. But how can I use gantt in abap2ui5? Do I need some special 'view->_generic_property( ... )' calls during initialization?
I tried it that way but I failed.
Thank you

**Comment by choper725** [comment]
in the local http handler u created you need to reference the ui5 sdk

**Comment by oblomov-dev** [comment]
I close this, can be solved with the mentioned solution, just reopen if you have further questions @schocker4. thank you for your help @choper725

**Comment by Ennowulff** [comment]
Thanks @christianguenter2 
cann you tell me which url I need to use in order to have the mentioned ressources available?

**Comment by Ennowulff** [comment]
yes. I understood, that the error will be gone if I define a newer version here

<img width="1154" height="743" alt="Image" src="https://github.com/user-attachments/assets/fdb508e5-f338-4f30-9e1f-a7fef3e607b3" />

But the error is still there. 
So I might have misunderstood what to do...?!
