### ISSUE TITLE
Error loading view:Unexpected token '&'

### ISSUE THREAD

**Issue by ptyqsh** [abap2UI5/abap2UI5#1296]
Install  abap2UI5-connector_sap_fiori_launchpad  1.131.0  , Then configure according to the document，but not working

console：

 Failed to load resource: the server responded with a status of 404 ()
abap.js:63  2024-07-30 10:11:47.085500 [ODataMetadata] initial loading of metadata failed -  
c @ abap.js:63
abap.js:63  2024-07-30 10:11:47.085600 Error: Invalid metadata document -  
c @ abap.js:63
abap.js:63  2024-07-30 10:11:47.111399 failed to load JavaScript resource: z2ui5/Component-preload.js -  sap.ui.ModuleSystem
c @ abap.js:63
abap.js:64  声明失败：ManagedObject.apply: encountered unknown setting 'inboundPermanentKey' for class 'sap.ushell.components.container.ApplicationContainer' (value:'X-SAP-UI2-PAGE:X-SAP-UI2-CATALOGPAGE:ZABAP2UI5:00O2TRD8TODJFUOQNRY0MZVCZ')
a @ abap.js:64
abap.js:285

**Comment by oblomov-dev** [comment]
which ABAP release do you use?

The Fiori Connector needs minimum:
SAP Netweaver (v.7.56) or S/4 2021 (Standard ABAP)
