### ISSUE TITLE
PR: Side Navigation

### ISSUE THREAD

**Issue by LadwigDev** [abap2UI5/abap2UI5#1304]
Hello,
I would like to contribute a PR to add the side navigation. Unfortunately I have no SAP-System where I am allowed to install an online version of ABAPGit. Maybe someone can add these methods to the project (changes + demo app attached)

[Demo App Side Navigation.txt](https://github.com/user-attachments/files/16559660/Demo.App.Side.Navigation.txt)
[Enhancements Z2UI5_CL_XML_VIEW.txt](https://github.com/user-attachments/files/16559661/Enhancements.Z2UI5_CL_XML_VIEW.txt)

- Added Method SIDE_NAVIGATION
- Added Method NAVIGATION_LIST
- Added Method NAVIGATION_LIST_ITEM
- Added Method FIXED_ITEM
- Added ID parameter to the FLEX_BOX method

Concerning the demo app: When you change the menu entry the whole view is re-rendered. I was not able to figure out how to insert a nested view into a flex_box. Maybe there is a way to increase the app performance if you want to have a look at it.

Best regards
Jan

**Comment by francisco-milan** [comment]
Hello Jan,

Thank you for offering to contribute to the project with the side navigation enhancements and demo app. Your proposed methods and updates seem like great additions.

If installing the online version of abapGit isn't feasible for you, one alternative is to open a pull request (PR) directly on GitHub using the web interface. You can upload your changes here, and we'll be able to review and merge them into the project.

Regarding the demo app's performance issue with re-rendering when changing menu entries, I'll take a look into how nested views within a FLEX_BOX can be optimized. If I find any potential improvements, I'll be sure to share them with you.

Thanks again for your contributions, and feel free to reach out if you have any questions about the PR process on GitHub.

Best regards,
Francisco.

**Comment by francisco-milan** [comment]
Another option you might consider is downloading and installing the ABAP Cloud Developer Trial 2022. This environment would allow you to install ABAPGit and test your changes directly. You can find more details and the download link here: [ABAP Cloud Developer Trial 2022](https://community.sap.com/t5/technology-blogs-by-sap/abap-cloud-developer-trial-2022-available-now/ba-p/13598069).

**Comment by LadwigDev** [comment]
Hi @francisco-milan 
I have tried using the web interface and opened a pull request. I hope I did everything correctly.

Will definetly check out the Developer Trial Version.

Best regards
Jan

**Comment by francisco-milan** [comment]
Hi Jan,

Thank you for opening the pull request! Please take a moment to review the messages provided by abaplint and adjust the code accordingly.

![image](https://github.com/user-attachments/assets/bc884ae7-e362-4ed7-baf5-a78131c311a6)

![image](https://github.com/user-attachments/assets/9b4b9220-745c-4cfd-841c-dd6ffa1d3377)

![image](https://github.com/user-attachments/assets/56ec577f-e0d8-44ea-88b7-833bfcb84131)

Using your fork, navigate to the folder that contains the code of the class z2ui5_cl_xml_view (src/02/01/01). You can use the pencil button to switch to Edit mode and apply the necessary changes.

![image](https://github.com/user-attachments/assets/7eeb6b4c-c3a2-4bb6-a9c1-b3e7725b1106)

![image](https://github.com/user-attachments/assets/6a8f7a92-ed66-41a5-9e2f-7be08d681f4c)

Let me know if you have any questions or need further assistance.

Best regards,
Francisco.

**Comment by LadwigDev** [comment]
Hi @francisco-milan ,
I have edited the file and now all tests seem to have been passed. Does anything else need to be done or can the PR now be edited?

Thanks for your help, I have never worked with abaplint before...

Best regards
Jan

**Comment by francisco-milan** [comment]
Hi @LadwigDev 

Thanks for the update! I'm glad to hear that all tests have passed.

Before we can proceed with the merge, the changes will need to be reviewed and approved by @oblomov-dev. Once that's done, we'll be able to move forward with the PR.

If you have any questions or need further assistance, feel free to reach out. I'm happy to help.

Best regards,
Francisco.

**Comment by oblomov-dev** [comment]
Thanks for your help @LadwigDev and @francisco-milan

**Comment by francisco-milan** [comment]
🎉 Welcome to the abap2UI5 team, Jan! 🙌 Your work is much appreciated, and we're excited to have you on board. 🚀

P.S. Feel free to go ahead and close the PR. Thanks again for your great work! 👍
