### ISSUE TITLE
Extension SAPUI5 elements

### ISSUE THREAD

**Issue by thomasmarkert** [abap2UI5/abap2UI5#132]
Hey,
Thank you for your work in creating the ABAP2UI5 tool. For me as an ABAP developer, this is a huge relief. I think it's very important that this tool gives us a means to ease the transition. I would try to create some examples in order to present them to the specialist department. However, some SAPUI5 elements are still required for this. Would it be possible to integrate this into the HTTP handler?
The relevant elements are as follows:

Planning Calendar
https://sapui5.hana.ondemand.com/#/entity/sap.m.PlanningCalendar

MultiInput
https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiInput

Smart Table
https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smarttable.SmartTable

Smart Filter Bar
https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smartfilterbar.SmartFilterBar

Object Page Layout
https://sapui5.hana.ondemand.com/#/entity/sap.uxap.ObjectPageLayout

Or is there another way to extend the SAPUI5 elements?

Best regard
Thomas

**Comment by choper725** [comment]
ill throw in there a Dynamic Page Layout also


brw GREAT Project !!!

**Comment by oblomov-dev** [comment]
Hello together,

thank you for trying abap2UI5! I gave this controls a quick look:

Object Page Layout / Dynamic Page Layout
A lot of XML to write but so far i don't see any javascript dependencies which make this not compatible. they can be added to abap2UI5.

MultiInput
Looks compatible, but i need to check the transfer of the model again.

Planning Calendar
A complex control with a lot features, changing the size, drag&drop etc. Normally i would say a real UI5 freestyle application is the better way for this. But if you just want to use the planning calender as a simple outpout without using all the other features it could be possible to extend abap2UI5 and send an XML with the planning calender controls to the frontend. Do you have a complex use case in mind?

Smart Table / Smart Filter
Smart means in this context that the UI and functionality of the UI5 Control is defined with OData annotations which are send from the backend. This is a different concept than abap2UI5 and more the Fiori Elements way. Therefore they are not compatible! But that does not mean that the output and functionality created with a smart control is also not possible with abap2UI5, depending on your use case you maybe have the chance to develop it by yourself.
Smart Filter - you can create an input field and a search button and then you have to implement the filtering of the table data by yourself at the press event of the button (look at the demos with f4 helps for an example)
Smart Table - take a look to the not-smart [sap.m.table]( https://sapui5.hana.ondemand.com/#/entity/sap.m.Table) which is working with abap2UI5.
Which functionality do you have in mind that you need to use a smart table and a smart filter?

If you want to try a control which is still not a part of z2ui5_if_view, you can use the method _generic where you can import any namespace, controlname and attribute. I will add a documentation that you have an example of how to use this.

Best regards!

**Comment by choper725** [comment]
will be great to have some documentation on how we can add new controls which are not yet implemented, i think this will open this project to the community even more !

**Comment by thomasmarkert** [comment]
Planning Calendar
I would like to display a kind of planning table for the relevant shifts in the production area. Would it be possible to change or create the corresponding appointment entry?

Smart Table / Smart Filter
I would like to use the SmartBar for the selection of the corresponding table entries.
In the SmartTable I need the following functions:
- Sort
- Filter
- Aggregation
- Selection of columns
- Saving the layout

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
Added now the following:
* Object Layout
* Dynamic Page Layout
* Multiinput (see demo selection screen more controls)
* a way to create views more generic (https://blogs.sap.com/2023/04/12/abap2ui5-5-6-extensions-with-xml-views-html-js-custom-controls/)

I will check the following in the next weeks:
* Smart Table / Smart FIlter
* Planning Calender

**Comment by Th0masMa** [comment]
Hi,

For the namespace I have sap.ui.table

the following methods were added to the Z2UI5_CL_XML_VIEW class:
UI_TABLE
UI_COLUMN
UI_COLUMNS
UI_EXTENSION
UI_TEMPLATE

as well as the extension in the constructor
APPEND VALUE #( n = `xmlns:u` v = `sap.ui.unified` ) TO mt_prop.
See example Price + Waers columns

I have also developed an example for this.
Z2UI5_CL_APP_DEMO_59

The filter and sorting on columns does not work here. Furthermore, the button in the toolbar of the table does not work.
Maybe someone can help here.

Would it be possible to write a short tutorial on how to change the customization from my on-prem system to the git repository.
[Z2UI5_CL_APP_DEMO_59.abap.txt](https://github.com/abap2UI5/abap2UI5/files/11882105/Z2UI5_CL_APP_DEMO_59.abap.txt)
[Z2UI5_CL_XML_VIEW.abap.txt](https://github.com/abap2UI5/abap2UI5/files/11882107/Z2UI5_CL_XML_VIEW.abap.txt)

**Comment by oblomov-dev** [comment]
Hi Thomas,

it would be great when you merge your extensions of the View class to abap2UI5. I created a more detailed explanation, you can find it here:
https://github.com/abap2UI5/abap2UI5/blob/main/docs/how_to_contribute.md
Pictures are made with adt-git but for on-premise abapGit it is all the same (just a different UI). 
After there is the chance to check your example.
Best regards.

**Comment by Th0masMa** [comment]
Hi,

In On-Prem System i dont find the Button Fork.
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/6a550190-d4cc-4351-8e79-2a19d31f2852)
I found this function, but I don't know if this is the right one. 
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/13887ea4-8673-4b51-ac58-18c69bd1d054)


Best Regards
Thomas Markert

**Comment by oblomov-dev** [comment]
Do the first step on github, there you can create a fork and you will get an own copy of the project. I updated the guidelines:
https://github.com/abap2UI5/abap2UI5/blob/main/docs/how_to_contribute.md
Then you can continue with abapGit on your system and "change remote".
best regards.

**Comment by Th0masMa** [comment]
Hi,

I did the fork on git and now have a copy in my git account.
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/5e7e7836-35d8-488a-91f0-b3ecd545395d)

I change the code and Stage in ABAPGIT
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/81294f71-1ba3-4abb-add6-8a6c17ee7dd3)
After that I get the following window. What do I have to do here?
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/ad9ea17e-4eaf-402d-9e6b-fe163e74f37b)

Best Regards
Thomas

**Comment by Th0masMa** [comment]
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/ba68897e-43d4-46f9-95b1-aca7fc6b66e1)

**Comment by oblomov-dev** [comment]
Mhh ok it is a while ago since i made this on-premise... i am not sure about the naming anymore.

Try "patch" now.

**Comment by Th0masMa** [comment]
I push Patch.
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/a24899ff-6e2c-45cf-9dcb-c586f83e533a)

**Comment by christianguenter2** [comment]
Whats SAPGui are you using?

**Comment by Th0masMa** [comment]
I use sagui Version 7.70.

Mit freundlichen Grüßen
Thomas Markert

Christian Günter ***@***.***> schrieb am Do., 29. Juni 2023,
21:56:

**Comment by christianguenter2** [comment]
Looks like SAPGui for Java? There are known issues.
https://docs.abapgit.org/user-guide/setup/sapgui.html

**Comment by oblomov-dev** [comment]
Hi thomas,

thank you for your PR and that it worked out in the end. 👍

This issue is very big now and includes different topics, therefore I close this issue, but feel free to open a new one. Maybe for each topic one issue, that makes it easy for us to help out.

@christianguenter2 thank your for your help and having an eye on abapgit topics.

Best regards.
