### ISSUE TITLE
Popup stack?

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#1328]
Hi @oblomov-dev ,
been away for some time as im currently busy with other stuff,

been thinking about implementing Some popup stack, not an infinite one, just one more to be able to open popup over popup,

any idea where to start do so? or its just duping the popup methods to popup2 ??

**Comment by oblomov-dev** [comment]
Hi @choper725,

Welcome back, yes had this situation here and there but to keep the frontend as small as possible i tried to do every in the backend. Therefore made sample 222:
Z2UI5_CL_DEMO_APP_161

This sample simulates a popup stack at the frontend for the user but it just has one layer at the frontend while remembering its stack in the backend. This reduces the complexity in JS a lot!

What is your use case exactly? Do you really need a "real" stack at the fronted and can’t do it in the backend like done in the sample above?

As always, no problem to extend abap2UI5, just want to make sure that it is really needed first.

Best regards.

**Comment by oblomov-dev** [comment]
@choper725 can this be closed? otherwise just reopen if you want to move on
