### ISSUE TITLE
custom controls in extra repository

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1331]
To keep the abap2UI5 core small, i separated the optional custom controls to a separated repository now:
https://github.com/abap2UI5-apps-addons/custom-controls

If you installs abap2UI5+custom_controls everything works as before.

Some cc are large and caused some troubles on older releases, i also hope they got more visible in an extra repository and its easier to manage them or add new ones there. abap2UI5 got very big during the last year and i separated some functions now to this place:
https://github.com/abap2UI5-apps-addons

@choper725 you did a lot of work with the CC, added you to the repository and organization (just in case if you want), i will also setup abaplint with less restrictive rules as in the abap2UI5 repo, changes can be done more easily with this.

**Comment by choper725** [comment]
great idea !

we should follow this up on checking class exsist on relevant demos.. just to avoid errors

**Comment by choper725** [comment]
great !
