### ISSUE TITLE
File Uploader control - Not able to Disable 

### ISSUE THREAD

**Issue by VirajCoulecar** [abap2UI5/abap2UI5#1333]
Hello,

I am working with the File Uploader control and I am passing abap_false to the "enabled" attribute as below but somehow it is not getting disabled.

    ir_parent->_z2ui5( )->file_uploader(
      value             = ir_client->_bind_edit( val = me->ms_screen-file_value view = ir_client->cs_view-nested )
      path              = ir_client->_bind_edit( val = me->ms_screen-file_path view = ir_client->cs_view-nested )
      upload            = ir_client->_event( iv_event_id )
      buttononly        = abap_true
      buttontext        = TEXT-t23
      icononly          = abap_false
      checkdirectupload = abap_true
      enabled           = abap_false ).

May I request you to have a look and let me know how to fix it.

Regards,
Viraj Coulecar

**Comment by choper725** [comment]
hi Viraj, enabled property is missing from CC implementation.. should be added, hope i get the time to do so, feel free to add it if u want in the CC js code..

**Comment by oblomov-dev** [comment]
fixed with https://github.com/abap2UI5/abap2UI5/pull/1334

**Comment by oblomov-dev** [comment]
@VirajCoulecar the issue and tested from my side. i will close this one. just reopen if you have further questions.
