### ISSUE TITLE
Syntax error in program "Z2UI5_CL_AJSON"

### ISSUE THREAD

**Issue by snbandi** [abap2UI5/abap2UI5#1388]
I installed the latest repo and while launching the service, it comes with this message -

Short Text
    Syntax error in program "Z2UI5_CL_AJSON================CP        ".

What happened?
    Error in the ABAP application program.

    The current ABAP program "Z2UI5_CL_CORE_JSON_SRV========CP" had to be
     terminated because it found a
    statement that could not be executed.
    In include "Z2UI5_CL_AJSON================CP        ", in line 5 of program
     "Z2UI5_CL_AJSON================CP        ", the following syntax errors
    have occurred:
    This variant of the command "INCLUDE" is not allowed in the restricted
     language scope.

This is in NetWeaver ECC 6.0 Ehp8 system

SAP_BASIS	750	0029	SAPK-75029INSAPBASIS	SAP Basis Component
SAP_ABA	750	0029	SAPK-75029INSAPABA	Cross-Application Component

In SE24, the syntax check comes as below -

	This variant of the command "INCLUDE" is not allowed in the restricted language scope.

Can you see why this error is coming up?

**Comment by oblomov-dev** [comment]
hi @snbandi,

thank you for finding this, it might be that i accidentally added an incompatibility for your release. made a fix now: 
https://github.com/abap2UI5/abap2UI5/pull/1389

can you pull again and check it one more time?

**Comment by snbandi** [comment]
Thank you. It fixed the problem.

**Comment by snbandi** [comment]
Thank you. It fixed the problem.
