### ISSUE TITLE
ViewModel - setSizeLimit - json_model_limit

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1399]
@choper725 i think the parameter json_model_limit of the http handler was a PR from you?

cleaning up the index.html at the moment, thinking of changing this parameter to the view. created a sample for this:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_071.clas.abap

Use z2ui5_cl_http_handler2 to test it.

Maybe it could be the better position. Then it can only be used when it is really needed and can also be flexible changed with every view_display.

Is this functionality still in use? any strong opinions on that? otherwise i will maybe change it and of course also change it for popups & popover.

**Comment by oblomov-dev** [comment]
i'll just move on, reopen if something causes troubles on your side.

its now integrated with branch: update-handler
sample 71 to see how it works.

**Comment by choper725** [comment]
actually it is in use globally on a handler, as this functionality is not make sense once in view

**Comment by oblomov-dev** [comment]
updated the handler now, just adjust the position of the sizelimit import as described here, but the logic itself is unchanged:
https://github.com/abap2UI5/abap2UI5/issues/1429

Somehow i still think its better to import it on app level or on model level, as this would also happen in normal ui5 freestyle development. as it is now all size limits are always changed for every app and there is no chance to differentiate between models/apps. but lets keep it like this for now but maybe a topic for the future....
