### ISSUE TITLE
Demo z2ui5_cl_demo_app_183 fails

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1413]
![image](https://github.com/user-attachments/assets/871b9455-0de2-4242-ad8b-7295e09de9ef)

![image](https://github.com/user-attachments/assets/100b9a98-5c65-4cd4-8e7b-f684553583f9)

**Comment by oblomov-dev** [comment]
thanks for documenting this! 
fixed with: https://github.com/abap2UI5/abap2UI5/pull/1415

**Comment by christianguenter2** [comment]
Thx. Fix works.
