### ISSUE TITLE
S/4 Public Cloud - Access abap2UI5 apps for business users

### ISSUE THREAD

**Issue by Jafuss** [abap2UI5/abap2UI5#1416]
Hi, basically I built an app using the ABAP2UI5 Repository, we are working on HANA Public Cloud environment and everything went OK in DEV tenant, we ran it and I created a custom tile to execute the HTTP Service. After some tests we moved everything to Test Tenant, transports and software collection import went OK, but when we tried to execute our custom tile in Test, it throws a 403 Forbidden error, also we tried with the Http handler URL and the DEV URL (changin tenant ID), but the same error shows up.

Had someone a similar problem when tried to move their APP to another tenant? We created an App sent by SAP, so it is supposed to run in PRD tenant. Have we forgot something in the process after transport? maybe somo authorizations.

**Comment by oblomov-dev** [comment]
Tested now for S/4 Public Cloud:

Use this Repository:
https://github.com/abap2UI5/frontend

(1) Pull the cloud branch with adt-abapgit. <br>
(2) Deploy the app in app folder to S/4 Public Cloud

Use this Guideline:
https://developers.sap.com/tutorials/abap-s4hanacloud-procurement-purchasereq-shop-ui..html#4c15de5c-bce6-46d0-a634-0008261b3117

**Comment by oblomov-dev** [comment]
All information now collected here:
https://abap2ui5.github.io/docs/configuration/s4_public_cloud.html

I close this issue, just create a new one if you run into problems.
