### ISSUE TITLE
New Demo Based on UI5 Demo Kit's "Flexible sizing - Toolbar" Sample

### ISSUE THREAD

**Issue by francisco-milan** [abap2UI5/abap2UI5#1418]
Hi everyone,

I have created a new demo based on the sample from the UI5 Demo Kit: [Flexible sizing - Toolbar](https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.Page/sample/sap.m.sample.PageListReportToolbar). I will be submitting two pull requests (PRs) soon:

 - First PR: Includes the necessary changes to make the demo work.
 - Second PR: Contains the demo itself.

However, I noticed two differences between the new demo and the one from the UI5 Demo Kit, and I would appreciate any suggestions to help resolve them:

 **1. No Margin Next to the Analytical Table:** The new demo lacks a margin on both sides of the area where the Analytical Table is placed. I noticed something similar happens with regular Tables when they're not responsive, and in those cases, the margin can be added using the **"inset"** property. Unfortunately, this property isn't available for the AnalyticalTable.

 **2. Table Height:** The height of the area containing the Analytical Table looks smaller than the one in the original UI5 Demo Kit sample.

I've attached two screenshots that highlight these differences. If anyone has suggestions on how to make the abap2UI5 demo more closely resemble the UI5 Demo Kit version, I would greatly appreciate your input.

![image](https://github.com/user-attachments/assets/528d8c4e-7b5a-49e3-963f-d060742cb2cd)

![image](https://github.com/user-attachments/assets/ad83b8b7-4239-441b-805a-838f653f207e)

Thanks in advance for your help!

Best regards,
Francisco.

**Comment by oblomov-dev** [comment]
mhh played a little bit around with it but also did not find a solution. first i thought it is because there are two pages on your sample:
<img width="700" alt="Google Chrome 2024-09-13 15 05 02" src="https://github.com/user-attachments/assets/6fde1333-1216-439c-bd4a-087116f59b44">
But changing it makes no difference. I would guess it is because a control which is on a higher level which influences the output, eg. the splitting container or the menu on the left. maybe someone else has an idea.

**Comment by francisco-milan** [comment]
Thanks @oblomov-dev

After further investigation, I believe the issue might be related to how I’m handling the layout_data for the Analytical Table in the abap2UI5 version. In the original sample, the table’s layout data might be associated with the table namespace. However, in abap2UI5, I haven't specified the namespace for the layout_data method (refer to the images below).

![image](https://github.com/user-attachments/assets/32b30a2a-f4c4-40a3-9f6d-54e8dd1c479b)

![image](https://github.com/user-attachments/assets/d906dcf8-d9cc-4af7-80a2-915253074354)

I tried specifying the namespace like this:

![image](https://github.com/user-attachments/assets/f27ca24b-7594-4053-86b3-8c0da4e9ba5c)

but I encountered the following error:

![image](https://github.com/user-attachments/assets/a9d0d4ff-9df1-4c1e-95f7-ace31f3430e2)

In previous demos I’ve either used the **`form`** namespace for layout_data or left the namespace blank, but I’m unsure how to handle this specific case where the **`table`** namespace seems necessary. I’d appreciate any advice on how to specify the **`table`** namespace without running into this error.

Thanks in advance for your help!

Best regards,
Francisco

**Comment by oblomov-dev** [comment]
you first need to check for the exact namespace in the sample, look to the top, there you find sap.ui.table:
<img width="800" alt="image" src="https://github.com/user-attachments/assets/5d03cab2-8b83-42c5-8362-01f1ae031882">

Next check the namespace mapping in abap2UI5 here which is "table":
https://github.com/abap2UI5/abap2UI5/blob/main/src/02/z2ui5_cl_xml_view.clas.abap#L9721

So basically you did everything right ;)

Maybe the openui5 framework does not contain this control?

can you bootstrap as a test for example with:
https://ui5.sap.com/resources/sap-ui-core.js

**Comment by francisco-milan** [comment]
Hi @oblomov-dev,

Thank you for your suggestion! After following your recommendation and bootstrapping with https://ui5.sap.com/resources/sap-ui-core.js, along with some minor adjustments to the abap2UI5 code, the demo is now working perfectly.

![image](https://github.com/user-attachments/assets/5fc62445-e0ca-4aab-8c06-ab1a513185bc)

I appreciate your help in pointing out the namespace issue and guiding me through it. Your insights were spot on!

If we can't stick with the ui5.sap.com bootstrap, is there another alternative you'd recommend in this case?

Best regards,
Francisco.

**Comment by francisco-milan** [comment]
Actually, never mind— I reverted the change and switched back to bootstrapping with the original src, and it worked! I will be submitting a new PR to update Demo 284 soon. Thank you again!
