### ISSUE TITLE
Stickyness II - Rollback Works

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1436]
1| The idea behind these two rollbacks is to make sure that everyone gets a his own LUW:
https://github.com/abap2UI5/abap2UI5/blob/1fba55457c6af0a7f38e425dad9d0bc72ebb1453/src/01/02/z2ui5_cl_core_http_post.clas.abap#L137-L139

abap2UI5 needs to save the actual context and does a commit here:
https://github.com/abap2UI5/abap2UI5/blob/main/src/01/01/z2ui5_cl_core_draft_srv.clas.abap#L79

if someone would do a create/modify etc. without doing a commit the abap2UI5 framework would accidentally save it to the database if i don't do the rollback work in L139.

So basically i just try to avoid side effects between abap2UI5 and the app implementation with these rollbacks. 

Is my understanding here right / does this make sense from the perspective of an app implementation?

2| As far as i remember OData Handlers always do a commit in the end automatically, not exact sure how a pure HTTP handler behaves, but maybe the commit in L79 is not needed because the handler will do a commit in the end anyway?

3| Sticky Situation:
what is the use case exactly @christianguenter2 @mzinnoecker? Do you want to have one LUW between multiple roundtrips? Then i think i need to create some extra logic for the commit of the context in L79 (which is not needed in a sticky situation, we can just keep it until the next reqeuest).

As always, open for changes, i am sure i did not take every use case into account.

**Comment by christianguenter2** [comment]
Use case would be pessimistic locking. Keeping LUW/locks between multiple roundtrips.

**Comment by christianguenter2** [comment]
> abap2UI5 needs to save the actual context and does a commit here:
this could also be solved with secondary db connection `R/3*SAP_2TH_CONNECT_APPL_LOG`, similar to BAL.

**Comment by oblomov-dev** [comment]
yes good idea, i created an extra issue for this and we can focus here on the rollbacks https://github.com/abap2UI5/abap2UI5/issues/1438

added now some logic with https://github.com/abap2UI5/abap2UI5/pull/1437
in sticky mode the rollbacks and commits are not used anymore. Means as far as i see it, it should theoretically keeping locks & LUW. You can give it a try and If possible just share a small sample with your use case similar to sample 137.

**Comment by christianguenter2** [comment]
I created a sample to test locking and rollback. AFAIS it works as expected.
https://github.com/abap2UI5/abap2UI5-samples/pull/373

**Comment by oblomov-dev** [comment]
thank you for the PR! merged https://github.com/abap2UI5/abap2UI5-samples/pull/374

works on my side! i will use this sample in the future when i refactor to make sure that the lock functionality still works as expected. and you can just extend the sample if you need further functionality or reproduce problems there if you run into errors.

no cloud ready is no problem, as long as it runs on ABAP Dev 2022, just need it for functional tests.

maybe interesting for you, i steampunkifikated your snippet by copying the metainfo from eclipse and gave it to chat gpt:
<img width="600" alt="Pasted Graphic 86" src="https://github.com/user-attachments/assets/7a23cd6c-25b1-4d4f-ab8b-810f3bfe55ff">
then:
<img width="524" alt="Safari 2024-09-18 15 37 20" src="https://github.com/user-attachments/assets/895fc51e-b4e2-4558-8add-9ee8e74c3002">
<img width="564" alt="Safari 2024-09-18 15 37 24" src="https://github.com/user-attachments/assets/8f4f9a71-5b8b-444d-b960-d67f0e8dfbc2">
et voila:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_135.clas.locals_imp.abap#L4
no need for manual work ;) and now the samples can still be imported to abap cloud (although your sample does not work)

**Comment by christianguenter2** [comment]
Nice, yeah AI is taking our jobs ;-)

It's seems that both sticky samples point the same app? I assume accidentally?
https://github.com/abap2UI5/abap2UI5-samples/blob/83ec66100c4f54b185cea193095f8a8e42e5f784/src/z2ui5_cl_demo_app_000.clas.abap#L256-L270

Btw. what happened to this sample? I assume the tile can be removed?
https://github.com/abap2UI5/abap2UI5-samples/blob/83ec66100c4f54b185cea193095f8a8e42e5f784/src/z2ui5_cl_demo_app_000.clas.abap#L1961-L1967

**Comment by oblomov-dev** [comment]
ah yes fixed with https://github.com/abap2UI5/abap2UI5-samples/pull/375

and the messaging is now here:
https://github.com/abap2UI5-addons/custom-controls
commented the samples out, they are also part of the custom control repo now.

**Comment by oblomov-dev** [comment]
close this, everything else continue here https://github.com/abap2UI5/abap2UI5/issues/1327
