### ISSUE TITLE
New Handler - Breaking Changes

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1447]
All logic now integrated into the abap2UI5 handler.

use with 
```abap

   METHOD if_http_extension~handle_request.

    z2ui5_cl_http_handler=>factory( server )->main( ).

  ENDMETHOD.

```

or in cloud:
```abap

    z2ui5_cl_http_handler=>factory_cloud( eq = request res = response )->main(  ).

```

Give it a try and Feeback / Bugs etc. welcome.

**Comment by mzinnoecker** [comment]
Hey, tested a few of our own and a few sample apps. Works for me, good work!

**Comment by christianguenter2** [comment]
Is there something I need to change in FLP tile config? All my previously working apps are now calling the abap2UI5 start page?

**Comment by oblomov-dev** [comment]
@christianguenter2 mhh i think the new handler logic is completely independent from the tile config. but maybe the change from sunday with the new index.html are the root cause. i also needed to updated the launchpad connector. will check this again.

**Comment by oblomov-dev** [comment]
this error is fine, its because this route leads to nothing:
https://github.com/abap2UI5/abap2UI5/blob/main/src/01/02/z2ui5_cl_core_ui5_app.clas.abap#L783
(we can adjust it another time when we integrate proper routing)

the launchpad routing problem is the following, i missed to bring this lines to the new connector:
https://github.com/abap2UI5-connectors/fiori-launchpad-connector-onpremise/blob/297f18263831aeb19b2e22373745b65bc4a21b9c/src/02/zabap2ui5.wapa.controller_-view1.controller.js#L12-L23

added it now here:
https://github.com/abap2UI5-connectors/fiori-launchpad-connector-onpremise/blob/main/src/02/zabap2ui5.wapa.controller_-app.controller.js#L11-L17

so i think it should work now, or we are close. you can give it a try. you just need to bring somehow the start parameters to the variable: sap.z2ui5.startupParameters 
then it should work again.

unfortunately i have no system with customized launchpad at hand, so its difficult for me to check, but i will customize one if it does not work out.

**Comment by christianguenter2** [comment]
Thx a lot. Made a small fix and it's working for me again.

**Comment by oblomov-dev** [comment]
nice, thanks for beta testing and the fix ;)

**Comment by francisco-milan** [comment]
Apologies for jumping into a closed issue. I just wanted to mention that Ctrl + F12 is not working for me. I'm not sure if this is related to the recent changes discussed here. If not, I'd be happy to open a new issue on GitHub for documentation and further follow-up.

**Comment by oblomov-dev** [comment]
thanks for the info, can reproduce it on my machine, will check that

**Comment by oblomov-dev** [comment]
fixed with https://github.com/abap2UI5/abap2UI5/pull/1458

**Comment by francisco-milan** [comment]
Fantastic, thanks a lot!
