### ISSUE TITLE
Syntax error when creating http handler

### ISSUE THREAD

**Issue by chritcal** [abap2UI5/abap2UI5#1454]
HI,

I installied abap2UI5 via ABAPGIT without problems.
When creating the http handler class, I get the following syntax error:
![image](https://github.com/user-attachments/assets/3ec2a002-de98-4e7d-a18c-f8f21e041081)

My release is:
![image](https://github.com/user-attachments/assets/0d9a1b59-37a4-467c-b75e-3aa60a9eee1f)

I copy pasted the code, so it should be ok.

cheers, Chris

**Comment by oblomov-dev** [comment]
yes the API has changed, try:
```abap
   METHOD if_http_extension~handle_request.

    z2ui5_cl_http_handler=>factory( server )->main( ).

  ENDMETHOD.
```
https://github.com/abap2UI5/abap2UI5/issues/1447

**Comment by chritcal** [comment]
Thanks a bunch, it works now :-)
Maybe adapt the installation instructions?

Thanks & cheers, Chris

**Comment by oblomov-dev** [comment]
yes i thought i did ;) which one did you use?

**Comment by chritcal** [comment]
This one:

![image](https://github.com/user-attachments/assets/73b29abb-89b0-4e78-b343-abd50be69652)

**Comment by oblomov-dev** [comment]
thanks fixed!
