### ISSUE TITLE
CTRL+F12 doesn't work with FLP connector

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1461]
Today I noticed that the CTRL+12 debug tool doesn't work when the App is integrated in FLP.
If I'm not mistaken this worked a while ago.

**Comment by oblomov-dev** [comment]
Yes thanks for the hint, refactoring ui5 frontend at the moment, it's coming back in a few days

**Comment by oblomov-dev** [comment]
should work now with https://github.com/abap2UI5-connectors/fiori-launchpad-connector-onpremise/pull/22

**Comment by christianguenter2** [comment]
Works again 👍 
Btw. nice new design.
![image](https://github.com/user-attachments/assets/ea50b01d-3557-457b-9985-4f6cfbcf8920)

**Comment by oblomov-dev** [comment]
yes cleaned it up a bit and put the debugger in extra files xml+js, i think we can easily extend it now further if we need to check more things at the frontend.
