### ISSUE TITLE
Not exposing all apps at once

### ISSUE THREAD

**Issue by whothefluff** [abap2UI5/abap2UI5#1510]
- First a bit context:

As things stand, after creating a service in the ICF and assigning to it the handler instance created with _z2ui5_cl_http_handler=>factory_, the _main_ method displays this screen at first (I assume so you can look for all classes implementing _z2ui5_if_app_)
![image](https://github.com/user-attachments/assets/be6f25bb-2703-4ffd-b927-8a831e831806)

But you can access any app by changing the parameter _app_start_ in the URL
![image](https://github.com/user-attachments/assets/86d8746b-9ea7-434e-901c-91f87d2398d6)

For example, if I change it to _Z2UI5_SQL_CL_APP_01_ and press enter I successfully open the app
![image](https://github.com/user-attachments/assets/d5b4bed8-89e1-4aa2-b946-e9e605fa7689)

- And then my question/proposal:

If there isn't a way already, I think it would be a good idea to be able to restrict published services to certain apps only. The goal would be to expose only specific apps for each service node. So that when you open an app you see the URL without parameters like so
![image](https://github.com/user-attachments/assets/ebe43095-9ca4-4b34-8a9d-ec88e2f75ead)

And (more importantly) if someone tries to access an app that has not been defined as part of that ICF node, they get an error:
![image](https://github.com/user-attachments/assets/cce543b1-57f0-46a4-a880-832fe2d15591)

Also, if there is in fact a way, I'd appreciate a link to its documentation because I couldn't find it on my own.

**Comment by whothefluff** [comment]
For reference, in my trial system I've created a subclass of _z2ui5_cl_core_http_post_ and modified _z2ui5_cl_http_handler_ to allow me to inject instances of _z2ui5_cl_core_http_post_. Now I can easily control how the POST method works without changing much from the original code.

ICF handler class
```abap
class zcl_a2ui5_sql_con_http_handler definition
                                     public
                                     create public.

  public section.

    interfaces: if_http_extension.

  protected section.

endclass.
class zcl_a2ui5_sql_con_http_handler implementation.

  method if_http_extension~handle_request.

    z2ui5_cl_http_handler=>factory( server )->main( i_post_handler = new zcl_a2ui5_custom_post_handler( `Z2UI5_SQL_CL_APP_01` ) ).

  endmethod.

endclass.
```

Modification of _z2ui5_cl_http_handler->main_
```abap
  METHOD main.

    ms_config = i_config.
    set_request( ).

    CASE ms_req-method.
      WHEN `GET`.
        http_get( ).
      WHEN `POST`.
        http_post( i_post_handler ).
      WHEN `HEAD`.
        mo_server->set_session_stateful( 0 ).
        RETURN.
    ENDCASE.

    set_response( ).
    session_handling( ).

  ENDMETHOD.
```


Modification of _z2ui5_cl_http_handler->http_post_
```abap
  METHOD http_post.

    IF so_sticky_handler IS NOT BOUND.
      DATA(lo_post) = COND #( WHEN i_handler IS INITIAL
                              THEN NEW z2ui5_cl_core_http_post( )
                              ELSE COND #( WHEN i_handler IS BOUND
                                           THEN i_handler
                                           ELSE THROW z2ui5_cx_abap_api( 'CUSTOM_POST_HANDLER_NOT_CORRECTLY_INITIALIZED' ) ) ).
    ELSE.
      lo_post = so_sticky_handler.
    ENDIF.

    lo_post->mv_request_json = ms_req-body.

    ms_res = lo_post->main( ).

    TRY.
        IF lo_post IS BOUND.
          DATA(li_app) = CAST z2ui5_if_app( lo_post->mo_action->mo_app->mo_app ).
          IF li_app->check_sticky = abap_true.
            so_sticky_handler = lo_post.
          ELSE.
            CLEAR so_sticky_handler.
          ENDIF.
        ENDIF.
      CATCH cx_root.
    ENDTRY.

  ENDMETHOD.
```

```abap
class zcl_a2ui5_custom_post_handler definition
                                    public
                                    create public
                                    inheriting from z2ui5_cl_core_http_post.

  public section.

    methods constructor
              importing
                i_app_name type string.

  protected section.

    methods main_begin redefinition.

    data an_app_name type string.

endclass.
class zcl_a2ui5_custom_post_handler implementation.

  method constructor.

    super->constructor( ).

    me->an_app_name = i_app_name.

  endmethod.
  method main_begin.

    try.

      me->ms_request = new z2ui5_cl_core_json_srv( )->request_json_to_abap( mv_request_json ).

      if me->ms_request-s_front-id is not initial.

        me->mo_action = me->mo_action->factory_by_frontend( ).

      elseif me->ms_request-s_front-id is initial
             and me->ms_request-s_control-app_start is initial.

        me->ms_request-s_control-app_start = me->an_app_name.

        new z2ui5_cl_core_draft_srv( )->cleanup( ).

        me->mo_action = me->mo_action->factory_first_start( ).

      elseif me->ms_request-s_control-app_start is not initial.

        raise exception type z2ui5_cx_abap_api.

      endif.

    catch cx_root into data(e).

        assert e->get_text( ) = 1.

    endtry.

  endmethod.

endclass.
```

Nonetheless, if something like that is deemed necessary after all, I'd say it's best to define the public components of _z2ui5_cl_core_http_post_ in an interface since class hierarchies can be problematic.

**Comment by oblomov-dev** [comment]
Hi @whothefluff,

thank you for the PR and starting this topic. There hasn't been any documentation on it so far. But I can now plan to add some documentation based on this conversation, so its good to talk about it.

Authorization is a complex topic, and different companies often approach it in their own unique ways. My goal with abap2UI5 has been to keep the framework as simple and easy to install as possible, therefore leaving more complex customization, like authorization, up to the developers using it.

I think we can address this topic on two levels:

**1. Service Level**

abap2UI5 doesn’t include its own HTTP handler — you define that yourself. One straightforward, programmatic approach would be to check for a specific app within the handler itself:
```abap
CLASS z2ui5_cl_launchpad_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_http_extension.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS z2ui5_cl_launchpad_handler IMPLEMENTATION.

  METHOD if_http_extension~handle_request.

    DATA(lv_app) = server->request->get_header_field( `APP_START` ).
    IF lv_app <> `MY_APP`.
      RETURN.
    ENDIF.

    z2ui5_cl_http_handler=>run( server ).

  ENDMETHOD.

ENDCLASS.
```
This allows you to control access to each individual app. This is similar to how things work in standard UI5/Fiori development, where each app has its own icf node and handler.

Alternatively, you could manage access via authorization objects, something like this:
```abap
CLASS z2ui5_cl_launchpad_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_http_extension.

ENDCLASS.

CLASS z2ui5_cl_launchpad_handler IMPLEMENTATION.

  METHOD if_http_extension~handle_request.

    DATA(lv_app) = server->request->get_header_field( `APP_START` ).

    "authority check
    AUTHORITY-CHECK OBJECT auth_obj [for USER user]
                            ID app lv_app
                            id id2 {field val2}|DUMMY]
    [id id10 {field val10}|DUMMY].

    IF sy-subrc <> 0.
      RETURN.
    ENDIF.

    z2ui5_cl_http_handler=>run( server ).

  ENDMETHOD.

ENDCLASS.
```
However, be mindful that no one should be able to bypass your checks, for example, by calling sample app 000 from the sample directly or via navigation you can also change the app on app level. 

Therefore and to avoid creating many ICF nodes, there is also the option to check on app level. 

**2. App Level Authorization**
For example something like this:
```abap
CLASS z2ui5_cl_demo_app_001 DEFINITION PUBLIC.

  PUBLIC SECTION.
    INTERFACES z2ui5_if_app.

ENDCLASS.

CLASS z2ui5_cl_demo_app_001 IMPLEMENTATION.

  METHOD z2ui5_if_app~main.

    "authority check
   AUTHORITY-CHECK OBJECT auth_obj [for USER user]
                            ID app z2ui5_cl_demo_app_001
                            id id2 {field val2}|DUMMY]
    [id id10 {field val10}|DUMMY].
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.

  ENDMETHOD.

ENDCLASS.
```

This is more like in class ABAP development and SAP GUI where authorization checks are done on program or transaction level.

Personally, I might lean towards the second approach as it’s more flexible, but I’m open to other ideas. What do you think? Do you see any other possible solutions?

Concerning the second comment:
I am not sure if i get the point here. In the end abap2UI5 is Z-Code. so you install the code and "own" it and you can just use it as it is or adjust it. So there is no need to make any "injections", just go into the classes directly and make your changes. For this reason all classes can also be inherited, you have complete freedom. But of course in the end you are the developer and have to take the responsibility for the code you transport into production. What situation do you have in mind, am i missing something here? We can also try to make the code more private if there is the need for.

Best regards and thanks for your input.

**Comment by whothefluff** [comment]
Fair enough, I guess I was so focused on using the abap2UI5 API that I didn't consider reading it directly from the HTTP header independently from the library classes lol

As for user authorizations, I'd say the best option is indeed the AUTHORITY-CHECK statement. It mimics the behavior of assigning an authorization object to a transaction code, which is pretty standard for SAPGUI apps

You can close the issue if you believe there isn't any further discussion to be had about the topic. All clear on my end

**Comment by oblomov-dev** [comment]
Nice, good to hear that it works for you. I will add this information to the documentation, i guess a lot of people have this questions in mind, so thanks for asking.
