### ISSUE TITLE
syntax errors in 752 SP04

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1523]
![image](https://github.com/user-attachments/assets/eb334a0f-c7a4-458d-aa79-11552eb58e5d)

**Comment by oblomov-dev** [comment]
ah can't see it on ABAP Dev Edition 2022, hope it is fixed now with: https://github.com/abap2UI5/abap2UI5/pull/1524

**Comment by christianguenter2** [comment]
Thx.
