### ISSUE TITLE
Play sound after error, success message

### ISSUE THREAD

**Issue by rafeodev** [abap2UI5/abap2UI5#1548]
Hi,

This is an awesome project. Small question,how to play a beep sound after raising an error ? The idea would be to get two beep sound. One for success and another one for error, hence while developing application with barcode scanner, it will possible to notify user whether scanning failed or not (in case for example the ean code does not exist ). With thanks and regards, Mehdi

**Comment by choper725** [comment]
you can easily try integrate a js library such as soundJs or any other for your needs

**Comment by rafeodev** [comment]
> you can easily try integrate a js library such as soundJs or any other for your needs

Is there any sample class I could use as a template ?

**Comment by choper725** [comment]
look here
https://github.com/abap2UI5-addons/js-libraries

this repo is for external js projects

**Comment by rob786541** [comment]
I seem to have a different perspective on what "easy" means! 😄 If the sound file is already available on the device and I simply want to play it, I would typically expect to achieve this with something straightforward like:
`var audio = new Audio("error.mp3");
audio.play();`
Do I really need an entire library just for that?

**Comment by rafeodev** [comment]
> I seem to have a different perspective on what "easy" means! 😄 If the sound file is already available on the device and I simply want to play it, I would typically expect to achieve this with something straightforward like:
> 
> `var audio = new Audio("error.mp3");
> 
> audio.play();`
> 
> Do I really need an entire library just for that?

I agree, I was also expecting something similar. Is there a simple way to achieve this ?

**Comment by choper725** [comment]
yes you can do that, check the repo i sent above, ill try to edit this with a relevant program for your need

**Comment by rafeodev** [comment]
> yes you can do that, check the repo i sent above, ill try to edit this with a relevant program for your need

Thanks a lot. I will wait for your program :-). Playing error/success sound for any scanning application is a "common" requirement that could be added to the abap2ui5 package.

**Comment by rob786541** [comment]
i uploaded a wave file with SE80 and activated in SICF the service /default_host/sap/public/bc/abap/mime_demo
![grafik](https://github.com/user-attachments/assets/90ff9ed0-273f-416d-80ad-c2c182293e49)

with this demo i am able to play the uploaded sound, if an error occurs
```ABAP
CLASS zmsz_cl_app_sound2 DEFINITION
  PUBLIC
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES z2ui5_if_app.

    DATA mv_initialized TYPE abap_bool.
    DATA mv_url         TYPE string.

    METHODS on_event.
    METHODS view_display.

    DATA company_code TYPE string.

  PROTECTED SECTION.
    DATA client TYPE REF TO z2ui5_if_client.

  PRIVATE SECTION.
ENDCLASS.


CLASS zmsz_cl_app_sound2 IMPLEMENTATION.
  METHOD on_event.
    CASE client->get( )-event.

      WHEN 'CUSTOM_JS_FROM_EB'.
        IF company_code IS INITIAL.
          client->follow_up_action( val = `playSound()` ).
          client->message_box_display( type = 'error' text = 'Should not be empty' ).
        ELSE.
          CLEAR company_code.
        ENDIF.
        client->view_model_update( ).

      WHEN 'BACK'.
        client->nav_app_leave( ).
        RETURN.

    ENDCASE.
  ENDMETHOD.

  METHOD view_display.
    DATA(view) = z2ui5_cl_xml_view=>factory( ).
    view->_generic( name = `script`
                    ns   = `html` )->_cc_plain_xml(
                        |function playSound() \{ new Audio("/SAP/PUBLIC/BC/ABAP/mime_demo/bam.wav").play(); \}| ).

    DATA(page) = view->shell( )->page(
                     title          = `Client->FOLLOW_UP_ACTION use cases`
                     class          = `sapUiContentPadding`
                     navbuttonpress = client->_event( 'BACK' )
                     shownavbutton  = xsdbool( client->get( )-s_draft-id_prev_app_stack IS NOT INITIAL ) ).
    page = page->vbox( ).
    page->input( id          = `inputApp`
                 value       = client->_bind_edit( company_code )
                 type        = `Number`
                 placeholder = `Company Code`
                 submit      = client->_event( 'CUSTOM_JS_FROM_EB' ) ).
    page->get_parent( )->hbox( class = `sapUiSmallMargin` ).
    page->button( text  = `call custom JS from EB`
                  press = client->_event( 'CUSTOM_JS_FROM_EB' ) ).

    client->view_display( view->stringify( ) ).
  ENDMETHOD.

  METHOD z2ui5_if_app~main.
    me->client = client.

    IF mv_initialized = abap_false.
      mv_initialized = abap_true.
      view_display( ).
    ENDIF.

    on_event( ).
  ENDMETHOD.
ENDCLASS.
```

**Comment by rafeodev** [comment]
Thanks a lot guys !!!

**Comment by rafeodev** [comment]
Tested in my system, it Works perfectly

**Comment by oblomov-dev** [comment]
Nice! Thanks to all of you for your work! 👍

I’ve added the information and snippet to the documentation so others can easily find it in the future if they encounter the same issue: https://abap2ui5.github.io/docs/development/barcodes.html

**Comment by christianguenter2** [comment]
Indeed very nice and highly appreciated. Prepared a little sample app shipped with success and error sounds.

**Comment by rob786541** [comment]
Thank you very much. I'm glad that you are integrating the contribution into the repository to make it easier for future developers. 
A great project by the way. i hope to be able to participate in the future as well.

**Comment by oblomov-dev** [comment]
@christianguenter2 not sure if the mime artifact will cause any problems in abap cloud when installing the sample repository with adt-abapgit, will check it another time (maybe it just gets ignored), but its definitely good to have it :)

i think barcodes, scanning etc is one of the evergreen topics, made a little linkedIn tweet out of it:
https://www.linkedin.com/posts/abap2ui5_abap2ui5-abap-ui5-activity-7264554408946946050-QR-d?utm_source=share&utm_medium=member_desktop

thanks again to all of you, i will close this one, just reopen or create a new one if there are further questions.
