### ISSUE TITLE
Background color for spa.m.table cell

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#1551]
Hi,

I like to change the standard background color of an sap.m.table cell.
I created already a custom CSS.
![image](https://github.com/user-attachments/assets/865c83d1-336b-4b40-ab2f-721b3b65a7a9)

Which I assigned via "CLASS" parameter to the cell text.
![image](https://github.com/user-attachments/assets/92a1a26c-8f81-44d0-b40f-ba404bb083cf)

But this unfortunately colors the text background only.
![image](https://github.com/user-attachments/assets/e35ce26a-48d2-4a33-8dfe-e1dc1302157b)

Has someone an idea how to set the background to the "parent" of table cell?

Thanks a lot.

Kind regards
Axel

**Comment by christianguenter2** [comment]
You can try something like
```CSS
  td:has(span.customBgColor) { background-color: red }
```

**Comment by axelmohnen** [comment]
Thanks a lot for the fast answer!

This works to color the background for the whole column.
I like to color each cells separately.

I tried to extend your idea a bit, by adding a variable in the CSS class property of the text control.
Unfortunately it didn't work.
 
View (XML)
`<mvc:View xmlns="sap.m" xmlns:core="sap.ui.core" xmlns:f="sap.f" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:mvc="sap.ui.core.mvc" xmlns:table="sap.ui.table" xmlns:unified="sap.ui.unified" displayBlock="true" height="100%">
  <Page class="sapUiContentPadding" id="page_main" navButtonPress=".eB(['BACK'])" showNavButton="false" title="abap2UI5 - sap.ui.table.Table Features">
    <html:style>td:has(.customBgColor) { background-color: red }
td:has(.customBgColor2) { background-color: blue }
td:has(.customBgColor3) { background-color: green }
td:has(.customBgColor4) { background-color: yellow }</html:style>
    <headerContent>
      <Link target="_blank" text="Source_Code"/>
    </headerContent>
    <f:DynamicPage headerExpanded="true" headerPinned="true">
      <f:title>
        <f:DynamicPageTitle>
          <f:heading>
            <HBox>
              <Title text="Search Field"/>
            </HBox>
          </f:heading>
          <f:expandedContent/>
          <f:snappedContent/>
        </f:DynamicPageTitle>
      </f:title>
      <f:header>
        <f:DynamicPageHeader pinnable="true">
          <FlexBox alignItems="Start" justifyContent="SpaceBetween">
            <FlexBox alignItems="Start">
              <VBox>
                <Text text="Search"/>
                <SearchField change=".eB(['BUTTON_SEARCH'])" id="SEARCH" search=".eB(['BUTTON_SEARCH'])" value="{/XX/MV_SEARCH_VALUE}" width="17.5rem"/>
              </VBox>
            </FlexBox>
            <HBox justifyContent="End">
              <Button press=".eB(['BUTTON_START'])" text="Go" type="Emphasized"/>
            </HBox>
          </FlexBox>
        </f:DynamicPageHeader>
      </f:header>
      <f:content>
        <Table items="{/MT_TABLE}">
          <columns>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
            <Column width="5rem"/>
          </columns>
          <items>
            <ColumnListItem>
              <cells>
                <Text class="{COL01_CLASS}" text="{COL01}"/>
                <Text text="{COL02}"/>
                <Text text="{COL03}"/>
                <Text text="{COL04}"/>
                <Text text="{COL05}"/>
                <Text text="{COL06}"/>
                <Text text="{COL07}"/>
                <Text text="{COL08}"/>
                <Text text="{COL09}"/>
                <Text text="{COL10}"/>
                <Text text="{COL11}"/>
                <Text text="{COL12}"/>
                <Text text="{COL13}"/>
                <Text text="{COL14}"/>
                <Text text="{COL15}"/>
                <Text text="{COL16}"/>
                <Text text="{COL17}"/>
                <Text text="{COL18}"/>
                <Text text="{COL19}"/>
                <Text text="{COL20}"/>
                <Text text="{COL21}"/>
              </cells>
            </ColumnListItem>
          </items>
        </Table>
      </f:content>
    </f:DynamicPage>
  </Page>`

Model (JSON)
`{
   "MT_TABLE": [
      {
         "COL01": "01",
         "COL01_CLASS": "customBgColor",
         "COL02": "02",
         "COL03": "",
         "COL04": "",
         "COL05": "",
         "COL06": "",
         "COL07": "",
         "COL08": "",
         "COL09": "",
         "COL10": "",
         "COL11": "",
         "COL12": "",
         "COL13": "",
         "COL14": "",
         "COL15": "",
         "COL16": "",
         "COL17": "",
         "COL18": "",
         "COL19": "",
         "COL20": "",
         "COL21": ""
      },
      {
         "COL01": "01",
         "COL01_CLASS": "customBgColor2",
         "COL02": "02",
         "COL03": "",
         "COL04": "",
         "COL05": "",
         "COL06": "",
         "COL07": "",
         "COL08": "",
         "COL09": "",
         "COL10": "",
         "COL11": "",
         "COL12": "",
         "COL13": "",
         "COL14": "",
         "COL15": "",
         "COL16": "",
         "COL17": "",
         "COL18": "",
         "COL19": "",
         "COL20": "",
         "COL21": ""
      },
      {
         "COL01": "01",
         "COL01_CLASS": "customBgColor3",
         "COL02": "02",
         "COL03": "",
         "COL04": "",
         "COL05": "",
         "COL06": "",
         "COL07": "",
         "COL08": "",
         "COL09": "",
         "COL10": "",
         "COL11": "",
         "COL12": "",
         "COL13": "",
         "COL14": "",
         "COL15": "",
         "COL16": "",
         "COL17": "",
         "COL18": "",
         "COL19": "",
         "COL20": "",
         "COL21": ""
      },
      {
         "COL01": "01",
         "COL01_CLASS": "customBgColor4",
         "COL02": "02",
         "COL03": "",
         "COL04": "",
         "COL05": "",
         "COL06": "",
         "COL07": "",
         "COL08": "",
         "COL09": "",
         "COL10": "",
         "COL11": "",
         "COL12": "",
         "COL13": "",
         "COL14": "",
         "COL15": "",
         "COL16": "",
         "COL17": "",
         "COL18": "",
         "COL19": "",
         "COL20": "",
         "COL21": ""
      }
   ],
   "XX": {
      "MV_SEARCH_VALUE": ""
   }`
