### ISSUE TITLE
Some Adjustments for UI5 V2 Compatibility

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#1580]
Made two changes for UI5 2.x compatibility: https://github.com/abap2UI5/abap2UI5/pull/1578

(1) sap.gantt.misc.Format.abapTimestampToDate
https://github.com/abap2UI5/abap2UI5/blob/main/app/webapp/controller/App.controller.js#L822
couldn't find any sample where it is used and what it is excactly doing, commented it therefore out now because it is not compatible with openUI5 and UI5 2.x 
@choper725 maybe you used it? let me know if its still important, maybe we can replace it with a plain JS converter without UI5 dependencies.

(2) CrossAppNavigation
https://github.com/abap2UI5/abap2UI5/blob/main/app/webapp/controller/View1.controller.js#L251
https://github.com/abap2UI5/abap2UI5/blob/main/app/webapp/controller/View1.controller.js#L264
Replaced the old call with a UI5 2.x compatible sap.ui.require call. everything should work as before, if not just share the error message and i can fix it.

The good news:
Additionally to abap checks with abaplint, the frontend artifacts are now checked with the new ui5 linter:
https://github.com/abap2UI5/abap2UI5/actions/runs/12031227951/job/33540289802

After the recent changes, all checks are sucessfull now:
<img width="1904" alt="image" src="https://github.com/user-attachments/assets/c2c4fef4-ae78-45b1-a256-7b84c0ef958b">

**Comment by choper725** [comment]
hi ,
as far as i remember some controls require a js date object, hence we did a util converter (vanilla js) to convert abap to js dates.

not sure where the  sap.gantt.misc came from, it was a cuatom namespace that we imported and used those functions with

**Comment by oblomov-dev** [comment]
thanks for the information! yes the util function itself is useful, but i can't find where we used  the specific sap.gantt.misc, the gantt samples also work without it... mhh but anyways. if problems will came up in the future, this issue can be found and then we can reactivate the formatter in an openUI5 ready way.

**Comment by choper725** [comment]
i dont think i used sap.gantt.misc anywhere
