### ISSUE TITLE
Question to Demo z2ui5_cl_demo_app_123: Map Container

### ISSUE THREAD

**Issue by Marchl-Woid** [abap2UI5/abap2UI5#1592]
Hi one question,
maybe somebody has a hint for me.

Demo z2ui5_cl_demo_app_123 as it is works fine. Map shows up. 

I wnat to use this UI Element in an application and I have following effent.

If you make in this demo z2ui5_cl_demo_app_123 following change:

```
   DATA(map) =  page->grid( 'XL3 L3 M6 S12' )->content( 'layout'  )->map_container(  autoadjustheight = abap_true
         )->content( ns = `vk`
             )->container_content(
               title = `Analytic Map`
               icon  = `sap-icon://geographic-bubble-chart`
                 )->content( ns = `vk`
                     )->analytic_map(
                       initialposition = `9.933573;50;0`
                       initialzoom = `6`
                     )  .
```

Packed the Map in a grid layout:
![image](https://github.com/user-attachments/assets/e73567cf-6aa8-4e02-9ccb-c502e4efbc7d)

Then I have the effect:

![image](https://github.com/user-attachments/assets/c2becc00-90b1-451f-a7be-fcb20f24dc74)

Now you can maximize, but don't get the map in the initial view...

But I also don't find a parameter for defining the heigth....

Thanks in advance...

**Comment by Marchl-Woid** [comment]
I Tried around a bit,
this seems to solve the general problem:
```
DATA(map) = page->analytic_map( initialposition = `9.933573;50;0`
                                       initialzoom     = `4`
                                       height = '10cm' ).
```


instead of
```
*    DATA(map) = page->map_container( autoadjustheight = abap_true
*                                           showHome = abap_true
*          )->content( ns = `vk`
*              )->container_content( title = `Analytic Map`
*                                    icon  = `sap-icon://geographic-bubble-chart`
*                  )->content( ns = `vk`
*                      )->analytic_map( initialposition = `9.933573;50;0`
*                                       initialzoom     = `4`
*                                       height = '10cm' ).
```

**Comment by oblomov-dev** [comment]
Hi @Marchl-Woid,

that looks good, yes sometimes its not possible to have certain UI5 controls as childs of other UI5 controls. maybe the map container is not needed in this case.
