### ISSUE TITLE
example OData service not available

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1617]
Many thanks for the latest innovations regarding OData support.

https://abap2ui5.github.io/docs/development/model/odata.html
`As an example, we will use the test OData service /sap/opu/odata/DMO/API_TRAVEL_U_V2/, which is available in most ABAP systems. `
I'd like to try the sample but unfortunately in none of the (on-premises) ABAP systems I have access to the sample OData service exists.

This makes we wonder where does that OData service come from? Maybe I miss the obvious.

**Comment by christianguenter2** [comment]
`Maybe I miss the obvious.` seems I was right. It's from here.
https://help.sap.com/docs/ABAP_PLATFORM_NEW/fc4c71aa50014fd1b43721701471913d/a9d7c7c140a0408dbc5966c52d156b49.html
https://github.com/SAP-samples/abap-platform-refscen-flight.git

**Comment by oblomov-dev** [comment]
thanks as always for testing and the fix in the docu. yes seems i mixed up the names of the entities.
