### ISSUE TITLE
confusion about switchDefaultModel

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1618]
Isn't it ab bit confusing that we use `switchDefaultModel` as boolean and as string?
https://github.com/abap2UI5/abap2UI5/blob/777c8d5a63620666cf20e1b837b8f38bf84740e1/src/02/z2ui5_if_client.intf.abap#L166
https://github.com/abap2UI5/abap2UI5/blob/777c8d5a63620666cf20e1b837b8f38bf84740e1/src/02/z2ui5_if_client.intf.abap#L36

Maybe we can rename the latter into something like `switchDefaultModelPath`?

**Comment by oblomov-dev** [comment]
mhh there are no strong naming conventions in this project, but now when i look at it one more time...
maybe `switch_default_model_path` is more consistent? all other variables are also named in this way. i also need to adjust the frontend JS at some points. changing it at the moment.

**Comment by christianguenter2** [comment]
yeah `switch_default_model_path` should be the way to go.

**Comment by oblomov-dev** [comment]
names are updated, everything should work
