### ISSUE TITLE
abap2UI5 is broken since last update

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#1627]
Since the latest changes I get this error
![image](https://github.com/user-attachments/assets/38830871-88e4-4be8-be51-16605bb9a0e9)
![image](https://github.com/user-attachments/assets/18e6ce18-d536-4fc4-9c8c-e123fc8bed11)

**Comment by oblomov-dev** [comment]
ok merged, some fixes and renamed. now everything should work again with new naming etc.

**Comment by christianguenter2** [comment]
work again. closing.
