### ISSUE TITLE
New FLP frontend - Fullscreen mode

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#1648]
Hi,
I just installed the latest version of the FLP frontend.
By default, my app wasn't in fullscreen mode. 

I see that in the manifest the property "fullwidth" is missing.
![image](https://github.com/user-attachments/assets/c26c6ad8-fef8-42e8-89f8-b67755787084)

When I set this property to "true" the app will be displayed in fullscreen mode.
Question:
I saw that the frontend integration has been changed a lot.
This there an other/preferred way to switch to fullscreen mode (e.g. via config)?

Thanks,
Axel

**Comment by oblomov-dev** [comment]
hi @axelmohnen,

yes I took the manifest as it is regenerated with the Fiori app generator. There the fullwidth is not set. so I think it is right to take it like this as the default, but feel free to change it on your system if you need the value set as true.

another idea:
we are able to set the lauchpad title dynamically via:
`client->set_lp_title`

Maybe a feature like this also helps you?

Found here:
https://stackoverflow.com/questions/55832369/how-to-disable-or-enable-letterboxing-and-adjust-ui5-for-the-widescreen/56137602#56137602
Maybe we can change the value with:
`AppConfiguration.setApplicationFullWidth(true|false); //*`

But never tried if this approach works. Feel free to give it a try and check if you can change the fullwidth parameter via an ui5 function. I will also check it in the upcoming days. Maybe then we can create a little client function like:
client->set_lp_fullwidth( abap_true )

**Comment by oblomov-dev** [comment]
added, this function now, on my side it works:
<img width="1920" alt="Google Chrome 2024-12-14 17 04 12" src="https://github.com/user-attachments/assets/bbae598c-0cb2-4568-bbbf-f3a04b0371d4" />

Just do:
<img width="703" alt="image" src="https://github.com/user-attachments/assets/d0cf9bb7-cccc-4789-a5ea-9e6a643e0cf0" />

**Comment by axelmohnen** [comment]
Hi @oblomov-dev ,
yes it works for me as well.
Thanks a lot!
