### ISSUE TITLE
Docs - Quickstart: part 3 - Create HTTP Service

### ISSUE THREAD

**Issue by nomssi** [abap2UI5/abap2UI5#1659]
I am following the steps described: 
-> There is no mention of transaction SICF needed to create a service / the screenshot displayed.
![image](https://github.com/user-attachments/assets/dd699c28-1b4e-4751-a049-0f01962a70ae)

br 
Jacques

**Comment by oblomov-dev** [comment]
Hi @nomssi,

thank you for the hint, its a good idea to add that!

Used your screenshot now and updated the documentation:
https://abap2ui5.github.io/docs/get_started/quickstart.html#_3-create-http-service

Feel also free to contribute directly to the docs, if you miss certain information. Everything is just WIP :)

Best regards.
