### ISSUE TITLE
how to troubleshoot?

### ISSUE THREAD

**Issue by nomssi** [abap2UI5/abap2UI5#1686]
After the latest update, I am unable to access abap2UI5 apps
![image](https://github.com/user-attachments/assets/421c26ff-a7d5-4ebe-868d-12be2625eb18)
What is the simplest way to identify the error?

best regards,
Jacques

**Comment by oblomov-dev** [comment]
Hi @nomssi,

i collect typical troubleshooting here:
https://abap2ui5.github.io/docs/configuration/troubleshooting.html

but you have a interesting error! seems that after first loading the html and javascript the second http request does not find the backend. it goes to /sap/bc/z2ui5 but your http endpoint is /zabap2ui5. mhh...

tested it on my machine, all good:
<img width="800" alt="image" src="https://github.com/user-attachments/assets/2a331b87-351d-46a2-9914-8aa58633ebb7" />

can you open the sources tab in the debugger tools and check which files are loaded? Maybe try to put the http handler under /sap/bc/
sometimes i have problems when it is defined directly under default host.

**Comment by nomssi** [comment]
![image](https://github.com/user-attachments/assets/933ff8b1-4cd3-4198-a3ae-952b151f6804)

After activation under /sap/bc/
![image](https://github.com/user-attachments/assets/bae6bb22-e1f8-4269-9915-4f8ef25fb120)

**Comment by oblomov-dev** [comment]
thanks for the screenshots, was able to reproduce it now. there was a little bug with latest changes, fixed now with:
https://github.com/abap2UI5/abap2UI5/pull/1688/files

you can try again.

**Comment by nomssi** [comment]
I confirm it nows works for me!
