### ISSUE TITLE
UI Extension - add sap.m.wizard

### ISSUE THREAD

**Issue by kirillorgazm** [abap2UI5/abap2UI5#218]
Hi! Thank you for your hard work on it.
This feature helps alot, even for those who already use UI5 as an instrument, and also for newcomers.

Is it possible to add sap.m.Wizard (with steps) and sap.m.Tree  ? They are not smart controls afaik

**Comment by oblomov-dev** [comment]
yes both controls are just XML with a JSON Model so they can be added. I will make an extra issue for the tree because the data has to be sent in a new format which is actually not part of the abap2UI5 functionality.

https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.Wizard

**Comment by oblomov-dev** [comment]
close this issue, check:
https://github.com/abap2UI5/abap2UI5/issues/219
https://github.com/abap2UI5/abap2UI5/issues/303
https://github.com/abap2UI5/abap2UI5/issues/248
