### ISSUE TITLE
UI Extension - add sap.m.tree

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#219]
documentation: https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.Tree

**Comment by axelmohnen** [comment]
Hi oblomov,
I have the requirement to use the sap.ui.table.TreeTable in the application.
Is this on your Todo list as well?
Many thanks,
Axel

**Comment by oblomov-dev** [comment]
Hi Axel, 

yes it is on my todo list ;) 

At the moment you can use all UI5 Controls which are working with a table model. But the plan is to make it also working with controls which are based on a tree model.

I have some other things to do first so it will not happen in the next days or weeks, but in the next months i hope that i can include it.

Best Regards.

**Comment by axelmohnen** [comment]
Great!
I tried to create a new "Tree table" control by myself.
It seem that the control expects the "treeAnnotationProperties" in case sensitive.
In ABAP the T_TAB gets automatically converted in upper case and the correspnding json model as well.
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/7a9af6da-a189-4539-82a8-228b6ca3889c)

The output look currently looks like this. No hierarchy yet :-(
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/0a048107-e9f0-45b6-9afd-570e9502f4bd)

I will let you know the outcome...

**Comment by axelmohnen** [comment]
Finally it works :-)
The first approach was with oData data source which didn't work.
The second approach is with JSON data source.
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/e2256536-703a-4138-9d61-59186e9633e6)

` METHOD z2ui5_if_app~main.

    IF check_initialized = abap_false.
      check_initialized = abap_true.

      mt_tree = value #( ( object = '1' categories = value #( ( object = '1.1' categories = value #( ( object = '1.1.1')
                                                                                                     ( object = '1.1.2') ) )
                                                                               ( object = '1.2' ) ) )
                         ( object = '2' categories = value #( ( object = '2.1' )
                                                              ( object = '2.2' ) ) )
                         ( object = '3' categories = value #( ( object = '3.1' )
                                                              ( object = '3.2' ) ) ) ).
    ENDIF.

    CASE client->get( )-event.

      WHEN 'BACK'.
        client->nav_app_leave( client->get_app( client->get( )-id_prev_app_stack ) ).
    ENDCASE.

    DATA(page) = z2ui5_cl_xml_view=>factory( )->shell(
        )->page(
            title          = 'abap2UI5 - TreeTable'
            navbuttonpress = client->_event( 'BACK' )
              shownavbutton = abap_true
            )->header_content(
                )->link(
                    text = 'Source_Code'  target = '_blank'
                    href = z2ui5_cl_xml_view=>hlp_get_source_code_url( app = me )
            )->get_parent( ).

    client->_bind_one( mt_tree ).
    DATA(tab) = page->tree_table(
      rows = `{path:'/MT_TREE', parameters: {arrayNames:['CATEGORIES']}}` ).
    tab->tree_columns(
    )->tree_column( label = 'Object'
        )->tree_template(
        )->text( text = '{OBJECT}')->get_parent( )->get_parent(
        )->tree_column( label = 'Column2'
        )->tree_template(
        )->text( text = '{COL2}')->get_parent( )->get_parent(
        )->tree_column( label = 'Column3'
        )->tree_template(
        )->text( text = '{COL3}')->get_parent( )->get_parent(
        )->tree_column( label = 'Column4'
        )->tree_template(
        )->text( text = '{COL4}').

    client->set_next( VALUE #( xml_main = page->get_root(  )->xml_get( ) ) ).

  ENDMETHOD.`

Tree table definition:
` TYPES: BEGIN OF ts_tree_row_base,
             object TYPE stringval,
             col2   TYPE stringval,
             col3   TYPE stringval,
             col4   TYPE stringval,
           END OF ts_tree_row_base.

    TYPES: BEGIN OF ts_tree_level3.
             INCLUDE TYPE ts_tree_row_base.
           TYPES: END OF ts_tree_level3.

    TYPES: tt_tree_level3 TYPE STANDARD TABLE OF ts_tree_level3 WITH KEY object.

    TYPES: BEGIN OF ts_tree_level2.
             INCLUDE TYPE ts_tree_row_base.
             TYPES: categories TYPE tt_tree_level3.
    TYPES: END OF ts_tree_level2.

    TYPES: tt_tree_level2 TYPE STANDARD TABLE OF ts_tree_level2 WITH KEY object.

    TYPES: BEGIN OF ts_tree_level1.
             INCLUDE TYPE ts_tree_row_base.
             TYPES: categories TYPE tt_tree_level2.
    TYPES: END OF ts_tree_level1.

    TYPES: tt_tree_level1 TYPE STANDARD TABLE OF ts_tree_level1 WITH KEY object.

    DATA: mt_tree TYPE tt_tree_level1.`

**Comment by oblomov-dev** [comment]
Wow, great work! 💪

Abap2UI5 is doing a /ui2/cl_json=>parse() with your data and creates automatic the right json model for the UI5 control. Expected we need some extra logic, but even better if it works with your data model out-of-the-box. Nice!

Just if you want, but it would be a great help when you send me your changes via PR. You extended the class z2ui5_cl_xml_view with the new tree controls and some properties. Would be nice if i don't have to do this manually again. So if you want, do the following:
(1) Create a new fork of the abap2UI5 project
(2) Pull this fork in your system 
(3) Extend the class z2ui5_cl_xml_view with your changes
(4) Commit these changes to your fork
(5) Open a PR that i can merge it

Best regards!

**Comment by oblomov-dev** [comment]
@axelmohnen Thank you for your PRs! 

When i find time in the next days, i will make a little twitter tweet about the tree control. Let me know your twitter name or a profile link to which i can refer to (just in case if you want to be named in it, otherwise no problem).

Great work!

**Comment by axelmohnen** [comment]
Hi,
Great idea! 
I don't have a twitter account ;-)
Naming is not needed...
Thanks,
Axel

**Comment by oblomov-dev** [comment]
Tested it on my machine, works fine!

https://twitter.com/abap2UI5/status/1673320288983842820
