### ISSUE TITLE
Extension index.html - Reduce XSS risks

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#223]
Test the following:
[https://htmx.org/docs/#security](https://t.co/BJn6szrljj)
https://content-security-policy.com/

TODO
(1) add an CSP meta tag between line 95-97 of the get_method a config ABAP variable could provide a secure by default standard value like content="default-src 'self' [http://openui5.org](https://t.co/JYj3yi4Nbd) *.openui5.org;" 
(2) make it configurable in the method interface

https://twitter.com/derhess/status/1656987971160096769

**Comment by oblomov-dev** [comment]
New Importing Parameter added (content_security_policy):
<img width="611" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/b784dda9-246e-439c-be4e-75d0b625e67a">

Per default, the following is allowed:
`<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' ui5.sap.com *.ui5.sap.com sdk.openui5.org *.sdk.openui5.org cdn.jsdelivr.net *.cdn.jsdelivr.net"/>`

Check:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
https://content-security-policy.com/

**Comment by choper725** [comment]
what to do with on prem url ?

**Comment by oblomov-dev** [comment]
it should work with the 'self' parameter.
