### ISSUE TITLE
Menu appearance / UI5 question

### ISSUE THREAD

**Issue by nomssi** [abap2UI5/abap2UI5#234]
When I start my app, the menubar sometimes appears as 
![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/3d612e7d-75f5-4929-b56f-f4813ba41a00)

even on a large monitor, with the details
![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/be56deff-c30f-45f0-9f6f-0bbf0c7d5222)

being displayed with I click on ...
After reloading once, I see 
![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/270387f7-ff30-4f9a-845b-ddb821ed4e15)

Do anyone knows how why? Can I can controll this?

My code looks like

    METHOD Z2UI5_ON_RENDER_MAIN.
    "DATA(view) = client->factory_view( 'ABAP_SCHEME' ).

    DATA(page) = z2ui5_cl_xml_view=>factory( )->shell(
              )->page(
                   id = 'id_page'
                   title = 'abapScheme - Workbench'
                   shownavbutton = abap_true
                   navbuttonpress = client->_event( 'BACK' ) ).

    page->header_content(
      )->overflow_toolbar(
        )->button(
            text  = 'Evaluate'
            press = client->_event( 'BUTTON_EVAL' )
            icon = 'sap-icon://begin'
            type    = 'Emphasized'
        )->toolbar_spacer(
        )->button( text = 'S-Expression' press = client->_event( 'BUTTON_SEXP' )
                   icon = 'sap-icon://tree'
        )->button( text = 'Trace' press = client->_event( 'BUTTON_TRACE' )
                    icon = 'sap-icon://step'
        )->button(
             text = 'Previous'
             press = client->_event( 'BUTTON_PREV' )
             icon  = 'sap-icon://navigation-left-arrow'
        )->button(
             text = 'Next'
             press = client->_event( 'BUTTON_NEXT' )
             icon  = 'sap-icon://navigation-right-arrow'
        )->button(
             text = 'Refresh'
             type  = 'Reject'
             press = client->_event( 'BUTTON_RESET' )
             icon  = 'sap-icon://delete'
        )->link( text = 'Help on..' href = 'https://github.com/nomssi/abap_scheme/wiki'
                 " icon  = 'sap-icon://learning-assistant' // 'sap-icon://sys-help'
       )->get_parent( ).

**Comment by oblomov-dev** [comment]
Interesting, i have the same problem but no solution 🤷‍♂️ When i change overflowtoolbar with normal toolbar it is working, but this is just a workaround and i think you choose overflow for a certain reason.

```abap
 page->header_content(
  )->toolbar(
    )->button(
        text  = 'Evaluate'
        press = client->_event( 'BUTTON_EVAL' )
        icon = 'sap-icon://begin'
        type    = 'Emphasized'
    ")->toolbar_spacer(
    )->button( text = 'S-Expression' press = client->_event( 'BUTTON_SEXP' )
               icon = 'sap-icon://tree'
    )->button( text = 'Trace' press = client->_event( 'BUTTON_TRACE' )
                icon = 'sap-icon://step'
    )->button(
         text = 'Previous'
         press = client->_event( 'BUTTON_PREV' )
         icon  = 'sap-icon://navigation-left-arrow'
    )->button(
         text = 'Next'
         press = client->_event( 'BUTTON_NEXT' )
         icon  = 'sap-icon://navigation-right-arrow'
    )->button(
         text = 'Refresh'
         type  = 'Reject'
         press = client->_event( 'BUTTON_RESET' )
         icon  = 'sap-icon://delete'
    )->link( text = 'Help on..' href = 'https://github.com/nomssi/abap_scheme/wiki'
             " icon  = 'sap-icon://learning-assistant' // 'sap-icon://sys-help'
   )->get_parent( ).
```
