### ISSUE TITLE
UI Extension - sap.m.carousel

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#261]
Add the carousel control to the class z2ui5_cl_xml_view

**Comment by oblomov-dev** [comment]
https://github.com/oblomov-dev/abap2UI5/issues/260

**Comment by oblomov-dev** [comment]
@nomssi 
Added the carousel control: https://github.com/oblomov-dev/abap2UI5/pull/275

Demo:
```abap
CLASS z2ui5_cl_app_demo_51 DEFINITION PUBLIC.

  PUBLIC SECTION.

    INTERFACES z2ui5_if_app.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z2ui5_cl_app_demo_51 IMPLEMENTATION.


  METHOD z2ui5_if_app~main.

    DATA(page) = z2ui5_cl_xml_view=>factory( )->shell(
          )->page(  title = 'carousel' ).

    page->carousel(
         )->text( `carousel 01`
         )->text( `carousel 02`
         )->text( `carousel 03`
         )->text( `carousel 04`
    ).

    client->set_next( VALUE #( xml_main = page->get_root( )->xml_get( ) ) ).

  ENDMETHOD.
ENDCLASS.
```
<img width="500" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/ef8c6a90-8f7e-459f-9a2a-e8279d5140a7">

**Comment by nomssi** [comment]
works for me:
![image](https://github.com/abap2UI5/abap2UI5/assets/18452507/7f0c4dce-514b-4062-ad11-3485e64adc5d)
