### ISSUE TITLE
Exception in the Demos 52

### ISSUE THREAD

**Issue by nomssi** [abap2UI5/abap2UI5#282]
With current version, I experience a "500 Internal Error" exception 

for demo Item Popover (class Z2UI5_CL_APP_DEMO_52) when I click on "details"

![image](https://github.com/abap2UI5/abap2UI5/assets/18452507/35a522d5-0eb1-4650-ba52-16aa5a8ef619)

or  for Layout demo (class Z2UI5_CL_APP_DEMO_58) when I click on "save"

![image](https://github.com/abap2UI5/abap2UI5/assets/18452507/41521bfb-91f7-436d-83bc-0fbf5fbe3690)

![image](https://github.com/abap2UI5/abap2UI5/assets/18452507/5065247c-345b-4647-990a-4c65a7415756)

**Comment by oblomov-dev** [comment]
Thank you for the hint! Fixed both bugs.
