### ISSUE TITLE
Contribution - Extend the demo repository or share your code snippets

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#304]
_Every help and PR extending the demo section is welcome!_

Extend the demo sections, with your own demos and apps or share your repositories. Your code snippets are a great help for others.

**Extend the demo section:**
(1) Fork and pull the Demo Repository:
[https://github.com/abap2UI5/abap2UI5-demos](https://github.com/abap2UI5/abap2UI5-demos)
(2) Add your demo and create a PR.

**Extend the link collection:**
(1) Add your app to the following page:
https://github.com/abap2UI5/abap2UI5/blob/main/docs/links.md

**Thank you for your help!**

**Comment by nomssi** [comment]
My current version of an adventure game Axage and abap2ui5 is now under:
https://github.com/nomssi/axage/

**Comment by oblomov-dev** [comment]
Great work! i will extend the demo section with links to other repositories, that it can be found easily.

**Comment by oblomov-dev** [comment]
Created a page to collect examples and code snippets:
https://github.com/abap2UI5/abap2UI5/blob/main/LINKS.md
And linked to it on the start page:
<img width="753" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/63a1e216-3db0-4773-a302-01fa5b235769">
