### ISSUE TITLE
[Info] PRs are always welcome! 🙏

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#306]
This project is open source and developed alongside other projects or during free time. Contributions are greatly appreciated!

A big thank you to the contributors:
@larshp @nomssi @axelmohnen @mbtools @christianguenter2 @sun-tassein @abs-lme @Th0masMa @choper725 @WegnerDan @noso2k1 @abapsheep 
And to the tools:
@abapGit @abaplint @open-abap

If you want to help out, check this out:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/CONTRIBUTING.md

**Comment by ssocratous71** [comment]
Hi,
  i have made several additions to the View and added several missing(new) properties and new UI controls (like date_range_selection , bullet_micro_chart etc.) I am attaching the code in this message if you want to merge it with the original so everybody can use it.

Regards,
[z2ui5_cl_xml_view.txt](https://github.com/abap2UI5/abap2UI5/files/13737781/z2ui5_cl_xml_view.txt)

S.Socratous

**Comment by oblomov-dev** [comment]
Hi @ssocratous71 

Thank you a lot for sharing your code, this is a big help! 🙏

Just in case if you are interested, you can also consider creating a PR for abap2UI5, then you become a contributor and your work for the project gets visible. Check out the documentation here:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/21_contribution/pr_onprem.md

Best regards.
