### ISSUE TITLE
required field for label

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#310]
hello there, i added required field for label, and for some reason its not working, im seeing the value required in the DOM, but its not showing the red dot.

i did:

1. added required field to the view class along with the boolean handler from the local class.

2. in the label control added required = abap_true with labelFor = “the id for the input field”

sorry fpr not providing images or code, im working on a on-premise system without internet connection

**Comment by oblomov-dev** [comment]
hi, normally you do everything right. maybe you can create a small example to reproduce the error and share the code that i can copy&paste the class and can take a look to it.

**Comment by choper725** [comment]
ill try to do it using the _generic method and paste it here

**Comment by choper725** [comment]
[demo_02.txt](https://github.com/abap2UI5/abap2UI5/files/12267804/demo_02.txt)

added required field to the color input, something there not working.... any idea why ??

this demo seems straight forward, i have no idea why this is not working...
https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.Label/sample/sap.m.sample.Label/code

**Comment by oblomov-dev** [comment]
thanks for the example, will try to take a look to it tomorrow.

**Comment by oblomov-dev** [comment]
I added demo 51 but could not solve the problem 🤷‍♂️

Created the example exactly like in the documentation:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/a4b0bb90-f988-4455-923a-5526dd0e3300">

Do you ever tried building this in a normal UI5 app? I am really wondering why this is not working but have no idea about the reason at the moment.

**Comment by choper725** [comment]
the demo is a normal ui5 app no? its working there..
first i was thinking it got to do something with the labelFor property of the label..
maybe something is wrong there ?

**Comment by oblomov-dev** [comment]
yes unfortunately it is the same problem and also not working:

abap2UI5 direct xml:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/4b787a60-7f23-4943-ac93-05dc749034fa">

vs documentation:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/c7eb5749-be68-4d80-8b29-55d47ab7aae0">

**Comment by oblomov-dev** [comment]
ah never noticed this...  maybe because this is not an official sap ui5 url parameter?

**Comment by choper725** [comment]
maybe, but ever since the addition of app_start parameter, im getting this..
when it was without the paramater this error didnt show up

**Comment by oblomov-dev** [comment]
yes before it was with path/classname but this is not working with 
https://github.com/abap2UI5/ext-fiori_launchpad_on_premise
so i had to switch this.

**Comment by choper725** [comment]
yes, as you mentioned before, im just suffering from console sensetivety regarding errors :) , thats why i asked this..

**Comment by oblomov-dev** [comment]
Yes but can't find anything to avoid the error message and custom parameters are a common requirement. When I find something I will adjust it.

**Comment by choper725** [comment]
well @oblomov-dev  all of a suddon, i ran demo 51 and viola, its working...
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/c1a7b2a7-ee6e-4949-8b4a-9a21c948eb6b)

probebly a sdk issue..

**Comment by oblomov-dev** [comment]
nice, this are the best errors, yes maybe really something with the sdk. good that it is solved.
