### ISSUE TITLE
New version - findings

### ISSUE THREAD

**Issue by nomssi** [abap2UI5/abap2UI5#312]
Please check the demos:
- Input with Value Help : no errors, but it does not seem to work (no value help?)
- How To / More II - "Show Popup Input" yields an internal error.

Incompabilities:
Error if I define a boolean as XSDBOOLEAN. This used to work.

**Comment by oblomov-dev** [comment]
Thank you for the issue! Fixed the two findings!

The booleans should work as before, the following types are converted:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/fec3eb51-53cb-4e7f-b5dc-31ea9b6b9499">

You need something else?
