### ISSUE TITLE
Save the app state ?

### ISSUE THREAD

**Issue by nomssi** [abap2UI5/abap2UI5#321]
Hi Oblomov-Dev, 

I would like your feedback on 2 ideas before starting anything:

- Can I save the save of the app and reload it later? It seems like it is already been done with the draft table.
- Further, could I have an app (a game) with multiple concurrent users? I realize HTTP is not be the protocol of choice.  
- 
best regards,

Jacques Nomssi Nzali

**Comment by oblomov-dev** [comment]
Hi nomssi,

yes i played around with these drafts a lot. It is fast getting complicated but it is also a lot of fun!

(1) you can reload every draft, just save the id of your actual app [ client->get()-id ] in a additional db table and load it later with 
```abap
data(app) = client->get_app( my_id ).
client->nav_app_leave( app ).
```
added the demo repository with an example: z2ui5_cl_app_demo_62
<br>
(2) you can also restart apps several times and navigate the caller to the same draft, that they are in a way working in the "same" app <br>
check out the exapmple:  z2ui5_cl_app_demo_63
(coding not cleaned up but good for the start to see the idea)
<br>
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/3854e394-ff29-4e50-8ddd-af977b9b430b"><br>
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/60784428-d30b-4be1-9ba7-ea32fb801881"><br>
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/9ca12098-0df4-406d-829d-4ba68f4315f5"><br>
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/49cbe17b-dc65-4317-85dc-19bdc5ea6c2f"><br>
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/3ced0dfb-50f9-4e48-ba0e-bdf0dfd78c58"><br>
you have to press the button refresh all the time (amc/apc or event mesh could replace this)
<br>

with some creativity there are a lot of other possibilities now, for example sending the app state between different systems and so on and so on 😉 <br>

have fun and let me know if you run into problems.

**Comment by oblomov-dev** [comment]
i close this one, just reopen it if you further questions. later in the year i plan to do more examples with this approach.
