### ISSUE TITLE
Re-rendering partly 

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#334]
Hi oblomov,
I have the following use case.
I implemented a flexible column layout with two pages (master/detail).
On the master page I assigned a "TreeTable". The detail page should be render based on the selected tree table record.
If I trigger a re-rendering of the whole view, the expanded tree table becomes collapsed again (Initial behavior).
I tried to keep the "result" string, but the class "Z2UI5_CL_XML_VIEW" doesn't offer an "add result" method.
Do you have a "best-practice" approach for such an scenario?
Thanks a lot.
Kind regards
Axel

**Comment by choper725** [comment]
is it possible to pre-render the detail column with empty values and then render only the model one master event fires?

**Comment by oblomov-dev** [comment]
Hi together,

never tried something in this direction so i am not sure at the moment about the best way to add this functionality.

But i extended the client interface a little bit with https://github.com/abap2UI5/abap2UI5/pull/336
You can check demo: z2ui5_cl_app_demo_65

You now have the possibility to send an extra view and add this to a certain control identified by id. it works in the same way as popovers are used. expect some bugs, but you can adapt this for your master/detail page.

let me know if it works for you or if you need further adjustments.

**Comment by axelmohnen** [comment]
Hi,
I tried the "nested View" approach inside the "midColumnPages" aggregation of the FlexibleColumnLayout.
Therefore, I added the property "id" to the  method "mid_column_pages". 
Unfortunately, with the following error message.
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/41d361ae-1320-412a-b0f2-d5da9a3b18ad)

Could we maybe use the "visible" property from "sap.ui.core.Control" inside the "Flexbox" in order to hide/show dynamically certain areas?
Thanks,
Axel

**Comment by oblomov-dev** [comment]
Hi,

(1) Can you share a simple version of your app that i can see the control you use and how you aggregate them. Then i could check how we can add the additional view and trigger partly rerendering.

(2) Yes the visible property is owned by most of the controls, if you use this and the control has children also its children are hidden. so you can hide certain areas of the view with this.

Best regards.

**Comment by axelmohnen** [comment]
Hi,
here is my rendering part. For testing reason I added the "visible" parameter to the "flexbox" method.

`* ---------- Set view -----------------------------------------------------------------------------
    DATA(lr_view) = z2ui5_cl_xml_view=>factory( client = ir_client ).

* ---------- Set dynamic page ---------------------------------------------------------------------
    DATA(lr_dyn_page) =  lr_view->dynamic_page(
        showfooter = abap_false
       "  headerExpanded = abap_true
      "   toggleHeaderOnTitleClick = client->_event( 'ON_TITLE' )
     ).

* ---------- Get header title ---------------------------------------------------------------------
    DATA(lr_header_title) = lr_dyn_page->title( ns = 'f' )->get( )->dynamic_page_title( ).

* ---------- Set header title text ----------------------------------------------------------------
    lr_header_title->heading( ns = 'f' )->title( TEXT-t00 ).

* ---------- Get page content area ----------------------------------------------------------------
    DATA(lr_content) = lr_dyn_page->content( ns = 'f' ).

* ---------- Get Flex page layout -----------------------------------------------------------------
    Data(lr_flex_page) = lr_content->flexible_column_layout( layout = 'TwoColumnsBeginExpanded' ).

* ---------- Render master page -------------------------------------------------------------------
* ---------- Get master page ----------------------------------------------------------------------
    DATA(lr_master_page) = lr_flex_page->begin_column_pages( ).

* ---------- Bind tree table data -----------------------------------------------------------------
    ir_client->_bind( me->mt_master_tree ).

* ---------- Set tree table -----------------------------------------------------------------------
    DATA(lr_tree) = lr_master_page->tree_table(
      rows = `{path:'/MT_MASTER_TREE', parameters: {arrayNames:['CATEGORIES'], numberOfExpandedLevels: '2'}}`
      rowselectionchange = ir_client->_event( mc_evt_tree_select )
      selectionbehavior = 'RowOnly'
      selectedindex = ir_client->_bind_edit( me->ms_screen-selected_index ) ).

    lr_tree->tree_columns(
    )->tree_column( label = TEXT-t03
        )->tree_template(
        )->text( text = '{OBJECT}')->get_parent( )->get_parent(
        )->tree_column( label = TEXT-t04
        )->tree_template(
        )->text( text = '{COL2}')->get_parent( )->get_parent(
        )->tree_column( label = TEXT-t05
        )->tree_template(
        )->text( text = '{COL3}')->get_parent( )->get_parent(
        )->tree_column( label   = TEXT-t06
                        halign  = 'End'
        )->tree_template(
        )->text( text = '{COL4}').


* ---------- Render detail page -------------------------------------------------------------------
* ---------- Get detail page ----------------------------------------------------------------------
    DATA(lr_detail_page) = lr_flex_page->mid_column_pages( ).

* ---------- Set Flexbox in order to hide content dynamically -------------------------------------
    DATA(lr_flex_box) = lr_detail_page->flex_box( width = '100%' visible = ir_client->_bind_edit( lr_controller->ms_screen-visible ) ).

    DATA(detailpage) = lr_flex_box->object_page_layout(
         showtitleinheadercontent = abap_true
         showeditheaderbutton     = abap_true
         editheaderbuttonpress    =  ir_client->_event( 'EDIT_HEADER_PRESS' )
         uppercaseanchorbar       =  abap_false
     ).

    DATA(header_title) = detailpage->header_title(  )->object_page_dyn_header_title( ).

    header_title->expanded_heading(
            )->hbox(

                )->title( text = 'Oblomov Dev' wrapping = abap_true ).

    header_title->snapped_heading(
            )->flex_box( alignitems = `Center`
                )->title( text = 'Oblomov Dev' wrapping = abap_true ).


    DATA(sections) = detailpage->sections( ).

    sections->object_page_section( titleuppercase = abap_false id = 'goalsSectionSS1' title = 'General Information'
*        )->heading( ns = `uxap`
*            )->message_strip( text = 'this is a message strip'
*        )->get_parent(
        )->sub_sections(
            )->object_page_sub_section( id = 'goalssubSectionSS1' title = 'goals1'
                )->blocks(
                      )->vbox(
                      )->label( text    = 'goals1'
                      )->label( text    = 'goals1'
                      )->label( text    = 'goals1'
                      )->label( text    = 'goals1'
                      )->label( text    = 'goals1'
                      )->label( text    = 'goals1'
                      )->label( text    = 'goals1'
                      )->label( text    = 'goals1'
                      )->label( text    = 'goals1'
                      )->label( text    = 'goals1'

            )->get_parent( )->get_parent( )->get_parent(
            )->object_page_sub_section( id = 'goalsSectionWS1' title = 'goals2'
                  )->blocks(
                        )->vbox(
                      )->label( text    = 'goals2'
                      )->label( text    = 'goals2'
                      )->label( text    = 'goals2'
                      )->label( text    = 'goals2'
                      )->label( text    = 'goals2'
                      )->label( text    = 'goals2'
                      )->label( text    = 'goals2'
                      )->label( text    = 'goals2').

    sections->object_page_section( titleuppercase = abap_false id = 'PersonalSection' title = 'Suppliers'
"       )->heading( ns = `uxap`
      "     )->message_strip( text = 'this is a message strip'
"       )->get_parent(
       )->sub_sections(
           )->object_page_sub_section( id = 'personalSectionSS1' title = 'Connect'
               )->blocks(
                     )->label( text    = 'telefon'
                     )->label( text    = 'email'
           )->get_parent( )->get_parent(
           )->object_page_sub_section( id = 'personalSectionWS2' title = 'Payment information  '
                 )->blocks(
                     )->label( text    = 'Hello! I an abap2UI5 developer'
                     )->label( text    = 'San Jose, USA' ).

* ---------- Set View -----------------------------------------------------------------------------
    ir_client->view_display( lr_view->stringify( ) ).`

**Comment by oblomov-dev** [comment]
Nice thank you, if you also have the rest of the app that I copy&paste running snippet, feel free to share that I do not need to reconstruct the rest. The part how you create your tree model and how you call the nested view would be helpful.

**Comment by axelmohnen** [comment]
Hi,
I created a working example "Z2UI5_CL_APP_DEMO_66" in the demo repository.
PR has been created.
Note: 
You have to add the property (n = `id` v = `test`) inside  mid_column_pages( ) method. This is the area where we like to add the detail page.

Kind regards
Axel

**Comment by oblomov-dev** [comment]
You can check again!

Needed to extend the view class with some additional properties and adjusted the 63 demo a little bit.

Dependent on the control where you want to add the additional view, you have to use different methods for destroy/append. therefore i added two additional importing parameters.

Not sure if this is the best final solution or it gets to complicated with this, but you can try it out and then we will see.

**Comment by axelmohnen** [comment]
Hi,
I guess you mean demo 66. Anyway, the nested view works fine.
As you already mentioned, it's quite complicated and expects a deep knowledge of the corresponding SAPUI5 class methods.

FYI:
Demo 65 doesn't work anymore: "No value was passed to the mandatory parameter "METHOD_INSERT".

Thanks,
Axel

**Comment by axelmohnen** [comment]
Hi,
I found a side effect of the nested view. If you use inside a nested view a button control with model bindings to the "enable" or "icon" properties, the binding values are not taken into account.
I tested it without nested view and it works as expected.

Example:
`* ---------- Set header toolbar actions -----------------------------------------------------------
    lr_header_title->actions( ns = `uxap` )->overflow_toolbar(
         )->overflow_toolbar_button(
             icon    = 'sap-icon://full-screen'
             tooltip = TEXT-t09
             type    = 'Transparent'
             press   = ir_client->_event( mc_evt_fullscreen )
             enabled = ir_client->_bind( me->ms_screen-fullscreen_btn_enter_enable )
         )->overflow_toolbar_button(
             icon    = 'sap-icon://exit-full-screen'
             tooltip = TEXT-t10
             type    = 'Transparent'
             press   = ir_client->_event( mc_evt_fullscreen )
             enabled = ir_client->_bind( me->ms_screen-fullscreen_btn_exit_enable ) ).`

Thanks,
Kind regards
Axel

**Comment by axelmohnen** [comment]
Hi,
thanks a lot for the quick fix. The nested view binding works great now!
Kind regards
Axel
