### ISSUE TITLE
Model update only doesn't work anymore

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#338]
Hi,
with one of the last updates of the repository the "model only" update doesn't work anymore.
Please have a look to the demo "Z2UI5_CL_APP_DEMO_49".
I have the same behavior with the "TreeTable" control. 
Thanks a lot.
Kind regards
Axel

**Comment by oblomov-dev** [comment]
HI,

yes you have to use the follwing method now:
```abap
      client->view_model_update( ).
```

Added this yesterday. When you use your tree, you don't want to update your model otherwise the tree collapses, therefore i added this function. I will correct the demos next. Check z2ui5_cl_app_demo_28 for a working example.

**Comment by axelmohnen** [comment]
Hi oblomov,
Thanks it works!
Kind regards
Axel
