### ISSUE TITLE
Syntac error in Clas Z2UI5_CL_APP_DEMO_56

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5#339]
Hi,

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/d885b6ff-349f-4345-aed4-ece8d23c2eaf)

Best Regards
Thomas

**Comment by larshp** [comment]
also found in CI, https://github.com/abap2UI5/demo-demos/runs/14788470569

**Comment by Th0masMa** [comment]
Hi,

it works. Thanks. for the quick help.

Best Regards
Thomas
