### ISSUE TITLE
Need help UI Element sap.ui.table

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5#341]
Hi,

I have developed a class Z2UI5_CL_APP_DEMO_53_ui_new for the UI element sap.ui.table.
Unfortunately, the event for the toolbar button "BUTTON_TOOLBAR" is not generated. See method Z2UI5_ON_EVENT
`  METHOD Z2UI5_ON_EVENT.

    CASE client->get( )-event.

      WHEN 'BUTTON_SEARCH' OR 'BUTTON_START'.
        z2ui5_set_data( ).
        z2ui5_set_search( ).

      WHEN 'BUTTON_TOOLBAR'.
        client->message_toast_display( 'BUTTON_TOOLBAR' ).
      WHEN 'BACK'.
        client->nav_app_leave( client->get_app( client->get( )-id_prev_app_stack ) ).

    ENDCASE.

  ENDMETHOD.
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/0c8d3312-2fec-422d-b3ad-7bc91e9313af)

The sorting and filtering function on the columns is also not triggered.
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/84cdd50f-643e-467e-bd6b-baa0d70917d0)

Is anyone able to help me.
`
[Z2UI5_CL_APP_DEMO_53_UI_NEW.txt](https://github.com/abap2UI5/abap2UI5/files/11960164/Z2UI5_CL_APP_DEMO_53_UI_NEW.txt)

**Comment by choper725** [comment]
you are missing client->_event( …) i think..

**Comment by Th0masMa** [comment]
Hi,

All events are triggered. But how do I determine the return values for the respective events? The lt_arg table is empty.

`  METHOD z2ui5_on_event.

    CASE client->get( )-event.
      WHEN 'BUTTON_SEARCH' OR 'BUTTON_START'.
        client->message_toast_display( 'Search Entries' ).
        z2ui5_set_data( ).
        z2ui5_set_search( ).
        client->view_model_update( ).
      WHEN 'BUTTON_TOOLBAR'.
        client->message_toast_display( 'Event Button BUTTON_TOOLBAR' ).
      WHEN 'SORT'.
        DATA(lt_arg) = client->get( )-t_event_arg.
        client->message_toast_display( 'Event SORT' ).
      WHEN 'FILTER'.
        lt_arg = client->get( )-t_event_arg.
        client->message_toast_display( 'Event FILTER' ).
      WHEN 'ROWSELECTIONCHANGE'.
        lt_arg = client->get( )-t_event_arg.
        client->message_toast_display( 'Event ROWSELECTIONCHANGE' ).
      WHEN 'CUSTOMFILTER'.
        lt_arg = client->get( )-t_event_arg.
        client->message_toast_display( 'Event CUSTOMFILTER' ).
      WHEN 'BACK'.
        client->nav_app_leave( client->get_app( client->get( )-id_prev_app_stack ) ).
    ENDCASE.

  ENDMETHOD.`




[Z2UI5_CL_APP_DEMO_53_UI_NEW.txt](https://github.com/abap2UI5/abap2UI5/files/11970225/Z2UI5_CL_APP_DEMO_53_UI_NEW.txt)

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
Have you checked example 48 and 52? there the t_arg table is filled at the frontend.

**Comment by choper725** [comment]
no need for t_arg. and i dont think it will work as it is a header event

you just need to specify the field correctly

ie:
lo_columns->ui_column(  sortproperty = `**PRODUCT**` filterproperty = `PRODUCT` )->text( text = `Product` )->ui_template( )->text( `{**PRODUCT**}` ).

**Comment by Th0masMa** [comment]
Hi,

Most of it works now. But I still have no idea how to determine the selected rows. Can someone help me there?

Best Regards
Thomas

**Comment by choper725** [comment]
try adding a new field to the list bind table called row_id, fill it with row numbers and return it with the the row selection change like 
rowselectionchange = cliend->_event(  val = ‘row_id’ t_arg = VALUE #( ‘${ROW_ID}’ ) ).

anf then the t_arg in the events will be filled with the row_id

**Comment by choper725** [comment]
you are right.. i was doing something with it and implemented rowactionitem for that with an icon on the row.. check demo :
https://sapui5.hana.ondemand.com/sdk/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.RowAction

any way, this is working:
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/2996f6af-5b4d-4bd1-9c3c-6a826b5e477d)

event
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/da349f13-a7af-4f2b-9332-667fa34365df)

**Comment by Th0masMa** [comment]
See Example Z2UI5_CL_APP_DEMO_70.

**Comment by choper725** [comment]
just lije using rowaction, with rowaction you can have multiple icon with menu, ill try demo that today on your demo.

the functionallity you were asking above was on the entire row click, thats what i got in the screenshot

**Comment by Th0masMa** [comment]
Hi @choper725,

Can you send the Code snippet.

Best Regards
Thomas

**Comment by choper725** [comment]
check demo 71
