### ISSUE TITLE
client->get( )-id_prev_app_stack )

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5#362]
Hi,

i pull the new repository and receive a Error.

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/68c4f064-7705-4d2d-b0d4-50b8a5497096)

**Comment by oblomov-dev** [comment]
yes update the demo repository, then it will work. or correct to:
client->get( )-s_draft-id_prev_app_stack

**Comment by Th0masMa** [comment]
It works.
