### ISSUE TITLE
error in demo 66 & on-prem http handler

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#364]
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/4b2e56f3-4f2c-4167-8d41-71f7983b90f1)

and btw, missing parenthesis closing the SWITCH in the on-prem http handler code.

**Comment by oblomov-dev** [comment]
fixed both errors with https://github.com/abap2UI5/abap2UI5/pull/366
