### ISSUE TITLE
error in console regarding app_start

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#369]
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/e523a9b6-afb4-40d0-97c8-49f0acd10def)

dont know if stuff breaks yet, but im getting this error in console..

**Comment by oblomov-dev** [comment]
my console looks fine. when do you get this message in specific?

**Comment by choper725** [comment]
im offline currently but it comes up when i run a class with this url parameter,  if i remember correctly when there are errors in the xml view. sometimes i get only this error and a blank screen, i was trying to implement nested vies if that helps..

**Comment by oblomov-dev** [comment]
checked the nested views and i don't have this error 🤷‍♂️ let me know if it comes up more often and in which specific situation.

**Comment by oblomov-dev** [comment]
Thank you for the hint. Added the logging for nested views and popovers again.

**Comment by oblomov-dev** [comment]
checked this further and it seems only to occure for certain UI5 version. for instance:
https://ui5.sap.com/1.115.0/resources/sap-ui-cachebuster/sap-ui-core.js
you get:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/c8b70585-d159-42bd-a33a-2fa4d49efae9">

but for nearly all other versions like:
https://ui5.sap.com/1.120.0/resources/sap-ui-cachebuster/sap-ui-core.js
everything is fine and you get:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/ad9e7f9f-0585-4dd3-ac20-cd732759fa3a">

I also observe this from time to time on S/4 Public cloud system with standard apps. 

So it looks not like a bug of abap2UI5 for me.

**Comment by choper725** [comment]
true, stopped seeing that error also
