### ISSUE TITLE
Display currency value according associated currency

### ISSUE THREAD

**Issue by CalvinwithHobbes** [abap2UI5/abap2UI5#370]
hi there,
I am looking for a solution to display a currency value. The currency value should be displayed correctly with the correct decimal fields according to an associated currency.
Any ideas? 
Best Regards
Calvin

**Comment by choper725** [comment]
you can use the decimal method in the view class to display value and currency symbol

**Comment by oblomov-dev** [comment]
Hi Calvin,

updated the demo section today, check demo 66. Would recommend checking the sap documentation and try to go a similar way:
https://sapui5.hana.ondemand.com/#/entity/sap.ui.model.type.Currency

<img width="300" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/5e78714a-5b29-4520-829d-d00a7ec55b24">
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/559162a8-38fa-4cfc-aa57-9d75d73dd75b">

best regards.

**Comment by CalvinwithHobbes** [comment]
Hi oblomov-dev
thank you very much for your fast help.
Regards, 
Calvin
