### ISSUE TITLE
How do I provide the tree structure for sap.m.Tree?

### ISSUE THREAD

**Issue by WegnerDan** [abap2UI5/abap2UI5#373]
This isn't really an issue, more of a request for help. 
Maybe discussions should be activated for this repo? 

I've done this before with OData, but I'm unsure how to do this with abap2ui5.

I've added sap.m.Tree and sap.m.StandardTreeItem with commit https://github.com/WegnerDan/abap2UI5/commit/f8997b52ae6bdae290036ccda46a3af1eebd92a0
I've not sent a pull request yet.

This is how far I've gotten:
![image](https://github.com/abap2UI5/abap2UI5/assets/6908247/f53f40c7-aa7a-4be8-8414-b9fc7b6addce)

```abap

    DATA(popup) = z2ui5_cl_xml_view=>factory_popup( client ).

    DATA(dialog) = popup->dialog( title         = f4help-title
                                  contentheight = '50%'
                                  contentwidth  = '50%' ).
    dialog->tree(
            mode  = 'SingleSelectMaster'
            items = client->_bind_edit( f4help-values )
        )->items(
            )->standard_tree_item( selected = '{IS_SELECTED}'
            title = '{VALUE}'
    ).

    dialog->buttons(
    )->button( text  = 'Abbrechen'(009)
               icon  = `sap-icon://decline`
               type  = `Reject`
               press = client->_event( c_event-f4help_cancel )
    ).

    client->popup_display( popup->stringify( ) ).

```

**Comment by WegnerDan** [comment]
As I understand it, I need the editable binding to be able to find out which tree item is selected, right? 
Or is there a way to do this with _bind? 

With _bind there is no runtime error, as you've said. 

I will look into the mentioned source code spots.

**Comment by oblomov-dev** [comment]
Yes when you want to transport the selected property then you have to use  bind_edit.

If possible maybe you can also provide a version of your app without database usage? I can use this then as an example for testing making it easier to figure out how to solve this.

**Comment by oblomov-dev** [comment]
Nice work! Looks good to me! Pretty printer is no problem, feel free to send a PR. 

Can I use the version without db for the demo repository?

**Comment by WegnerDan** [comment]
> Can I use the version without db for the demo repository?

Yep, feel free!
