### ISSUE TITLE
CREATE DATA: The specified type ("__DYNAMICALLY_CREATED_TYPE__") is not allowed here

### ISSUE THREAD

**Issue by snbandi** [abap2UI5/abap2UI5#385]
I am getting the following error while launchng the service from SICF(Handler class Z_CL_ABAP2UI5_RH of service "/sap/fdor/abap2ui5" -

![image](https://github.com/abap2UI5/abap2UI5/assets/29529086/4752526d-4a1b-41c8-a2b1-245d30b349e4)

Here is the ST22 dump -

Category               ABAP programming error
Runtime Errors         CREATE_DATA_NOT_ALLOWED_TYPE
Except.                CX_SY_CREATE_DATA_ERROR
ABAP Program           /UI2/CL_JSON==================CP
Application Component  BC-FES-BUS-RUN
Date and Time          07/15/2023 09:11:22

 Short Text
     CREATE DATA: The specified type ("__DYNAMICALLY_CREATED_TYPE__") is not
      allowed here.

 What happened?
     Error in the ABAP application program.

     The current ABAP program "/UI2/CL_JSON==================CP" had to be
      terminated because it found a
     statement that could not be executed.

Information on where terminated
    The termination occurred in ABAP program or include
     "/UI2/CL_JSON==================CP", in "RESTORE". The
    main program was "SAPMHTTP".

    In the source code, the termination point is in line 31 of  program or
    include "/UI2/CL_JSON==================CM008".
    The termination is due to exception "CX_SY_CREATE_DATA_ERROR" occurring in
     procedure "RESTORE" "(METHOD)".
    This exception was not handled locally or declared in the RAISING
    clause in the procedure's signature however.
    The procedure is in program "/UI2/CL_JSON==================CP". The source
     code begins in line 1 of
    (include) program "/UI2/CL_JSON==================CM008".

Active Calls/Events

No.   Ty.          Program                             Include                             Line
      Name

   11 METHOD       /UI2/CL_JSON==================CP    /UI2/CL_JSON==================CM008    31
      /UI2/CL_JSON=>RESTORE
   10 METHOD       /UI2/CL_JSON==================CP    /UI2/CL_JSON==================CM009   109
      /UI2/CL_JSON=>RESTORE_TYPE
    9 METHOD       /UI2/CL_JSON==================CP    /UI2/CL_JSON==================CM00I    28
      /UI2/CL_JSON=>DESERIALIZE_INT
    8 METHOD       /UI2/CL_JSON==================CP    /UI2/CL_JSON==================CM007    19
      /UI2/CL_JSON=>DESERIALIZE
    7 METHOD       Z2UI5_CL_HTTP_HANDLER=========CP    Z2UI5_CL_HTTP_HANDLER=========CCIMP   764
      Z2UI5_LCL_UTILITY_TREE_JSON=>FACTORY
    6 METHOD       Z2UI5_CL_HTTP_HANDLER=========CP    Z2UI5_CL_HTTP_HANDLER=========CCIMP  1333
      Z2UI5_LCL_FW_HANDLER=>REQUEST_BEGIN
    5 METHOD       Z2UI5_CL_HTTP_HANDLER=========CP    Z2UI5_CL_HTTP_HANDLER=========CM002     3
      Z2UI5_CL_HTTP_HANDLER=>HTTP_POST
    4 METHOD       Z_CL_ABAP2UI5_RH==============CP    Z_CL_ABAP2UI5_RH==============CM001     3
      Z_CL_ABAP2UI5_RH=>IF_HTTP_EXTENSION~HANDLE_REQUEST
    3 METHOD       CL_HTTP_SERVER================CP    CL_HTTP_SERVER================CM00I   801
      CL_HTTP_SERVER=>EXECUTE_REQUEST
    2 FUNCTION     SAPLHTTP_RUNTIME                    LHTTP_RUNTIMEU02                     1453
      HTTP_DISPATCH_REQUEST
    1 MODULE (PBO) SAPMHTTP                            SAPMHTTP                               12
      %_HTTP_START

This is from SAP NETWEAVER 7.5
![image](https://github.com/abap2UI5/abap2UI5/assets/29529086/b6a59a84-8bfb-4de1-9f10-672550cc8dc1)

Can you please look into what is causing this error from class /UI2/CL_JSON?

**Comment by oblomov-dev** [comment]
can you create an external breakpoint at this position:
7 METHOD Z2UI5_CL_HTTP_HANDLER=========CP Z2UI5_CL_HTTP_HANDLER=========CCIMP 764
Z2UI5_LCL_UTILITY_TREE_JSON=>FACTORY
<img width="916" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/8f5c9ed4-8243-42f6-ae16-16db363ccdde">

And copy the value of variable "iv_json".

Thank you.

**Comment by snbandi** [comment]
Please see below -

![image](https://github.com/abap2UI5/abap2UI5/assets/29529086/ac0b8076-88fa-42b1-a8a6-d72b58db8410)

{"OLOCATION":{"ORIGIN":"http://host:8000","PATHNAME":"/sap/fdor/abap2ui5","SEARCH":"?sap-client=100","VERSION":"com.sap.openui5.dist:sdk:1.116.0:war"}}

**Comment by oblomov-dev** [comment]
Oh sorry, didn't want you to publish the url etc. just want to check if the json looks fine, but it is!

Can you create a new report and only execute the following and see if it works:
```abap
data lv_json type string.
data lr_result type ref to data.
lv_json = `{"OLOCATION":{"ORIGIN":"http://host:8000","PATHNAME":"/sap/fdor/abap2ui5","SEARCH":"?sap-client=100","VERSION":"com.sap.openui5.dist:sdk:1.116.0:war"}}`.

/ui2/cl_json=>deserialize( EXPORTING json         = CONV string( lv_json )
                                         assoc_arrays = abap_true
                               CHANGING  data         = lr_result ).
```
And replace the lv_json with your value.

Till now it seems not like an abap2UI5 problem to me. More like somethig is wrong with /ui2/cl_json in your system.

**Comment by snbandi** [comment]
Thank you for quick response.

No aplogies necessary. I am trying to be careful regarding my client system.

You are correct, class /ui2/cl_json code on that box seems to bit old. I ran the above suggested code on another box, that ran fine.  I will have the code applied on Monday and check again to close this issue.
