### ISSUE TITLE
Url  Additional Parameter how to access in cust APP class

### ISSUE THREAD

**Issue by smithmarius** [abap2UI5/abap2UI5#391]
Hi.

Could you please demonstrate how I can use a additional url parameter ie "workitem" and acess it in the app class .  
"?app_start=z2ui5_cl_app_demo_XX&**work_Item=234**".
The idea is to use this to visualise this passing of the parameter in tx swfvisu to call the app as an approving step in a workflow. The APP will then use the workitem to initialise the content as needed based on the workitem passed .

**Comment by oblomov-dev** [comment]
hi @smithmarius,

yes you can add url parameters, for example:
<<server>>/<<handler>>?sap-client=100&app_start=z2ui5_cl_app_hello_world&myparam=test

And read it in your app with this methods:
```abap
    DATA(lv_search) = client->get( )-s_config-search.
    DATA(lv_param) = z2ui5_cl_xml_view=>factory( client )->hlp_get_url_param( `myparam` ).
```

Best regards.

**Comment by smithmarius** [comment]
Excellent ! Thank you for a excellent framework.!

**Comment by smithmarius** [comment]
Answered.
