### ISSUE TITLE
Open dynamic URL within ABAP2UI5 App

### ISSUE THREAD

**Issue by CalvinwithHobbes** [abap2UI5/abap2UI5#398]
Hi oblomov-dev, hi together,

I have a more special issue, probably out of range.

I want to display an archived document within my ABAP2UI5 App  in another browser tab. 

In SAP you can call the function module SCMS_URL_GENERATE to retrieve a URL out of the archive information (Archive-ID/Document-ID) with all the necessary seckeys.

  call function 'SCMS_URL_GENERATE'
    exporting
      command         = 'get'
      contrep         = v_archiv_id
      docid           = v_doc_id
      tooffset        = lv_tooffset
      accessmode      = lv_accessmode
      security        = lv_security
    importing
      absolute_uri    = lv_uri
    exceptions
      error_parameter = 1
      error_signature = 2
      others          = 3.

Within my abap2ui5-app I have a table and a cell with a button to retireve the archiving information(in the table row) and call the event "DISPLAY_DOCUMENT"

      lo_cells->button( icon = 'sap-icon://document-text'
                        press = o_client->_event(  val = `DISPLAY_DOCUMENT` t_arg = value #( ( `${COREP}` ) ( `${DOCID}` )  ( `${CLASS}` ) )  ) ).

The event "DISPLAY_DOCUMENT" calls a method with the function module SCMS_URL_GENERATE above to return the URL.
Now I am stuck how to open this URL in a new browser tab.
Any ideas?

**Comment by oblomov-dev** [comment]
HI Calvin,

normally the best way would be to create all URLs in advance and then change the cell to a link and use the following control:
```abap
  )->link(
       text = 'Open URL in new tab'  target = '_blank'
       href = `https://www.github.com/abap2UI5`
```
You can trigger the new tab via the XML View with this.

But it seems that you cannot create all links in advance and have in mind to create a link after an event and then create a new tab. You can use this little workaround:

When you are in the event implementation and created your new link, you can go back to the frontend but register an action for the future. In this case we call the action directly (0 ms) and open a new tab
```abap
client->timer_set(
      interval_ms    = 0
      event_finished = client->_event_client( action = client->cs_event-open_new_tab 
                                              t_arg = value #( ( `https://www.github.com/abap2UI5` )  )
      ) ).
```
Let me know if this works for you.

**Comment by CalvinwithHobbes** [comment]
Hi oblomov-dev,
many thanks to your reply.  
Unfortunately I cannot create the URL in advance as the seckey includes some timeslot. After some minutes the URL is invalid.

Propably it could work if I would include some JavaScript code like : 

`window.open("https://www.github.com/abap2UI5", "abap2ui5Tab");`

Is there a possibility to include some HTML or JavaScript ?
Regards
Calvin

**Comment by oblomov-dev** [comment]
You can include HTML and JavaScript:
https://blogs.sap.com/2023/04/12/abap2ui5-5-6-extensions-with-xml-views-html-js-custom-controls/

But in this case i would recommend just calling a new app via _event_client, you can check the following example:
https://github.com/abap2UI5/demo-demos/blob/main/src/z2ui5_cl_app_demo_73.clas.abap

Best regards.

**Comment by CalvinwithHobbes** [comment]
Hi oblomov-dev, hi all,

Just to give you some feedback. I am a little step further. 
As you suggested I implemented a new app receiving the generated url.  In the new app I used your example 
[https://github.com/abap2UI5/demo-demos/blob/main/src/z2ui5_cl_app_demo_73.clas.abap](url) as template and adapted it a little bit:

```
    data(lo_view) = z2ui5_cl_xml_view=>factory( o_client ).
    data(lv_xml) = `<mvc:View controllerName="project1.controller.View1"` && |\n|  &&
                   `    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"` && |\n|  &&
                   `  xmlns:z2ui5="z2ui5"  xmlns:m="sap.m" xmlns="http://www.w3.org/1999/xhtml"` && |\n|  &&
                   `    ><m:Button ` && |\n|  &&
                   `  text="back" ` && |\n|  &&
                   `  press="` && o_client->_event( 'BACK' ) && `" ` && |\n|  &&
                   `  class="sapUiContentPadding sapUiResponsivePadding--content"/> ` && |\n|  &&
                   `       <m:Link target="_blank" text="Source_Code" href="` && lo_view->hlp_get_source_code_url(  ) && `"/>` && |\n|  &&
                   `<html><head>` && |\n|  &&
                  `<title>Document</title>` && |\n|  &&
                  `</head>` && |\n|  &&
                  `<body>` && |\n|  &&
                  '<script> window.open(' && '"' && v_url && '"' && ', "Document"); </script>' && |\n|  &&
                  `</body>` && |\n|  &&
                  `</html>` && |\n|  &&
                   `</mvc:View>`.

    o_client->message_toast_display( | HTML: { lv_xml } | ).
    o_client->view_display( lo_view->hlp_replace_controller_name( lv_xml ) ).
```

The important JavaScript-part is
`'<script> window.open(' && '"' && v_url && '"' && ', "Document"); </script>'`

When using a simple url without any parameters, 
e.g. `v_url = 'https://www.google.com/'. `  
everything is working fine.

But as soon as parameters are included it does not work anymore. 
e.g. `v_url = 'https://www.google.com/search?q=abap2ui5&oq=abap2ui5'.`


Unfortunately this has something to do with JavaScript and the `window.open`-method.
I'll continue to search for a solution and keep you up to date as soon I know more.
Meanwhile, if you have any ideas don't hesitate to answer ;-)
Regards
Calvin

**Comment by oblomov-dev** [comment]
Did you also checked doing it without extra javascript?

I updated the demo again with your new url:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_app_demo_73.clas.abap

You don't need to call the window.open function by yourself, you can just call this via frontend function of abap2ui5 with:
```abap
      WHEN 'BUTTON_OPEN_NEW_TAB'.
        client->timer_set(
            interval_ms    = `0`
            event_finished = client->_event_client( action = client->cs_event-open_new_tab
                                              t_arg = value #( ( `https://www.google.com/search?q=abap2ui5&oq=abap2ui5` )  )
      ) ).
```

This works on my side.

If you really want to send JS to the frontend, try;
```javascript
window.open( <<url>> , '_blank' );
```

Best regards.

**Comment by CalvinwithHobbes** [comment]
Hi oblomov-dev,

you made my day !!
Thank you. It absolutely works fine with your sample class
[https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_app_demo_73.clas.abap](url)

Why didn't I listen to you already in the first reply?? :-)
Many thanks!

Regards,
Calvin
