### ISSUE TITLE
SELECT-OPTIONS in abap2UI5

### ISSUE THREAD

**Issue by sun-tassein** [abap2UI5/abap2UI5#406]
Is there a way to use SELECT-OPTIONS from standard ABAP GUI screens or something similar to them.
Basically i have a requirement where the user wants to paste multiple documents and get some report output, in standard ABAP i would just use a SELECT-OPTIONS for this.
I didnt see an example for this in the demos without importing a file but i may have missed something.

Also just wanted to thank you, this is an amazing project, SAP should learn from you in designing their systems.

**Comment by oblomov-dev** [comment]
Hi @sun-tassein,

updated the demo repository, you can check:
z2ui5_cl_app_demo_56

There is no UI5 control which exactly mimics select-options, but you can try multi_input combined with a popup. This is also the way SAP is going in their Fiori Elements apps. The multi_input is not editable to guarantee that only valid range parameters can be done. In the coding you can see that the input is mapped to a range table and you get the same result as you would get when you work with select-options in selection-screens. Maybe there are still some bugs in the example but hopefully it is enough to start with.

Thank you for your nice comment, it's nice to hear that you like the project.

Best regards.

**Comment by sun-tassein** [comment]
Thanks for your help, this solution is not exactly what i was looking for. I looked a little deeper into the sap.m.MultiInput object, and from the references that is actually exactly what i need but i cant seem to make it work the same way as in the official SAP samples.
Whenever i try pasting multiple values into the field it only pastes the first one.

On this link [https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInput](url), what i am getting in abap2UI5 is the first example (Enter a search term, e.g. “Notebook”, and add matching products as tokens) so it saves only a single input/token, and what i would want is the second example (MultiInput with pre-selected tokens) here i select the field and paste and all of the items/tokens are pasted into the field where i could suposedly to something with them in the backend with ABAP.

**Comment by oblomov-dev** [comment]
Yes the multi input control in combination with token controls is very complex.

Did also not find a solution for this problem yet. Played around with:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_app_demo_78.clas.abap

But when i copy multiple tokens and paste them again it seems that there is no backend event to fill up the token table, checked the properties and events  🤷‍♂️  

When i find a way i will let you know again.

**Comment by ssocratous71** [comment]
I have tried multi-input and there is also another problem when deleting tokens. It starts even tokenupdate and removes the token from the UI , but you have no way to know which one was removed to update token table in backend. Is there a workaround on this?

**Comment by oblomov-dev** [comment]
Have not found a solution yet, but @axelmohnen found a little workaround, maybe this also helps you.

Check out his generic search help in the tools repository:
https://github.com/abap2UI5/abap2UI5-tools/tree/main

There you can find a trick how to read the deleted tokens in the backend:
https://github.com/abap2UI5/abap2UI5-tools/blob/509454a1f28f6281a4ec7210a7ab078ea21e3fb7/src/z2ui5_cl_tool_app_shlp_gen.clas.abap#L633

**Comment by ssocratous71** [comment]
Excellent. Now it works!!!! Keep up the good work!

**Comment by oblomov-dev** [comment]
fyi @sun-tassein @ssocratous71 

updated the token handling again. Now it is possible to copy&paste multiple tokens. On my side it behaves now like the  MultiInput in the UI5 demos. Check out this demo:
z2ui5_cl_demo_app_078
![image](https://github.com/abap2UI5/abap2UI5/assets/102328295/57fa8ba6-da37-43ef-ac40-7949989feb40)

Added a new custom UI5 Control to abap2UI5 which extends the normal MultiInput and added the correct transfer of added/deleted tokens to the backend:
https://github.com/abap2UI5/abap2UI5/blob/main/src/01/03/z2ui5_cl_fw_cc_multiinput.clas.abap

Let me know if you still miss a functionality.

Best regards.

**Comment by oblomov-dev** [comment]
i close this issue, just open a new one if you have question or need further functionality.
