### ISSUE TITLE
Gantt Chart not getting model in sap.z2ui5.oResponse.OVIEWMODEL

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#414]
Hi @oblomov-dev 
i dont seem to get model in sap.z2ui5.oResponse.OVIEWMODEL running tree table in gantt chart,
seems to be empty.
am i doing something wrong or its just not possible to implement this chart..?

based on my latest pr  https://github.com/abap2UI5/abap2UI5/pull/413/commits/91317dc0087451a5b60c1065464a594ac7c957a0
this is the code snippet for the demo gantt.simple based on JSON Model.
https://sapui5.hana.ondemand.com/#/entity/sap.gantt.simple.GanttChartWithTable/sample/sap.gantt.sample.GanttChart2JSON

[Z2UI5_CL_APP_DEMO_GANTT.txt](https://github.com/abap2UI5/abap2UI5/files/12148455/Z2UI5_CL_APP_DEMO_GANTT.txt)

**Comment by oblomov-dev** [comment]
HI @choper725,

thank you for the example. I added the model binding which sends the data to the frontend. Adjusted the following:
```abap
 )->tree_table( rows = `{path: '` && client->_bind( val = mt_table path = abap_true ) && `', parameters: {arrayNames: ['CHILDREN'],numberOfExpandedLevels: 1}}`
```
You can check this example:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_app_demo_76.clas.abap

<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/9bb57a23-a686-4311-baf2-a093b57dd83b">

The model is now not empty anymore:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/d1b34f3b-da60-4b23-8a21-e0c0e3a0cd55">

Best regards.

**Comment by choper725** [comment]
thanks! i saw that demo 07 (tree table) was adjusted also for the new syntax..

ill try get it to work now!

**Comment by choper725** [comment]
got it to display the tree but, the tasks need date object in order to work, hence the formatter there, but for some reason its not working, even if i put the method in the controller.. not getting called

**Comment by oblomov-dev** [comment]
can you update your example with your actual version?

Normally i would guess, you can do the following in the backend and just skip the formatter:
<img width="648" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/edefd084-d4be-437f-be68-05c450dec0c2">

**Comment by choper725** [comment]
here it is

[Z2UI5_CL_APP_DEMO_76.txt](https://github.com/abap2UI5/abap2UI5/files/12171749/Z2UI5_CL_APP_DEMO_76.txt)


you mean dealing with Date object in abap ??

**Comment by oblomov-dev** [comment]
yes instead of using the formatter at the frontend, try to do the changes directly in the backend and send the ready formatted values to the frontend.

**Comment by choper725** [comment]
yeah, i tried to send the date string instead of timestamp but its not wirking either…

**Comment by oblomov-dev** [comment]
did you try without these { }?

maybe something like this works:
```js
{ path : '/starttime' , formatter...
```
set the path paramter = abap_true like:
```abap
             )->object_number(
                   state = '{STATE_PRICE}'
                   number = `{ parts: [ { path : 'PRICE' } , { path : 'WAERS' } ] } `
              ).
```

**Comment by choper725** [comment]
thanks ! adding parts did the trick, for the time

regarding the TASK and SUBTASK .. nothing worked there adding the templateSharing parameter..

any way, got it to work
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/bbb6fbc8-96ec-4e2c-bc32-d30d99fdef25)

now just need to handle the Date object being sent to the time & endtime properties, without the formatter..

any idea how to do so in abap ?
how its possible to create a js Date object in abap ?

**Comment by oblomov-dev** [comment]
yes i think it could work but the date field also made troubles here:
https://github.com/abap2UI5/abap2UI5/issues/401#issuecomment-1646958812

when you make it to send it to the frontend it hope it will work, otherwise you can update the example again that i can take a look to it.

**Comment by choper725** [comment]
created pr for new demo update

demo is not working as the formatter function not in the http_handler method, in order to get it to work, need to add this:

       `            ` && |\n|  &&
       `            fnTimeConverter: function (sTimestamp) {` && |\n|  &&
       `              return new sap.gantt.misc.Format.abapTimestampToDate(sTimestamp);` && |\n|  &&
       `            },` && |\n|  &&

tried changing it to string of Date function but im getting this..
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/be0c8387-ab57-4a93-886b-94ca52b787a8)

i dont think this is possible without formatter function...

**Comment by choper725** [comment]
solved
