### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#420]
Hi,
I have the requirement to display the GOS attachments (PDF) from business object into ABAP2UI5.
Do you have already such a control to display PDF (binary format)?

The control "sap.m.UploadCollection" could be an option, but I don't know it works with a binary string.

Thanks,
Axel

**Comment by oblomov-dev** [comment]
Hi @axelmohnen,

did not find an ui5 control for this (only which depend on frontend JS). But you can send it as base64 to the frontend and display it in an iframe. Updated the demo repository, check:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_app_demo_79.clas.abap

<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/f0f0f907-f8f1-46cf-aac0-fa66d7d39829">

**Comment by axelmohnen** [comment]
Hi oblomov,
this works great! Thanks a lot.
The sap.m.PDFViewer control is more or less doing the same. It creates an iFrame as well.
Kind regards
Axel
