### ISSUE TITLE
error in xml view - rating indicator

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#428]
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/586ca5a1-49fe-4c63-b29a-08d2d2017cde)

![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/9b5e2ca9-0207-4673-a520-531b9ceea8e5)

**Comment by oblomov-dev** [comment]
thank you for the hint, fixed with https://github.com/abap2UI5/abap2UI5/pull/429
