### ISSUE TITLE
getting error in z2ui5_cl_fw_utility

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#441]
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/b1a29d7f-646c-438e-bb43-367770d8d582)

also here
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/a5a0038d-41e3-4faa-884b-8615056c0da3)

**Comment by oblomov-dev** [comment]
thanks for the hint, should be fixed with https://github.com/abap2UI5/abap2UI5/pull/442
