### ISSUE TITLE
Using class text elements for translation

### ISSUE THREAD

**Issue by CalvinwithHobbes** [abap2UI5/abap2UI5#447]
Hi all,

I have another issue. 
I am using a title on my page with the following coding:

```
      data(lv_title) = 'This is my title'.
      data(view) = z2ui5_cl_xml_view=>factory( client = o_client ).

      data(page1) = view->page( id  = `MAIN_PAGE`
                                title  = lv_title
                                navbuttonpress  = o_client->_event( 'BACK' )
                                shownavbutton  = abap_true ).
```

everything is working fine. The title appears on my page 
![image](https://github.com/abap2UI5/abap2UI5/assets/28622781/87e0f4b6-5a6d-4002-815f-ac16a23e369d)

But as I want to translate the title into another language according the logon language of the user, I want to use class text elements.
I assign the class text element text-001 the text 'This is my title' and adapt the coding to:

```
      data lv_title type string.
      lv_title = text-001.
      data(view) = z2ui5_cl_xml_view=>factory( client = o_client ).

      data(page1) = view->page( id = `MAIN_PAGE`
                                title = lv_title
                                navbuttonpress = o_client->_event( 'BACK' )
                                shownavbutton  = abap_true ).
```
 Unfortunately the title is not displayed on the page.
Any ideas?
Regards
Calvin

**Comment by oblomov-dev** [comment]
Hi calvin,

can you make a breakpoint at this position:
   data(page1) = view->page( id = `MAIN_PAGE`

and show the value of the variable lv_title?

Maybe the logon language of your browser is different and therefore the title is not set? You can also check sy-langu in the debugger to make sure you have the right language.

Best regards.
