### ISSUE TITLE
Date Picker value not getting updated in backend table when in a table

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#457]
im trying to get a datepicker column in demo70

[datepicker.txt](https://github.com/abap2UI5/abap2UI5/files/12260101/datepicker.txt)

but the value in the date picker is not getting updated in the table mt_table..
any idea why ??

**Comment by oblomov-dev** [comment]
i am not sure if this solves the problem, because it is a complex use case (aggregation + path etc) but you did not set the table to bind_edit, maybe this is one step closer to the solution?

**Comment by choper725** [comment]
oh sorry, i tried but it still not working..

**Comment by choper725** [comment]
solved by using displayFormat and valueFormat, to comply with abap dats format..

)->date_picker( value = `{CREATE_DATE}`  displayFormat = 'dd/MM/yyyy' valueFormat = 'yyyyMMdd' ).

**Comment by oblomov-dev** [comment]
Ah good to know! thank you for the information.
