### ISSUE TITLE
Flow Logic 

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5#461]
Hi @oblomov-dev ,

I want to call another app Z2UI5_CL_APP_DEMO_25 from the example Z2UI5_CL_APP_DEMO_80.

```
    CASE client->get( )-event.
      WHEN 'CallApp' .
        client->nav_app_call( NEW z2ui5_cl_app_demo_25( ) ).
```
That works too. Only the return does not work.
in result->
![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/bb53560f-1ada-4811-85c4-37bca295fe5d)

It goes from app Z2UI5_CL_APP_DEMO_24 to app Z2UI5_CL_APP_DEMO_25.
Exactly the same syntax is used in the app Z2UI5_CL_APP_DEMO_24. What am I doing wrong?

Best Regards 
Thomas

**Comment by oblomov-dev** [comment]
Did you use the method "nav_app_leave" to go back? 
Otherwise when you use nav_app_call a new instance is created and you will not get the former state.

**Comment by Th0masMa** [comment]
i use "back" to go back. 
How is the correct syntax to call a App and go back to the previous app?

**Comment by oblomov-dev** [comment]
first call an app:
```abap
client->nav_app_call( new my_app() )
```
then go back to the calling app with:
```abap
client->nav_app_leave( client->get_app( client->get( )-s_draft-id_prev_app_stack ) )
```

this is how it works in all samples. not sure if i got your point.

**Comment by Th0masMa** [comment]
Hi @oblomov-dev ,

i change the example 80. 

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/c2d238f2-b225-4dd2-9e44-82338d146b59)

Call the app Z2UI5_CL_APP_DEMO_25

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/359dab58-0667-46d1-976b-0d65ce181c3a)

I can't get back to the previous app.

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
thank you for providing the example, makes it very easy to find the problem quickly.

the demo was a little bit misleading. everything worked correctly, the only problem was that the view of the planning calender was not displayed again. there is an check variable "check_on_navigated" which is true when there is an app change, initial app load or navigation. i recommend to display the main view again,  every time this variable is true.

slightly adjusted the app with:
```abap
    IF client->get( )-check_on_navigated = abap_true.
      z2ui5_display_view( ).
      RETURN.
    ENDIF.
```
Now it works fine.

**Comment by Th0masMa** [comment]
Excellent. You are the greatest!!!!!!!!!!!!
