### ISSUE TITLE
selected property for list in popover not updating in table

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#463]
hi @oblomov-dev 

im trying to implement a list inside of a popover, all seems to go well execpt selected property not updating the binded table (used _bind_edit).

ill upload an example here soon.

**Comment by choper725** [comment]
[list in popover.txt](https://github.com/abap2UI5/abap2UI5/files/12270086/list.in.popover.txt)

example: press 'post' button

**Comment by oblomov-dev** [comment]
i remember some problems with the selected property. but the functionality is working when you use it not in a popover? for example on the main screen or normal popup?

**Comment by choper725** [comment]
it does work correctly when not in popover.. is that a bug in ui5 also ?

**Comment by oblomov-dev** [comment]
maybe in the popover and view model processing in abap2UI5 is a bug, will try to take a look to it tomorrow.

**Comment by oblomov-dev** [comment]
there was a bug in the view model of popovers. fixed it and added demo 81.

**Comment by choper725** [comment]
thanks !
