### ISSUE TITLE
Demo Z2UI5_CL_APP_DEMO_77 export table to xlsx

### ISSUE THREAD

**Issue by nomssi** [abap2UI5/abap2UI5#477]
In my test, the icon for export is missing (I checked the Demo animated GIF as a reference)

**Comment by choper725** [comment]
the demo is working fine ..
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/b4519dea-f506-44e0-8913-eb344c58e5b7)

whats the problem you have ?

**Comment by nomssi** [comment]
my test in Edge, with the latest release:
![image](https://github.com/abap2UI5/abap2UI5/assets/18452507/252494bd-ec6e-42d0-b091-dcdb54a6bdeb)

**Comment by choper725** [comment]
this is on edge in my end..
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/832b7d1f-db51-4669-b445-d2f7c922e1f4)


are you getting any console errors ??

**Comment by nomssi** [comment]
ah yes...
![image](https://github.com/abap2UI5/abap2UI5/assets/18452507/085d8935-9b71-4a04-8934-1be7a2d2a04e)

**Comment by choper725** [comment]
yor sdk is openui5 ?
try changing it to sapui5

**Comment by nomssi** [comment]
That was the root cause: I changed the SDK and it worked, thank you!

I was think only the demos under "Visualization" would require sapui5. Now I found out the "Planning Calendar" works with openui5 and the Excel Export needs sapui5.
