### ISSUE TITLE
Uncaught ModuleError: failed to load 'sap/ui/core/date/UI5Date.js' in v1.25.1

### ISSUE THREAD

**Issue by WegnerDan** [abap2UI5/abap2UI5#495]
I pulled tag v1.25.1 and get the following error:  

`Uncaught ModuleError: failed to load 'sap/ui/core/date/UI5Date.js' from /sap/public/bc/ui5_ui5/resources/sap/ui/core/date/UI5Date.js: 404`

I commented out this line and it worked again:
https://github.com/abap2UI5/abap2UI5/blob/4de8956b8027024d9cee1813f916e16e0e5e42f0/src/z2ui5_cl_http_handler.clas.abap#L415  

Is this really required?

**Comment by choper725** [comment]
when i messed with the dates, probebly i left that there .. for what i did there,  it can be removed

**Comment by oblomov-dev** [comment]
@choper725 to keep the index.html small i transferred now the date functions on app level to demo 76:
https://github.com/abap2UI5/abap2UI5-samples/blob/43718746682d4d9f136a5b98b1c08daf367f0a84/src/z2ui5_cl_app_demo_76.clas.abap#L66

Then we avoid incompatibilities if lower releases are used. Are your use cases still working with this adjustment?

**Comment by choper725** [comment]
my use cases was the demo 76,
might as well fix the planning calendar also..

if you ask me, date handling should still be there on the on init, as it is an adaption for js date object,
but for your question yes its still working with loading it seperatly..

**Comment by oblomov-dev** [comment]
Yes seems the date is just working from a specific release, have also problems here:
https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/issues/3#issuecomment-1671721064

Maybe later in the future, we can put this back to the index.html when the old UI5 versions are not maintained anymore.

**Comment by choper725** [comment]
the line of require of UI5Date is not needed for the date implementation,

the Date.createObject is generic js,, regardless of UI5Date library.

i think there was a misunderstanding there :)

**Comment by oblomov-dev** [comment]
ah ok thanks fr the information, did not got this.

Maybe it will be helpful for the future to collect some utility functions in the controller e.g. oController.oUtil.oDate for example. Then these functions can be referenced in the xml view definition. Will take a look to this again.

**Comment by choper725** [comment]
if you can reference them in a expression binding that will do the trick

**Comment by oblomov-dev** [comment]
@choper725 ok i checked it again and this is maybe then the better way:

(1) updated the index html with a helper function:
https://github.com/abap2UI5/abap2UI5/blob/ffc3b52533585aa9d1d26ee0bfc5733e8947b18d/src/z2ui5_cl_http_handler.clas.abap#L420
(2) the demo needs then just load the helper function:
https://github.com/abap2UI5/abap2UI5-samples/blob/7c96475c5c86cd4cfa24d96ac94449e97218698a/src/z2ui5_cl_app_demo_76.clas.abap#L90
(3) and then can call the function in expression binding:
https://github.com/abap2UI5/abap2UI5-samples/blob/7c96475c5c86cd4cfa24d96ac94449e97218698a/src/z2ui5_cl_app_demo_76.clas.abap#L116

I have no idea if it makes sense to talk about what is close to the UI5 standard here, but i would say this could be more or less the correct way :)

let me know if this also working for you or if we need more adjustments.

**Comment by choper725** [comment]
ill check it,
whats the purpose of this new _generic_property ? to load custom js?

about sticking to ui5 standard, my two cents are, and thats why im involving in this project is to bridge the gap of an abaper to a ui5 dev.
as i see it, when you came up with this way of serving ui5 from abap, you managed to bring complicated js developing to the “more friendly” abap.
and by this guide line i go, when coming to abap, and especially in a open source project you can make complicated tasks simpler,
if this is simpler ?! i dont really know to be honest

**Comment by oblomov-dev** [comment]
_generic_property is just a method to add properties in a generic way, sometimes helpful to test something without extending the view class. Here i used it to add a new namespace to the view. 

Got the idea from here:
https://sapui5.hana.ondemand.com/sdk/#/topic/b0fb4de7364f4bcbb053a99aa645affe
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/8b0113be-60ee-48ff-b583-b5752c861329">

Thats why i think it could be a good approach for this. Just want to avoid to use global variables, not sure if we run into problems when using abap2UI5 embedded in launchpads or in other contexts. So if this is working for you we can keep it like this.

Yes as simple as possible from the ABAP perspective and trying to be as close as possible to the UI5 standard inside the framework, not always easy to balance but so far i am very surprised that so much more is easily possible (nav container, nested views, message manager etc.) 👍

**Comment by choper725** [comment]
@oblomov-dev 
what is the difference between z2ui5.oController.oUtil and the z2ui5.Helper ??

**Comment by oblomov-dev** [comment]
there is no difference, just naming, but i see i got confused. i corrected it again to:
```abap
 view->_generic_property( VALUE #( n = `core:require` v = `{Helper:'sap/z2ui5/Helper'}` ) ).
```
All functions are now collected under: sap.z2ui5
