### ISSUE TITLE
Uncaught TypeError 

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5#501]
Hi,

when I start example 80 I get the following error:

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/61337774-69e9-4c49-9346-379e15d8e483)

Best Regards
Thomas

**Comment by choper725** [comment]
look at adjustments in #495

**Comment by Th0masMa** [comment]
Hi 
I check the example 76. It ist very easy to change my example 80. Tomorrow i change it.
Thank you all for the Help.

Best Regards
Thomas
