### ISSUE TITLE
Binding Incompatibility with PR 503  - New Tag v.1.25.2

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#512]
Added an incompatibility with PR https://github.com/abap2UI5/abap2UI5/pull/503

Now: 
Variables which are binded with _bind always have to be public attributes of the app class. Otherwise an error is thrown.

Before: 
If _bind was used with a non-public attribute automatically one time binding with the actual value of the variable was made and no error occured.

Check this for an example:
https://github.com/abap2UI5/abap2UI5-samples/blob/131f800419618547488dd0c4af70d36d2176697e/src/z2ui5_cl_app_demo_02.clas.abap#L166

Need the version before this change? 
Use this tag: https://github.com/abap2UI5/abap2UI5/releases/tag/v.1.25.2

**Comment by choper725** [comment]
is something wrong with the binding ??
demo 97 acting weird, but the code seems to be ok..

**Comment by oblomov-dev** [comment]
ah yes thanks for the hint. seems there are still some issues. started to fix it and it is working now but i need to test it more. you can check _dev branch if you need it quickly or use the tag.

**Comment by choper725** [comment]
great. just implementing new features and saw the binding not working correctly

**Comment by oblomov-dev** [comment]
updated the demo 102 with your code and fixed some bugs with the binding.

i can not find any entries with this demo:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/c8dba37a-612b-48ec-8894-0a7d4261a49f">

**Comment by choper725** [comment]
its case sensitive i fell for that also :)

**Comment by oblomov-dev** [comment]
but it is working now on my side:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/ef67a983-ee91-450c-b0da-814903ad831e">

**Comment by oblomov-dev** [comment]
Updated the name of the http handler with the latest commit.

Before:
z2ui5_cl_http_handler

Now:
z2ui5_cl_fw_http_handler

**Comment by choper725** [comment]
> Updated the name of the http handler with the latest commit.
> 
> Before: z2ui5_cl_http_handler
> 
> Now: z2ui5_cl_fw_http_handler

does this changes something ??

**Comment by oblomov-dev** [comment]
no, just adjust your http handler with the new name.

**Comment by choper725** [comment]
manually ? or pulling latest pr ?

**Comment by oblomov-dev** [comment]
Pull latest PR but the call of the http handler is in your custom http handler. There you have to do the adjustment manually.

**Comment by choper725** [comment]
> Pull latest PR but the call of the http handler is in your custom http handler. There you have to do the adjustment manually.

oh thats right !! thanks

**Comment by oblomov-dev** [comment]
btw.
also added the feature that you can now add your own javascript to the index.html (if needed):
https://github.com/abap2UI5/abap2UI5/blob/main/src/z2ui5_cl_fw_http_handler.clas.abap#L18

**Comment by choper725** [comment]
wow !

like creating a function and use it via expression binding ??

**Comment by oblomov-dev** [comment]
yes this is for example an option.

**Comment by choper725** [comment]
@oblomov-dev 
how can we call a function in the custom_js property, from abap and not with expression binding ??

**Comment by oblomov-dev** [comment]
You can call it for example like this:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/54b388c5-36dd-416c-86f1-bf025045106e">

<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/25dfc0b1-fc4c-41b3-a7f1-378453e17ff1">

**Comment by choper725** [comment]
Great! thx !

**Comment by oblomov-dev** [comment]
yep it is added now.

**Comment by choper725** [comment]
seems not to work when trying to call it in a popup
see demo..
[demo_90.txt](https://github.com/abap2UI5/abap2UI5/files/12569865/demo_90.txt)


im trying to implement P13N.POPUP control.. (the new one)
but the data loading is from js only..

this is what i inserted into custom_js function in the handler..
[custom_js.txt](https://github.com/abap2UI5/abap2UI5/files/12569869/custom_js.txt)

**Comment by oblomov-dev** [comment]
Just took a look to the source code without starting it, but maybe the following helps:

It looks like you want to reference UI5 objects in your new method, but you call this method during rendering and i think it is to early because the ui5 controls are not created at this time. You can call this method with a timeout just to see if it is working then. Or what is your error message?

Why are you not creating a custom control to fill the p13n data with JS like you did with the spreadsheet for example?

**Comment by choper725** [comment]
well i think custom control is a bit overkill for this scenario.

i didnt say the the zcc_plain_xml line was workibg and triggering the js code once inserted in main xml view and not a fragment.

i liked the approach you said triggering it with timeout,
how i do that? as far as i understand i need somekind of view to trigger a js function no?

**Comment by oblomov-dev** [comment]
Ah ok it is just not working in a fragment? Then my guess was wrong. Can you also give me the working snippet when you put it into the main view? Then I can compare both and check if I find something.

**Comment by choper725** [comment]
its just to change to view type from view to popup..
ill send it later today,
but i think this still will not work as the zcc_plain_xml trigger the js function before the popupview is loaded, like you mentioned before.
as in the js function i need to get the object byId from the popupview

**Comment by oblomov-dev** [comment]
@choper725 create a new issue for your problem, i will close this one, that the topics don't get mixed.
