### ISSUE TITLE
t_draft error

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#530]
hi @oblomov-dev 

i started to encounter problems with exception of no entry of previous request found in draft table.

to reproduce it it open two demos on two seperate tabs in the browser and in one of them press back or even triggering an event

**Comment by oblomov-dev** [comment]
how can i reproduce it? Start a demo via direct url and then trigger an event?

Two in separated tabs should make no difference, they get unique IDs with every request.

**Comment by choper725** [comment]
start two demos not from direct url and then trigger event in one and then go to the other tab and trigger event in the second one

**Comment by oblomov-dev** [comment]
mhh i do not get the error 🤷‍♂️ 
opened two tabs and started the launchpad on both.
Then pressed continue, and started the same demo in both tabs.
Then triggered an event in one tab and did the same in the other one, but it works fine.

**Comment by choper725** [comment]
hi @oblomov-dev 

check this video of it i did,

i opened a direct link url in one tab and the launchpad in another...

https://share.vidyard.com/watch/32ScgNdS2Nmr6UWh6eekvf?
