### ISSUE TITLE
url steing gets cut off when using open in new tab

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#531]
hi @oblomov-dev 

it seems that rhe url string im sending to the open new tab method gets cut off along the way,
and in the browser it appears to be cut,

im passing 740 chars long string to it.

edit:

the url got url parameters, and at the first occurence of the char ‘,’ (comma) the string is getting cut off and sent to window.open method..

**Comment by oblomov-dev** [comment]
can you send me an example url that i can reproduce the error?

**Comment by choper725** [comment]
[demo open new tab.txt](https://github.com/abap2UI5/abap2UI5/files/12542702/demo.open.new.tab.txt)

here it is,

the url is
https://www.google.com/search?q=abap2ui5&oq=abap2ui5,123

what opens in browser is
https://www.google.com/search?q=abap2ui5&oq=abap2ui5

**Comment by oblomov-dev** [comment]
Added a small correction, you can check again.

**Comment by choper725** [comment]
fixed, thanks !
