### ISSUE TITLE
third column in flexible column layout

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#538]
hi @oblomov-dev 
in order to utlize the thired column in (master-detail-detail layout)
another nested view is needed, 
once the the detail page go to detail-detail page, the mid column gets deleted, ill do a simple demo on it, if im not clear enough

**Comment by oblomov-dev** [comment]
hi @choper725, a demo would be great to have an example for testing. 

Do you think two nested views are enough for all use cases or are there layouts where more is needed? Not sure if just adding another method is the best way or maybe working with t_nested_views. Will check this.

**Comment by choper725** [comment]
well  currently i dont know any other layout that manage is own seperate views which not defined in xml directly,
i think a third view will solve it, currently i think a generic approach using t_nested_views might be too much, for the current use cases

**Comment by choper725** [comment]
here is a small demo based on demo 97,
its pretty clunky as it refreshes the view again in order to show that only one nested view can be displayed due to only one view and controller..

just press the navigation arrow in the table to goto third column,
then to go back just select another row in the list of column 1 view..

[demo_97.txt](https://github.com/abap2UI5/abap2UI5/files/12566458/demo_97.txt)

**Comment by oblomov-dev** [comment]
Thank you. Added now this demo to the repository 0098 and added also nested_view2 functionality.
It seems to work:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/190d3cca-838c-4f39-95c3-18ab20871255">

**Comment by choper725** [comment]
thanks, ill check this, should work with the new view parameter for binding right?

**Comment by oblomov-dev** [comment]
Yes it should work, if you run into problems use demo 98 to reproduce the error and let me know.

**Comment by choper725** [comment]
working ! thx !!
