### ISSUE TITLE
zcc_plain_xml in popup

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#544]
Hi @oblomov-dev 
reopening the issue of using zcc_plain_xml along with custom_js in handler..

im trying to implement p13n.popup
https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.p13n.Popup/sample/sap.m.sample.p13n.Popup/code

when calling zcc_plain_xml in popup im getting an error
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/1dfa316b-2709-4f83-bcd6-ecff995034e4)

here is the demo
[DEMO 90 POPUP.txt](https://github.com/abap2UI5/abap2UI5/files/12578095/DEMO.90.POPUP.txt)

here is relevant custom_js script (which can be inserted in zcc_plain_xml method also iguess).
[custom_js.txt](https://github.com/abap2UI5/abap2UI5/files/12578110/custom_js.txt)

also, the zcc_xml_plain is working when used not in popup (same custom_js script)
see demo
[DEMO 90 MAIN VIEW.txt](https://github.com/abap2UI5/abap2UI5/files/12578124/DEMO.90.MAIN.VIEW.txt)

as suggested earlier, a custom control is maybe too much at this point for it..
but might worth taking a look at when trying to implement p13n + variant managment, using p13n.engine..

i do liked your idea of calling the js function with a timer, but i cant seem to find a way to do so without a xml view attached to the call...
there is a generic way, of the client to run a js command ? outside of a view ?

EDIT:
after fiddling around with it, i found that even if it will work in  a popup, the data used to keys of the json binded to the p13n.popup must be in lowercase,
[p13n Work.txt](https://github.com/abap2UI5/abap2UI5/files/12578972/p13n.Work.txt)

here is a working case (not in popup) but data is not showed there..

messing around with demo for it in the sdk i found that upper case keys in the binded json is the issue for it

again, thanks for the help, 
cheers choper725

**Comment by choper725** [comment]
hi @oblomov-dev 
well using it in xml view class could work, but zcc_plain_xml seems to not work in a popup..

**Comment by choper725** [comment]
yes right, try loading it before the popup,
but i guess im digging deeper into it, probebly will not work eventually because of uppercase keys in the model :/

**Comment by choper725** [comment]
@oblomov-dev can you please point me to the section where the keys get assigned in the binding code ? i want to test i got it fully working on my side..

**Comment by oblomov-dev** [comment]
check the area here:
https://github.com/abap2UI5/abap2UI5/blob/main/src/00/z2ui5_cl_fw_binding.clas.abap#L151

normally the abap variable name is used, and in case it is too long it is switched to an uuid.

**Comment by choper725** [comment]
hi @oblomov-dev 

managed to get it working with your tips :)
[DEMO 90 POPUP.txt](https://github.com/abap2UI5/abap2UI5/files/12623956/DEMO.90.POPUP.txt)

unfortunately this is not working with uppercase keys in the binded table,
managed to get it to work by adding pretty_name = 'L' to function trans_json_any_2.

so i figured, is it possible to make a new parameter in _bind and _bind_edit that indicates the pretty_name to the trans_json_any_2 function ?

**Comment by oblomov-dev** [comment]
hi @choper725,
thank you for the work, i will take a look to it. Can you share a few screenshots that i can see what you exactly changed in the source code?
Best regards.

**Comment by choper725** [comment]
hi @oblomov-dev 
what i changed in order for it to work was:

1.add optional parameter named PN to function trans_json_any_2 in class Z2UI5_CL_FW_UTILITY
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/04e348d8-4f08-4c30-966d-282685b7cba7)
'
2. i hardcoded the lowercase creation of keys in binding process by add the PN parameter in the method  main_set_frontend of class Z2UI5_CL_FW_MODEL. here
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/b238fb3a-6941-4d50-a9b2-f0e6ee90a1c7)

**Comment by oblomov-dev** [comment]
Thank you! yes i see... very strange that uppercase is not working in a popup....

I added not the changes, you can check the branch _dev and see if this is working for you.

Yes extending the binding method is one option, but to keep it simple maybe it is the better way to just go with lowercase letters with tables all the time. But this needs some refactoring for all apps which are already in use, which is also not perfect. I need to check this again.

**Comment by choper725** [comment]
i think the the case issue is only on p13n control, its not a global issue,

hence i dont think refactoring everything is worth it,

maybe just passing parameter to use lowercase keys in the binding method is an option.

this change i mentioned above breaks all demos.. which are working fine without it, its just this p13n control

**Comment by oblomov-dev** [comment]
Ok yes this could be the right way, also because in ABAP normally everything is upper case.

I added now an optional importing parameter to the binding methods _bind, _bind_edit, _bind_local. You can check branch _dev and test if it is working for p13n.

Best regards.

**Comment by choper725** [comment]
great! ill check it

btw, its worth removing the to_lower in name_front parameter in cl_fw_binding as the table case is irrelevant for that scenario

**Comment by oblomov-dev** [comment]
ah yes i forget to delete this again, it was just a test. updated it again.

**Comment by choper725** [comment]
hi @oblomov-dev 

work as expected!

but still zcc_plain_xml method not working in a popup display

**Comment by oblomov-dev** [comment]
What is exactly not working? When you send JavaScript with plain_xml? Maybe you better send the functions with the main view and then call immediately (with a second request) the popup.

**Comment by choper725** [comment]
when you use zcc_plain_xml in a popup display you get this error 

![](https://user-images.githubusercontent.com/129428114/267074967-1dfa316b-2709-4f83-bcd6-ecff995034e4.png)

pointing to the controller in the ofragment definition on the json model creation.

the use cases for it is not only js but also css on in the popup..

im not sure if using css or js in the main view will work when calling from popup tbh..

**Comment by oblomov-dev** [comment]
I am also not completly sure, but i think it should not matter where you define the JS and CSS. You could also do this in the index.html and later use it in your xml popups or normal views.

But when this is not working, feel free to share your demo with the error again, then i can try to take a look.

**Comment by oblomov-dev** [comment]
this issue got big. lets continue here https://github.com/abap2UI5/abap2UI5/issues/698 
and for any other questions just open a new issue.
