### ISSUE TITLE
One button can be clicked multiple times

### ISSUE THREAD

**Issue by Hhpy410** [abap2UI5/abap2UI5#546]
HI, oblomov-dev
how do i show the BusyIndicator
when click a button before server event 

https://github.com/abap2UI5/abap2UI5/assets/38339002/3b32e72f-c94e-4585-871e-7c7f60cd0fcf

**Comment by oblomov-dev** [comment]
hi @Hhpy410 
ah yes, the busy indicator has a certain delay, therefore i implemented an additional one and added an extra check that only one request at a time can be send to the server. https://github.com/abap2UI5/abap2UI5/pull/547

you can check again.
