### ISSUE TITLE
Nested View - Table SELKZ binding issue

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#553]
Hi,
I'm using the nested view approach.
In the nested view I implemented a sap.m.table table control single selection mode like in demo "Z2UI5_CL_DEMO_APP_019".
Unfortunately, the value for SELKZ (column_list_item( selected = '{SELKZ}') isn't forwarded to the app variable anymore.
This was working for release 1.25.2.

I tried to add the new parameter "VIEW" to the _BIND_EDIT method like explained in issue #506 
[(https://github.com/abap2UI5/abap2UI5/issues/506#issuecomment-1704984625)]

That didn't help either...

**Comment by oblomov-dev** [comment]
Mhh, can you share the code of the app that i can reproduce the error?

In my test it is working, but maybe i overlook something:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/777d2eb1-aa23-4fa8-bda3-6b74acfdcd0e">

**Comment by axelmohnen** [comment]
It took me a while to build up a working example.
The example is a mix of demo 19 and 65.

How to reproduce the issue:
Not working:
1.1) Select on record in table of nested view
1.2) Press the "copy selected entries" pushbutton on the "nested" View
1.3) Toast Message: "Line not selected"

Working:
2.1) Select on record in table of nested view
2.2) Press the "copy selected entries" pushbutton on the "main" View"
2.3) Toast Message: "Line selected"

Outcome:
It seems when the event gets triggered in the main view it works, but when the event gets triggered in the nested view the binding doesn't work.

[ZAMOH_CL_DEMO_APP_019_065.txt](https://github.com/abap2UI5/abap2UI5/files/12672636/ZAMOH_CL_DEMO_APP_019_065.txt)

**Comment by oblomov-dev** [comment]
Thank you for the demo, this is a great help to find the error quickly. Yes the nested views are a bit more complex. I made a small fix to abap2UI5. And additionally slightly adjusted your demo. You have to specify the view for the binding.
[demo_update.txt](https://github.com/abap2UI5/abap2UI5/files/12673910/demo_update.txt)

You can give it a try again and let me know if it works for you.

Best regards.

**Comment by oblomov-dev** [comment]
Does specifying the view in the binding maybe also solve this problem after the abap2UI5 update now?
https://github.com/abap2UI5/abap2UI5/issues/550?notification_referrer_id=NT_kwDOBhln57Q3NzY3NjQyMDk2OjEwMjMyODI5NQ#issuecomment-1727042518

**Comment by axelmohnen** [comment]
@oblomov-dev ,
thanks a lot for the quick fix.
The fix seems to work for my demo.
[[demo_update.txt](https://github.com/abap2UI5/abap2UI5/files/12673910/demo_update.txt)]

Unfortunately, I implemented the your latest changes in our system (before v1.30), but now the FLP integration failed with an XML parsing error:
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/da6f4a9a-f93a-49f1-be73-fbac9b0928b2)
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/53f7ffbc-e0f3-4a63-a94c-2c972d706282)

**Comment by oblomov-dev** [comment]
So with v.1.30 it is working, but with the actual version not?

**Comment by oblomov-dev** [comment]
I get problems with the latest changes of the ShellUIService:
<img width="1380" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/c84a581e-98e7-4e45-b9e5-988a4ce0e0d2">

Can you share the full snippet of your manifest.json and your View1.controller.js? Maybe i missed something.

**Comment by axelmohnen** [comment]
maybe the "Service" tag is missing in your manifest:
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/d4522db0-4076-4d6e-b744-7e571333c120)

[View1_controller.txt](https://github.com/abap2UI5/abap2UI5/files/12681770/View1_controller.txt)
[manifest.txt](https://github.com/abap2UI5/abap2UI5/files/12681772/manifest.txt)

**Comment by oblomov-dev** [comment]
Ok thank you, needed to update the Launchpad repository again. Somehow the ushell service is not available on my system. I made loading of this optional now.

I can reproduce the error now, 1.30 is working, newer not. I will check this later again.

**Comment by oblomov-dev** [comment]
updated the repository again, in my tests it is working, you can try again.
