### ISSUE TITLE
demo 109 popover issue

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#563]
hi @oblomov-dev 
in the new demo 109 for quick popover, i have an issue when trying to open the popover a **second** time..
something no working properly there, cant seem to figure out where..
i got  a guess maybe it got to do something with the event of closing of the popover maybe ?

**Comment by oblomov-dev** [comment]
thanks for the example, added a small fix, you can try again.
https://github.com/abap2UI5/abap2UI5/pull/559

**Comment by choper725** [comment]
seems to work, but something is weird, the popover stay open on the second time as long as i keep the mouse button pressed...

**Comment by oblomov-dev** [comment]
added a small fix. works better on my side now, you can test again.
https://github.com/abap2UI5/abap2UI5/pull/567
