### ISSUE TITLE
demo 77 + 75 error in custom control loading

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#565]
hi @oblomov-dev 

getting errors in console and demos not working..
file uploader and xlsx download

![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/23a48126-1f30-4537-9f95-ff2f2696585a)

![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/849a9610-5cb4-4a32-8bf4-dfda9ef477ec)

thanks !
cheers, choper725,

**Comment by oblomov-dev** [comment]
Both working fine on my side. Did you switch the library from open ui5 to normal ui5?

Used a normal text for upload:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/caac7a5d-0a93-47d4-9bc4-019bdcd1cb3f">

And xlsx export:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/238fa979-54b0-4ef9-a209-ab5b751f91e0">

**Comment by choper725** [comment]
i dont remember changing it but ill check..

**Comment by choper725** [comment]
checked the url, seems to be sapui5..

still getting the same error..

**Comment by oblomov-dev** [comment]
Can you switch the sap ui5 version to a lower or higher release? Just to check if something in the ui5 sdk changed which creates the error.

**Comment by choper725** [comment]
seems to be something on my end ..
sorry for the trouble..
