### ISSUE TITLE
Nested View: Popover doesn't work

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#570]
Hi,
The popover control doesn't work inside a nested view.
Error message in the browser's console:
_**TypeError: Cannot read properties of undefined (reading 'getDomRef')**_

Please have a look to the attached demo app.
[ZAMOH_CL_DEMO_APP_POPOVER.txt](https://github.com/abap2UI5/abap2UI5/files/12734913/ZAMOH_CL_DEMO_APP_POPOVER.txt)

Thanks a lot in advance.
Kind regards
Axel

**Comment by oblomov-dev** [comment]
added a small fix:
https://github.com/abap2UI5/abap2UI5/pull/571

now it works on my side:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/3e41dbbe-cc88-46de-88ee-c163fa72348d">

**Comment by choper725** [comment]
@oblomov-dev 
might worth adding logic for viewnest2 to avoid future errors

**Comment by axelmohnen** [comment]
Hi @oblomov-dev,
Yes, it works for me as well.
Thanks a a lot!

**Comment by oblomov-dev** [comment]
@choper725 good point! added it also for nested view2 now.

**Comment by axelmohnen** [comment]
Issue has been solved. I will close it.
Thanks!
