### ISSUE TITLE
question about t_draft

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#574]
hi @oblomov-dev 

as part of @axelmohnen great SH control,
and in general once a app call another app (class) 
how can we return to the last state of the calling app.?
in the SH demo i see that the entire first app is rerendered again once the value return from the SH popup to the input field.

is it possible to just return to the last state of the app without rerendering ??

**Comment by oblomov-dev** [comment]
you can use the method nav_app_leave to jump to a specific state, for example:
```abap
client->nav_app_leave( client->get_app( client->get( )-s_draft-id_prev_app_stack ) ).
```
id_prev_app_stack gives you the calling app, but you can also use different IDs:
<img width="232" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/21dfc12c-b8ad-442e-b5fb-d2f4e83c2dd1">

Does this help you?

**Comment by choper725** [comment]
well i think i narrowed down the issue,
you right this way of moveing bettween classes do work but there is an issue with z2ui5_cl_tool_app_09,
once i remove the re render and replace it with view_model_update,
it seems that EDIT parameter is getting cleared from all the binded variables.
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/d5693d8e-6d9d-4f4f-ad73-2c15a860b68e)


before calling the SH: (from the 09 demo)
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/e55eeeaa-10aa-4d65-94be-437e1d4b2c8f)
the EDIT parameter got the binded variable ms_screen_partner.


after the value is returened from the SH
it gets printed with toast message but the EDIT parameter is cleared..
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/ca1df29c-b6a5-462e-a232-822c3207dea6)


well, i dont know if thats the expected behavior or not, but it seems thats the reason why only rerendering works.. and not only updating the model

**Comment by oblomov-dev** [comment]
Checked it and yes got the same problem, seems there was a bug in abap2UI5, fixed it with:
https://github.com/abap2UI5/abap2UI5/pull/576

Thanks for finding the issue, you can try again.

**Comment by choper725** [comment]
thanks ill check it !!

**Comment by choper725** [comment]
works as expected ! thanks @oblomov-dev
