### ISSUE TITLE
SmartFilterBar - metadata

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#577]
Hi,

I like to implement the SmartFilterBar (sap.ui.comp.smartfilterbar.SmartFilterBar) instead of FilterBar (sap.ui.comp.filterbar.FilterBar).
The "FilterBar" control works fine, but I like to profit from the smartfilterbar "Recent history" feature.
[https://sapui5.hana.ondemand.com/sdk/#/topic/37dbf1f30127420d9c585bc1ad80086b.html](url)

This feature is integrated in the SAP Fiori launchpad and available for SmartFilterBar fields.

The problem:
The SmartFilterBar control expects a "Entityset" or "EnitityType" as metadata field description.
Do you know how to bind such a parameter in ABAP2UI5?

Thanks a lot in advance.
Kr Axel

**Comment by axelmohnen** [comment]
Hi,
an other option could be to "rebuild" the recent history feature by using the class /UI2/CL_PERS_CONTAINER_ACCESS.
This class handles the access to the FLP users personalization configuration tables "/UI2/CONTAINER" and "/UI2/ITEM".
The history will be displayed in the input field via "suggestionItems".

**Comment by oblomov-dev** [comment]
Hi @axelmohnen,

unfortunately the smart controls are not really fitting to the abap2UI5 concept. Smart controls are build on top of normal UI5 controls e.g.:
Smart Filter Bar is on top of the FilterBar.

That means that UI5/Fiori Elements gets (1) Metadata from the Backend and then (2) the UI5 Controls are dynamically generated. In the Backend you can define the metadata via Annotations. Therefore you always need an OData Service which generates the UI for this, and we can not really adapt this in abap2UI5 (we are always sending the final UI5 View).

But as you said in your second answer:
You can try to build everything manually and try to find the methods which the smart controls are calling. If it is somehow working with the classes you mention we can call them and send the values to the backend and build a table with suggestion items out of it.

Feel free to give it a try. I never really used the launchpad, so I can not share more knowledge here, but if you find the calls you need I can check where we can add them to abap2UI5.

**Comment by oblomov-dev** [comment]
i close this one just reopen it if you have further questions.
