### ISSUE TITLE
multiinput does not handle remove tokens event

### ISSUE THREAD

**Issue by ssocratous71** [abap2UI5/abap2UI5#578]
Using multiinput can add token with the submit event. When removing tokents the tokenupdate event does not handle correctly the remove.(no index or other data to find out what was removed.

**Comment by oblomov-dev** [comment]
@ssocratous71 is this solved with https://github.com/abap2UI5/abap2UI5/issues/406 ?

**Comment by oblomov-dev** [comment]
continue with https://github.com/abap2UI5/abap2UI5/issues/406 and i close this one
