### ISSUE TITLE
Sample Z2UI5_CL_DEMO_APP_058 changing the layout is not working - Binding-Methods

### ISSUE THREAD

**Issue by CalvinwithHobbes** [abap2UI5/abap2UI5#580]
Hi together,
with the newer release of abap2ui5 the sample **Z2UI5_CL_DEMO_APP_058** changing the layout is not working anymore.
I got the error:

**500 Internal Server Error
BINDING_ERROR - No class attribute for binding found - Please check if the binded values are public attributes of your class**

even though the values are public attriubutes.

The problem are the newer versions of the **_bind**- and **_bind_edit**-methods within the method **z2ui5_on_render_popup** of this samle coding. The binding-methods do not get along with 

**VAL =  VALUE ty_t_combo( ( key  ...**

like:
```
               ...
               )->combobox(
                   selectedkey = client->_bind_edit( ms_layout-selmode )
                   items       = client->_bind( VALUE ty_t_combo(
                       ( key = 'None'  text = 'None' )
                       ( key = 'SingleSelect' text = 'SingleSelect' )
                       ( key = 'SingleSelectLeft' text = 'SingleSelectLeft' )
                       ( key = 'MultiSelect'  text = 'MultiSelect' ) ) )
                   )->item(
                       key = '{KEY}'
                ...
```
Instead one has to change the coding 
```
             ...
               )->combobox(
                   selectedkey = client->_bind_edit( ms_layout-selmode )
                   items       = client->_bind( mt_combo )
                   )->item(
                       key = '{KEY}'
              ...
```
 and declare an mt_combo table and fill it in the z2ui5_on_init-method.

Same when transfering values with a declaration of a table within a structure:  VAL = ms_layout-t_cols ...

```
              ...
              )->table(
                   items = client->_bind_edit( ms_layout-t_cols )
              )->columns(
                   )->column( )->text( 'Visible' )->get_parent(
               ...
```

I declared a new table mt_cols and filled it with the data from ms_layout-t_cols.

```
      ...
       )->table(
        items = client->_bind_edit( mt_cols )
        )->columns(
            )->column( )->text( 'Visible' )->get_parent(
      ...
```

Anyhow I don't really understand why? I didn't find the reason in class Z2UI5_CL_FW_CLIENT.

Find attached my working coding of the class 058.
[class z2ui5_cl_demo_app_058.txt](https://github.com/abap2UI5/abap2UI5/files/12856356/class.z2ui5_cl_demo_app_058.txt)

Regards 
Calvin

**Comment by oblomov-dev** [comment]
hi @CalvinwithHobbes,

yes I adjusted the binding logic with version 1.30 and higher. Unfortunately there is a small incompatibility when you use local variables. You have to use the method bind_local now, then you can also use the former version with:
```abap
client->_bind_local( VALUE ty_t_combo(
                       ( key = 'None'  text = 'None' )
                       ( key = 'SingleSelect' text = 'SingleSelect' )
                       ( key = 'SingleSelectLeft' text = 'SingleSelectLeft' )
                       ( key = 'MultiSelect'  text = 'MultiSelect' ) ) )
```

I will fix the class later.

Best regards.

**Comment by oblomov-dev** [comment]
fixed now with:
[m/abap2UI5/abap2UI5-samples/commit/2849c2bd0c00cc7a6e4db923c5c1b6ad1c41eb6c](https://github.com/abap2UI5/abap2UI5-samples/commit/2849c2bd0c00cc7a6e4db923c5c1b6ad1c41eb6c)

**Comment by oblomov-dev** [comment]
i close this issue, just open a new one if you run into further problems
