### ISSUE TITLE
Download table to Excel or CSV

### ISSUE THREAD

**Issue by ssocratous71** [abap2UI5/abap2UI5#594]
I had try to use the example for downloading a table to excel and the button at the toolbar does not appear. I had check the Demo (CLASS Z2UI5_CL_DEMO_APP_077) and the problem is also there. Inspecting the app you can see errors in loading the javascripts ( -> 'sap/ui/export/Spreadsheet.js': failed to load 'sap/ui/export/Spreadsheet.js' from https://sdk.openui5.org/resources/~202310020939~/sap/ui/export/Spreadsheet.js: Failed to  ... Log-dbg.js:493  2023-10-23 12:14:50.269600 Control 'z2ui5.ExportSpreadsheet' did not return a class definition from sap.ui.define. -  XMLTemplateProcessor
u @ Log-dbg.js:493
Log-dbg.js:493  2023-10-23 12:14:50.269600 Can't find object class 'z2ui5.ExportSpreadsheet' for XML-view -  XMLTemplateProcessor.)

Then I try to do the one with downloading a csv file. It works, but it does not support UTF8 characters. I try first encoding the string to UTF and hen to BASE64 but without success. Can you recommend a way to download a table in Excel or csv that supports UTF8?

Regards,

S.Socratous

**Comment by oblomov-dev** [comment]
HI @ssocratous71,

do you use openui5 in the bootstrapping? The spreadsheet is not part of OpenUI library, therefore i recommend to change the ui5 bootstrapping.

How did you try to change the encoding? Did you use the functions recommended here before creating the base64:
https://stackoverflow.com/questions/60133415/how-to-encode-a-string-variable-into-a-given-code-page

Best regards.

**Comment by ssocratous71** [comment]
I use similar conversions (CALL METHOD ('CL_WEB_HTTP_UTILITY')=>encode_utf8) but this produces an xstring. If I use then 
encode_x_base64 again I do not get the original characters back.

**Comment by ssocratous71** [comment]
I also try from the utilities class the following:
    DATA(xstr) = lcl_utility=>get_xstring_by_string( val ).
    result = lcl_utility=>encode_x_base64( xstr ).
    
    but still get invalid characters except number and English.

Is there something that need to be added to :
view->zcc_plain_xml( `<html:iframe src="data:text/csv;base64,` && lv_base64 && `" hidden="hidden" />`).

Any help will be appreciated.

NOTE: the same routines for uploading a csv file (with greek characters) works fine.

**Comment by oblomov-dev** [comment]
Is this working on your side?

```abap
    data(lv_result) = `my test`.
    data(lv_x) = cl_http_utility=>encode_utf8( lv_result ).
    DATA(lv_frontend) = cl_http_utility=>encode_x_base64( unencoded = lv_x ).

    "send it to the frontend here...

    DATA(lv_x2) = cl_http_utility=>decode_x_base64( encoded = lv_frontend ).
    DATA(lv_result2) = cl_http_utility=>decode_utf8( encoded = lv_x2 ).

    assert lv_result = lv_result2.
```
Yes maybe on the way to the frontend something gets broken... 🤔

**Comment by ssocratous71** [comment]
I get the original text back by using encode_utf8 encode_x_base64 and then reverse with  decode_x_base64 and decode_utf8. Everything is ok. But when sending it to the frontend as an iframe to get downloaded, it seems something does not work as expected. I will continue trying different methods, but downloading files seems to not work properly.

**Comment by oblomov-dev** [comment]
Yes then its definitely on the way to the frontend. Try different methods out sounds good, i have also no concrete solution yet and would do the same. Maybe you can change the iframe settings, or set encoding in the request response or check the ajax response in chrome.... 
If you find something out, let me know that I can take a deeper look or adjust the code of abap2UI5.

**Comment by ssocratous71** [comment]
I have changed thee codepage in the local utility class and it seems to work ok now!!!!
Thanks for the help.        

CALL METHOD ('CL_ABAP_CONV_CODEPAGE')=>create_out
          EXPORTING
            CODEPAGE = 'windows-1253'
          RECEIVING
            instance = conv.

**Comment by oblomov-dev** [comment]
👍

**Comment by oblomov-dev** [comment]
i close this issue, if you have further problems open a new one
