### ISSUE TITLE
Binding Error with Popup (Message Manager) and <!DOCTYPE html>

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#596]
@choper725 you added with:
https://github.com/abap2UI5/abap2UI5/commit/56be32c4c77fab62765c7ed1a212e6912cf22845
To the index.html:
<img width="300" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/868e20e9-52ec-41fb-a020-961ffcf2e259">

I see that this is per default set in every UI5 app, so its of course the right way, but i get the following binding error in the message manager popup. As for as I remember you did something in this direction and also had problems with the binding. You have a guess what is happening here and how to solve this?

Demo: **z2ui5_cl_demo_app_038**
The actual version of abap2UI5 does not show entries in the popup (press Messages Button up left):
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/6239e2e0-28c8-4117-bfa2-691d1cb3a02a">

But when I comment out the doctype:
<img width="300" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/126295f7-992f-406a-ad42-fb253becf0fe">
It is working again:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/a3016bde-130f-4111-82b9-3b74fb8cc014">

I also tried to create the binding with lower case, but this does not cchange something... 🤷‍♂️

Thanks for any idea.

Best regards.

**Comment by choper725** [comment]
ill take a look at it, as i recall i got an app running with message manager control currently (with doctype).
if i remember correctly i worked on messgae popover control..

**Comment by oblomov-dev** [comment]
thank you. yes messagepopover works fine, also when you put it on the main screen, but only message manager in the popup is not working.

**Comment by choper725** [comment]
well, i also have no idea what thats not working with the doctype,
also i got nothing in the console,
also tried to use a lower version of sapui5 sdk, also not seem to work..

the reason i used doctype was in order to make RichTextEditor working as its a requesite for it..
but in comparison of the two control, the message view is alot more common than RTE.
i guess its worth commenting that out for now...

its wierd.. as anything else works perfectly in a dialog besides this control.. 

ps: (non related)
i get an error in console regarding the cloudflare cdn
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/d9b1304e-6d24-4239-90ac-03d910070a89)

**Comment by oblomov-dev** [comment]
Ok thanks for checking this!
Yes but every app per default is generated with doctype so it hink it is correct keeping it. Also the popup is not working for 2 months and no one created an issue, i think the normal use case is to show it as a message popover. maybe a bug with ui5 in a popup. i think the best way is to just delete the popup from the demos.

yes i check the cloudflare message, still working in this area at the moment thanks.

**Comment by choper725** [comment]
> Ok thanks for checking this! Yes but every app per default is generated with doctype so it hink it is correct keeping it. Also the popup is not working for 2 months and no one created an issue, i think the normal use case is to show it as a message popover. maybe a bug with ui5 in a popup. i think the best way is to just delete the popup from the demos.
> 
> yes i check the cloudflare message, still working in this area at the moment thanks.

ok,

a dot is missing there at the cdn

**Comment by oblomov-dev** [comment]
thanks, fixed with the latest update.
