### ISSUE TITLE
error in demo 102, bwipjs

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#602]
Hi @oblomov-dev 
just after pressing Show Barcode
getting:
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/7149f5e1-15c4-4a06-8922-cad11ede24e6)

and
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/1c18a1d5-ded0-41b5-8c67-22366ae5c58a)

**Comment by oblomov-dev** [comment]
ah yes, this demo is still under construction, will fix this in the upcoming days. thanks for the hint.

**Comment by oblomov-dev** [comment]
made some updates, it works now on my side

**Comment by choper725** [comment]
not working on my end
getting an error here

![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/5112f838-eab8-42f7-9f12-9127fb35b825)

here, on the marked line
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/b1e019a4-412c-49d4-80d3-ba664e1145d7)

**Comment by oblomov-dev** [comment]
ah i see, added again a fix. you can try again.

**Comment by choper725** [comment]
still error on the same line
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/4ecaeae8-e580-4869-87cc-499d4e158430)

**Comment by oblomov-dev** [comment]
oh forgot to update the main repo, you can try again

**Comment by choper725** [comment]
works !
