### ISSUE TITLE
error in xml_view class

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#611]
hi @oblomov-dev 
var mv_name was already declared

![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/fd68b451-a149-46c9-bf1c-e442521c0e43)

**Comment by oblomov-dev** [comment]
mhh checked this again, but i can activate the view without problems. mv_name is also declared just a single time:
<img width="666" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/af3e4cf1-bcad-417e-9c5c-46170283e0be">

Maybe you can copy&paste the code and try again?

**Comment by choper725** [comment]
for some reason mv name & root & parent & root … is declared inthe public section and in private section..
