### ISSUE TITLE
Sample in Cloud ABAP Trial  - Error Icon

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5#627]
Hey,

When I start the demo in the cloud via the HTTP service, I get the following error:

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/875301b8-7959-4cc3-9faf-feec6e823269)

If I call the URL directly, I get the following error:

![image](https://github.com/abap2UI5/abap2UI5/assets/64013300/9f3c5234-5a76-4d7f-82bd-fed461e759f1)

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
Do you only get this problem in abap cloud or in on-premise too?

Can you find out which UI5 control exactly needs the favicon.ico? Do normal UI5 apps have the same problem?

Not sure if this is an abap2UI5 problem or a problem with UI5 or the library in general.

**Comment by Th0masMa** [comment]
I reinstalled the source code.

**Comment by oblomov-dev** [comment]
ok great, i close this one, just open a new issue if there are further problems.
