### ISSUE TITLE
demo 119 not working

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#629]
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/a1a6f0bc-88e6-46b4-ae3b-992fee92110c)

demo 119, 109,21..

popups & popover not working.
demos with html:script,
some formal ns declarations not working such as in demo 88 line ->")->header( ns = `tnt`"

i see the constructor of in xml view is changed..

**Comment by axelmohnen** [comment]
Same issue for me. 
Must be linked to the latest updates.

**Comment by oblomov-dev** [comment]
I adjusted the xml view generation that only namespaces which are in use are transferred, to keep the payload small. Most demos are fixed now, still some work to do...

**Comment by choper725** [comment]
let me know if help needed
