### ISSUE TITLE
Generic DDIC searchhelp generator is not working 

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#633]
Hi,
since the latest changes the generic DDIC searchhelp generator "Z2UI5_CL_TOOL_APP_SHLP_GEN" isn't working anymore.
Example: Z2UI5_CL_TOOL_APP_09
The dialog doesn't open at all.
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/0ef1bc16-7d3e-425b-b112-19516dfebc89)

Could this be linked to the new namespace approach?

Thanks a lot in advance.
Kind regards
Axel

**Comment by oblomov-dev** [comment]
fixed now with https://github.com/abap2UI5/abap2UI5/pull/635

**Comment by axelmohnen** [comment]
Hi @oblomov-dev,
Great, it works again!
Thanks again for the genius support :-)
Issue can be closed.
