### ISSUE TITLE
Visualization Demos - Error not available with openui5 library

### ISSUE THREAD

**Issue by ssocratous71** [abap2UI5/abap2UI5#634]
Hi,
  when trying out the visualization demos I get an error 'Charts are not avalaible with OpenUI5, change your UI5 library first'.
How to change library (if possible) or is it something wrong with the installation?

**Comment by oblomov-dev** [comment]
You need to change the bootstrapping, you can check the information in the FAQ:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/faq.md#2-how-to-change-the-bootstrapping-of-ui5

**Comment by ssocratous71** [comment]
Have change HANDLE_REQUEST as you have indicated by still receiving the same Error. 
In debugger the lv_version in Z2UI5_CL_DEMO_APP_014 is COM.SAP.OPENUI5.DIST:SDK:1.120.0:WAR

    DATA(lt_config) = VALUE z2ui5_if_client=>ty_t_name_value(
      (  n = `data-sap-ui-theme`         v = `sap_belize` )
      (  n = `src`                       v = `https://ui5.sap.com/resources/sap-ui-core.js` ) "<- adjusted ( for example to load from sap cdn)
      (  n = `data-sap-ui-libs`          v = `sap.m` )
      (  n = `data-sap-ui-bindingSyntax` v = `complex` )
      (  n = `data-sap-ui-frameOptions`  v = `trusted` )
      (  n = `data-sap-ui-compatVersion` v = `edge` ) ).

**Comment by ssocratous71** [comment]
MY bad!! I did not notice that lt_config has to be passed as parameter.  Not it works fine! Thanks!
