### ISSUE TITLE
View Parser V2 - Potential Improvements and Open Questions

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#660]
The z2ui5_cl_xml_view class (renderer V1) currently has several limitations:

1. Namespace Conflict: Controls with identical names from different namespaces (like sap.m.Input and sap.ui.webc.main.Input) cannot be consistently integrated.
[sap.m.Input](https://sapui5.hana.ondemand.com/#/api/sap.m.Input)
[sap.ui.webc.main.Input](https://sapui5.hana.ondemand.com/#/api/sap.ui.webc.main.Input)
4. Incorrect Namespace Definition: The class uses aliases instead of actual namespaces:
https://github.com/abap2UI5/abap2UI5/blob/fb13cbce11f56b09cf60b8ac1b985191cb8c42ce/src/z2ui5_cl_xml_view.clas.abap#L4605C35-L4605C35
A correct usage would look like this:
https://github.com/abap2UI5/abap2UI5/blob/fb13cbce11f56b09cf60b8ac1b985191cb8c42ce/src/02/z2ui5_cl_ui5_m.clas.abap#L330
8. Control Naming Discrepancy: The class defines control names with underscores, differing from UI5 API naming conventions. This discrepancy hinders automated code generation based on the UI5 API. For example, in sap.m, the correct naming convention should be as shown in this image: <img width="200" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/18052fe1-ebe4-404c-9711-956baa80417e">
10. Class Size: The z2ui5_cl_xml_view class is significantly large, potentially affecting maintainability.

**No plans to delete or replace the class z2ui5_cl_xml_view because this would create big incompatibilities and all apps have to be adjusted, just asking if there is a better approach to create the view for the future (as an additional approach)?**

My idea is the following: 
Introduce a new class structure where main namespaces like sap.m and sap.ui are separated into distinct classes with naming conventions matching the UI5 API. For example, see sap.m implementation here:
https://github.com/abap2UI5/abap2UI5/blob/main/src/02/z2ui5_cl_ui5_m.clas.abap

The usability would look like this. 
Example App with namespace sap.ui.webc.main:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_131.clas.abap
Example App with namespace sap.m:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_132.clas.abap
Got it from this blog post: 
https://blogs.sap.com/2022/03/10/ui5-web-components-enablement-for-openui5-sapui5/

Open Questions:
- How many subclasses should exist to avoid unnecessary complexity?
- Suggestions for naming the basic methods to create the XML tree, currently using underscores (e.g., _add, _add_p, _add_c) to distinguish from UI5 controls
- Usability easy enough?

This approach is still experimental, and I'm open to ideas and experiences. Please share your thoughts in the comments!

**Comment by axelmohnen** [comment]
@oblomov-dev,
Yes, I see the need of redesigning the framework, as the class z2ui5_cl_xml_view getting to large.
I prefer to have only one class per namespace. This makes it not to complex, but still solves the naming issue.

Doesn't matter how the final redesign will look like, we have to keep the current approach for existing apps!

Thanks,
Kind regards
Axel

**Comment by choper725** [comment]
well i get why redesign is needed, its just that for me, it about simplicity, once an abaper is jumping on this project, xml view is a really friendly class, what i mean by that is, if you want lets say a label, you ssarch for a label in the “pool of controls”,
with a class for every name space, things can do get quite tricky, as of the new demos for the new approach arent that intuative as the old approach..
to conclude this for me this project is not to replace ui5, is just to open a doorway for a great way to program it..

cheera choper725

**Comment by oblomov-dev** [comment]
yes you are right. xml_view makes it very easy for the beginning. therefore i still try to find a way to allow the use of multiple view parsers creating the possibility that everyone can use their favorite one.

**Comment by oblomov-dev** [comment]
There are a lot of interesting innovations on the roadmap 🧐
https://btp.udina.de/development/ux/ng-ui5.html

* "In the long run, the [UI5 Web Components](https://sap.github.io/ui5-webcomponents/) will replace the classic UI5 controls."
* UI5 2.0
* etc.

I think it makes sense to wait a little bit before putting too much effort in a new view parser. Maybe we can include some of the upcoming innovations in the new one. And then we should also find a good way for documentation and solve this issue:
https://github.com/abap2UI5/abap2UI5/issues/241

**Comment by oblomov-dev** [comment]
i will close this for now. the actual view renderer seems to be a pragmatic and good approach! we should just wait a little bit more for UI5 2.x and webc controls and then make a new one based on this new innovations.
