### ISSUE TITLE
Alignment of suggestion items

### ISSUE THREAD

**Issue by WegnerDan** [abap2UI5/abap2UI5#661]
I don't think this is a bug, but rather user error.

I've got a suggestionItem list with very long texts and the texts are aligned to the right. 
Is there a simple way to get them aligned to the left?

I can't provide a better screenshot (sensitive customer data).

![image](https://github.com/abap2UI5/abap2UI5/assets/6908247/fed38f97-2d4d-49c3-87c0-515d4b593d03)

It works fine with short texts, but these descriptions can be several hundred characters long.

**Comment by oblomov-dev** [comment]
Have you checked the property textdirection of suggestion item?
https://sapui5.hana.ondemand.com/sdk/#/api/sap.m.SuggestionItem%23controlProperties

<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/64a02ee7-98e4-492e-86f4-2dae74d7dde0">

**Comment by WegnerDan** [comment]
That's sounds exactly right.

Not entirely sure where to use it, though. 

I'm using ``list_item( text = `{VALUE}` additionaltext = `{DESCR}` ).`` to bind table fields to suggestionitems. 

I assume the control sap.m.SuggestionItem has to be implemented first, right?

**Comment by oblomov-dev** [comment]
yes seems that the control is not there add the moment, you can try to add it by yourself with:
https://github.com/abap2UI5/abap2UI5/issues/303
https://github.com/abap2UI5/abap2UI5/issues/248

In the end you can use it by doing:
suggestion_item( textdirection = {TEXTDIRECTION} )

let me know it it works for you, otherwise i can check this again.

**Comment by WegnerDan** [comment]
I've already tried, but I can't get the description property to show up yet.

Hopefully I'll get this to work tomorrow. Will report back.

**Comment by WegnerDan** [comment]
I've just noticed that the current version of method list_item already has a textdirection parameter, but it does not seem to affect the output of the suggestions.  

It seems to me this is probably not the correct property anyway:
https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.core.TextDirection%23overview

This is probably for languages that read from right to left and not the alignment of the text in the suggestions.

**Comment by WegnerDan** [comment]
Using suggestionrows instead of suggestionitems in combination with the wrapping property of label fixes my problem!
