### ISSUE TITLE
message manager - moved into separated custom control

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#667]
With: https://github.com/abap2UI5/abap2UI5/pull/666

The Message Manager Functionality is now separated from the index.html and included in:
https://github.com/abap2UI5/abap2UI5/blob/main/src/03/z2ui5_cl_cc_messaging.clas.abap

Sample how to use it here:
https://github.com/abap2UI5/abap2UI5-samples/blob/main/src/z2ui5_cl_demo_app_135.clas.abap

Tried to take all functionality of demo:
Z2UI5_CL_DEMO_APP_084

The idea is that you can sent a Table with Data Binding to the frontend and it gets automatically synchronized with the Messages of the Message Manager. That makes it easy to use in the backend.
Binding:
```abap
 DATA(page) = view->_cc( 
         )->messaging( )->control( client->_bind_edit( mt_messaging )
        )->shell(
```
Synchronization at the frontend with:
```JS
var resBinding = new sap.ui.model.ListBinding(Messaging.getMessageModel(), "/" );
resBinding.attachChange(this.onModelChange.bind(this));
```

Expect some bugs but in general it works on my side. 

@choper725 and everyone else who is using it, can you check if this works for you?

**Comment by choper725** [comment]
ill check on my end but it seems like a great idea moving it to a cc

**Comment by oblomov-dev** [comment]
Yes the previous version also only worked for the main view because the message manager gets binded to the main view but when we extend the CC we can also bind it to the nested view.

The message manager is a little bit complex and it takes me a while, also a lot of other improvements are possible but I suggest we go with the basic logic for now and make more extensions when it is really needed.

**Comment by choper725** [comment]
as of demo 66, the message manager also work in nested view,

it dont work in popup

**Comment by oblomov-dev** [comment]
ah ok, cool, thank you for checking this! 

yes, then maybe the binding has to be additionally made with the popup to work when there is the need to work in such a situation.

**Comment by choper725** [comment]
i dont think its possible to load cc as part of xmlview of popup..
it was the same problem with the zcc plain xml use inside a popup view

**Comment by oblomov-dev** [comment]
mhh it is not possible to use Custom Controls in popups? 🤔

I mean maybe you have to load the JS definition of the CC beforehand with the main view, but after doing this once the CC is globally available and you can use it in any XML view (as for as i know, but never testedit)

**Comment by choper725** [comment]
ill check this also, maybe with a demo..

**Comment by oblomov-dev** [comment]
yes share your demo if you run into problems, and i can check if we find a solution. Just create a new issue. I will close this one.
