### ISSUE TITLE
tag v.1.30.6 - message manager, timer, title, scrolling & focus (incompatibility)

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#676]
Message manager
Timer
Title
Scrolling
Focus/Cursor 

are now included as Custom Controls. Check the samples and adjust your apps.

Use the following tag if you run into problems:
https://github.com/abap2UI5/abap2UI5/releases/tag/v.1.30.6

And let me know if you miss a functionality.

**Comment by choper725** [comment]
title ge js getting called 5 times in http handler.

and there is way a way to cleaer interval now that is a cc ?

**Comment by oblomov-dev** [comment]
Thank you! Fixed it with https://github.com/abap2UI5/abap2UI5/pull/678

Still trying to figure out which CC should be loaded at startup. In general it seems to be a robust process, loading cc accidentally multiple times does not cause any problems and loading multiple CC at startup also does not really make the startup process longer. Maybe only the controls which load third party libraries like driver.js or bwip-js should not be loaded per default at startup. I will continue testing this.

In addition i have in mind to make the Custom Controls independent from the specific view renderer to make it possible to work with multiple different renderers in the future (https://github.com/abap2UI5/abap2UI5/issues/660). Therefore the use of the class z2ui5_cl_xml_view should be avoided in the CC classes. Start to create a new wrapper class for the use of CC with z2ui5_cl_xml_view:
https://github.com/abap2UI5/abap2UI5/blob/main/src/z2ui5_cl_xml_view_cc.clas.abap
(still experimental)

@choper725 
 ```
and there is way a way to cleaer interval now that is a cc ?
```
what does this mean/ which functionality do you need?

**Comment by choper725** [comment]
hi @oblomov-dev 
i was just using timer with repeat, bun than notich, how can we stop thw repeat ?

**Comment by oblomov-dev** [comment]
ah yes, checked this out and updated demo:
Z2UI5_CL_DEMO_APP_028

With https://github.com/abap2UI5/abap2UI5/pull/680

Not sure anymore if we really need the check_repeat, because every model updated also rerenders the timer control (which only activates another delayed). You can try it out and let me know it if works.

**Comment by choper725** [comment]
works great !
logic wise its probebly easier to understand that you can manually shutdown timer not related to view model update being called or not..

**Comment by oblomov-dev** [comment]
Needed to reorganize the index.html a little bit to make the maintenance easier. Now the javascript logic is separated and stored here:
https://github.com/abap2UI5/abap2UI5/blob/eaf9e993c288c22eb8ffb578fadd422c9884dc82/src/01/01/z2ui5_cl_fw_http_handler.clas.abap#L136
And can be adjusted with the help of this repository here:
https://github.com/abap2UI5/js_files_of_abap2UI5/blob/main/webapp/fw/index.js

For a pure JS snippet i needed to delete the importing parameter:
https://github.com/abap2UI5/abap2UI5/blob/eaf9e993c288c22eb8ffb578fadd422c9884dc82/src/01/01/z2ui5_cl_fw_http_handler.clas.abap#L19

But added a new functionality for this here:
https://github.com/abap2UI5/abap2UI5/blob/eaf9e993c288c22eb8ffb578fadd422c9884dc82/src/01/01/z2ui5_cl_fw_http_handler.clas.abap#L290

The custom functionality which should be processed onEventFrontend can be imported via the new normal custom_js now. Example here:
```abap
  data(lv_js_on_event_frontend) = `sap.z2ui5.onBeforeEventFrontend.push( (args) => { debugger;  sap.m.MessageToast.show("test") } )`.


    DATA(lv_resp) = SWITCH #( server->request->get_method( )
       WHEN 'GET'  THEN z2ui5_cl_fw_http_handler=>http_get( t_config = lt_config
         check_logging = abap_true
         custom_js = lv_js_on_event_frontend
         )
       WHEN 'POST' THEN z2ui5_cl_fw_http_handler=>http_post( server->request->get_cdata( ) ) ).
```

fyi @choper725 let me know when this not works or if there are any problems.

**Comment by choper725** [comment]
never really used the custom js parameter in prod..
as its rather oreferable to make changes app wise and not handler wise for me..

what is the purpose of the js files repository ?

i see the http handler changed completly, anything new ?

what is the onbeforeevent frontend ?? first time seeing that

**Comment by oblomov-dev** [comment]
the onbeforefrontendevent array is just a chance to store funcitons which will be processed onfreontendevent and replace the importing parameter custom_js_on_event_frontend.

the js files repository is more or less just for testing before copying it to abap2UI5. 

just refactored http handler a little bit, nothing new, try to make everything a little bit less messy but not easy with the abap & js mixture.

**Comment by choper725** [comment]
isee,

btw, not working on my end, getting this right after a pull
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/4094be41-bf39-4a2d-82cf-a1291dd96d6b)

**Comment by oblomov-dev** [comment]
thank you for testing, you can try again:
https://github.com/abap2UI5/abap2UI5/pull/715

**Comment by choper725** [comment]
not getting logs in console when check_logging = abap_true

**Comment by oblomov-dev** [comment]
adjusted some logic again, should work now.

**Comment by choper725** [comment]
> adjusted some logic again, should work now.

work now

**Comment by oblomov-dev** [comment]
this issue got big. i close this one. just open a new one if there are any further problems.
