### ISSUE TITLE
Multi Combo Box support

### ISSUE THREAD

**Issue by ssocratous71** [abap2UI5/abap2UI5#690]
Hi,
  I have change the library to make multi combo box work (it was rendered as combobox). I had made it work but I am having trouble getting the selectedkeys back. I only get an empty itab without any key information:
                            )->multi_combobox(
                               name = 'Hier'
                               showButton = abap_true
                               items = client->_bind( val = gt_hier )
                               selectedKeys = client->_bind_edit( val = gt_sel_hier )
                               "selectedItems = client->_bind_edit( val = gt_hier )
                               )->item(
                                  key = '{KEY}'
                                  text = '{PRODH}'

gt_hier contains all items with key and text info.
gt_sel_hier has a similar structure (I tried string_table but it always returns empty). I get as many lines as the selections I made, but with empty items in the gt_sel_hier.

Any help will be appreciated.

Regards,

S.Socratous

**Comment by oblomov-dev** [comment]
so the combobox works, you just have problems with the multi combo box?

maybe you can make a little example app out of it that i can copy&paste to an other system. That makes it easier to find the problem (maybe something wit the binding but i can just guess).

**Comment by oblomov-dev** [comment]
i close this one, fixed with https://github.com/abap2UI5/abap2UI5/pull/694
if you run into further problems, just open a new issue
