### ISSUE TITLE
event for onClick js event of html control

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#707]
hi @oblomov-dev 

is it possible to connect a js native onClick event to behave like an event from sapui5 ?

for example a onclick event of html button to make a roundtrip with a  rasing event in abap ??

something in the sense of:
`<html:button onclick = client->_event( "ON_CLICK_EVENT" ) />`

**Comment by oblomov-dev** [comment]
yes, you can check the syntax of the call at the frontend with:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/3858bb00-086e-40c4-b510-d65e6ad46a6c">

And the function at the frontend is stored here:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/ecbb859b-1ef6-4341-818d-2df0554a739e">

In the html something like this should work:
```js
sap.z2ui5.oController.onEvent( { 'EVENT' : 'MY_EVENT', 'METHOD' : 'UPDATE' , 'CHECK_VIEW_DESTROY' : false })
```

Feel free to add your example to the samples repository, maybe its easier then to find a solution.

**Comment by choper725** [comment]
works !!
is it possible to make it user friendly like adding a parameter to bind methods to make it add the prefix to the onEvent string ??

**Comment by oblomov-dev** [comment]
yes i would always recommend to encapsulate it in a custom control, using data exchange via properties and use only UI5 API (and avoid using window object as far as possible).

Give me a few days, i prepare a little guideline of how to encapsulate JavaScript in a CC and integrate to abap2UI5.

**Comment by oblomov-dev** [comment]
check this out:
https://blogs.sap.com/2023/12/11/abap2ui5-a4-extensions-ii-guideline-for-developing-new-features-in-javascript/

summed up what is working best for me, but maybe you will find other ways that fit better to your needs. 

as long as you stay in a custom control, you can just raise an event and don't need to call framework functions manually as you did with:
sap.z2ui5.oController.onEvent
furthermore the complete data exchange can be done via properties+data binding making the communication with the backend very simple. that is the reason why this is my preferred way at the moment.

**Comment by choper725** [comment]
i see, very detailed blog, i just think that for bigger controls this is probebly is the best way, but for small things maybe its overkill ??
any way, maybe for something small like tie an event to an html tag, this might be large.
but i see why you prefer this as a guideline to develop js abap integration
