### ISSUE TITLE
messaging cc not working on sdk version below 1.118

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#736]
hi @oblomov-dev 
messaging cc not working on older version below 1.118.

**Comment by oblomov-dev** [comment]
yes messaging only exists on higher releases, it replaces the old message manager:
https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.core.message.MessageManager
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/27545118-3e05-4655-a273-9d4275563dbe">

**Comment by choper725** [comment]
well, actually didnt know that,
guess i need to find a solution as all apps are now broken, as runing on older sdk.. from previous implementation  of message manager.

**Comment by oblomov-dev** [comment]
Ah adjusted it a few weeks ago and thought it's a good idea to switch directly to a non deprecated control but did not kept this in mind...

As far as I remember the message manager and messaging have very similar APIs, so maybe you can just extend the CC with some try catch and when messaging is not there you do the same with message manager.

**Comment by choper725** [comment]
> Ah adjusted it a few weeks ago and thought it's a good idea to switch directly to a non deprecated control but did not kept this in mind...
> 
> As far as I remember the message manager and messaging have very similar APIs, so maybe you can just extend the CC with some try catch and when messaging is not there you do the same with message manager.

ill try do that

**Comment by oblomov-dev** [comment]
i close this one, so far i have no time to develop it for lower ui5 libraries, but feel free to share your solution or let me know if you run into problem, just reopen the issue.
best regards.

**Comment by choper725** [comment]
i sont got time for that either..  but i need that as some of my apps are broken because of that
