### ISSUE TITLE
Integration Chart.js as CC

### ISSUE THREAD

**Issue by Marchl-Woid** [abap2UI5/abap2UI5#744]
Hello everyone, 
I am a big fan of this project and am already experimenting with possible use cases. I also find the concept with the cutsom controls quite exciting.

Is there already a plan or an effort to integrate the chart.js library as an alternative chart representation?

https://www.chartjs.org

Thank you and greetings
Matthias

**Comment by oblomov-dev** [comment]
Hi @Marchl-Woid,

thank you for this issue.

Yes chart.js is a very nice framework and it is open-source, unfortunately a lot of charts and diagrams of UI5 are not part of open-ui5. Therefore integrating this into abap2UI5 is a very good idea!

I checked the framework and it seems it should be possible to create a custom control around the functionality and then send a table with some additional config information from the backend. 

If you have some JS knowledge or someone else feel free to give it a try with:
https://blogs.sap.com/2023/12/11/abap2ui5-a4-extensions-ii-guideline-for-developing-new-features-in-javascript/

<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/289330b6-ea8f-4fdd-80c2-a87fdc85e7e8">

**Comment by choper725** [comment]
see demo 147

**Comment by Marchl-Woid** [comment]
@choper725 . wow that was quick :)

I will play around with it tomorrow :) 

Happy new year to all

**Comment by choper725** [comment]
fully integrated with abap2ui5 framework, including plugins, see demo 148

**Comment by oblomov-dev** [comment]
Fantastic job, looks excellent!

And nice that it is solved with nested abap structures, makes the usability very easy! Luckily we could solve all compress and binding problems. 🥳

<img width="1372" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/a7e13f19-0ab8-40f8-9268-2eef6bcaeea6">

**Comment by Marchl-Woid** [comment]
You guys are amazing. Works perfect :)
