### ISSUE TITLE
new debugging

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#747]
hi @oblomov-dev 
im trying the check the new debugginng cc, 
i get nothing in console as before, even with check debugging = true in handler..
does this debugging cc works differently ??

**Comment by oblomov-dev** [comment]
yes press strg+a and then a popup with the xml shows up. will document it soon

**Comment by oblomov-dev** [comment]
i close this and we can continue here https://github.com/abap2UI5/abap2UI5/issues/748
