### ISSUE TITLE
Actual changes, Incompatibilities & Debugger Tools

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#748]
Added a few changes during the last week...

(1) 
Refactored the index.html to fulfill the following guidelines:
https://sdk.openui5.org/topic/28fcd55b04654977b63dacbee0552712
https://sdk.openui5.org/topic/408b40efed3c416681e1bd8cdd8910d4.html#loio408b40efed3c416681e1bd8cdd8910d4/section_MigrateJquery

(2) 
Especially the module loading of abap2UI5 and its custom controls changed, for example:
[    r_js  =    ` sap.ui.define("z2ui5/FileUploader",[` && |\n| &&](https://github.com/abap2UI5/abap2UI5/blob/0cb198b1e3a26fedbbbefd6ba80242f65987bd52/src/01/03/z2ui5_cl_fw_cc_file_uploader.clas.abap#L23)
We use now sap.ui.define and no JQuery dependency exists anymore.

(3) 
Tried to refactor all JQuery dependencies, there is still some work to do, but in general bootstrapping with the following works now:
https://sdk.openui5.org/nightly/2/resources/sap-ui-core.js

Recommend to check if the bootstrapping on your side with the new UI5 version also works and to adjust your custom controls. Its all preparation for:
https://blogs.sap.com/2023/12/21/introducing-openui5-2.x/

(4)
Added new debugger tools, now the console is not used anymore, use the keyboard shortcut ctrl+f12 instead:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/2f9588db-d222-4f9b-82ca-f44eeb039807">

(5) 
Fiori Launchpad Extension works now without OData Service and communicates directly via HTTP:
https://github.com/abap2UI5/abap2UI5-launchpad_on_premise

As always, expect some bugs and let me know if you run into problems.

**Comment by choper725** [comment]
strg+a is Ctrl+a ??

**Comment by choper725** [comment]
on a RTL orientation debug menu got all kinds of scrolls..
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/9432ba5c-5c74-421f-8045-cadf5672b39d)

**Comment by oblomov-dev** [comment]
Thank you and yes, check https://github.com/abap2UI5/abap2UI5/pull/749

**Comment by choper725** [comment]
with help of predefined css class in http handler, now the jquery is removed #751

**Comment by oblomov-dev** [comment]
thank you for the change and to add a demo with chart.js 🙏
