### ISSUE TITLE
Error in Extensions - Change CSS Demo

### ISSUE THREAD

**Issue by LadwigDev** [abap2UI5/abap2UI5#759]
Hi Oblomov, first of all: great work!
I am currently familiarizing myself with the framework and have arrived at CSS. When I call up the demo app 50, I am currently getting the following error message (newest version of ABAP2UI5 and demos is installed):

<img width="536" alt="Error" src="https://github.com/abap2UI5/abap2UI5/assets/155659152/b00657a1-6f46-4a7c-a1df-2c64eb3215b1">

My goal is to add a right border to columns of the ui_table to group those visually, so I tried copying the code of demo app 50 to mine and altered it as follows:

`view->_cc_plain_xml( '<html:style> .sapUiTableCol:nth-child(6) { border-right: 1rem solid; } </html:style>' ).`

But as soon as I include this line of code to my app I am receiving the same error message as above. Is this the right way to address a table column in CSS? Found it here: https://answers.sap.com/questions/11726643/assign-a-css-class-to-sapuitablecolumn.html

Best regards
Jan Ladwig

**Comment by oblomov-dev** [comment]
HI @LadwigDev,
in general you do everything right, the problem was that the demo was outdated, so thank you for finding the bug!
I fixed it now and you can check demo 50 again.

The following is now the right command to add css:
```
           )->_generic( ns = `html` name = `style` )->_cc_plain_xml(
                    `.sapMInput {` && |\n|  &&
                         `    height: 80px !important;` && |\n|  &&
                         `    font-size: 2.5rem !important;` && |\n|  &&
                         `}` && |\n|  &&
                         |\n|  &&
                         `input {` && |\n|  &&
                         `    height: 80% !important;` && |\n|  &&
                         `    font-size: 2.5rem !important;` && |\n|  &&
                         `}` && |\n|  &&
                         |\n|  &&
                         `input[role="textbox"] {` && |\n|  &&
                         `    height: 80px !important;` && |\n|  &&
                         `    font-size: 2.5rem !important;` && |\n|  &&
                         `}` && |\n|  &&
                         |\n|  &&
                         `input[role="text"] {` && |\n|  &&
                         `    height: 80px !important;` && |\n|  &&
                         `    font-size: 2.5rem !important;` && |\n|  &&
                         `}` && |\n|  &&
                         |\n|  &&
                         `.sapUiSearchField {` && |\n|  &&
                         `    height: 35px;` && |\n|  &&
                         `    font-size: 2.5rem !important;` && |\n|  &&
                         `}` && |\n|  &&
                         |\n|  &&
                         `.sapUiTfCombo:hover {` && |\n|  &&
                         `    height: 2rem;` && |\n|  &&
                         `    font-size: 2.5rem !important;` && |\n|  &&
                         `}` && |\n|  &&
                         |\n|  &&
                         `.sapMInputBaseInner::placeholder {` && |\n|  &&
                         `    font-size: 1.4rem !important;` && |\n|  &&
                         `}`
            )->get_parent(
```
And this is the output of demo 50:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/45155106-b7be-4ca5-b2be-acdc5b63e141">


Best regards.

**Comment by LadwigDev** [comment]
Thanks a lot! It works for me now too
