### ISSUE TITLE
S-RTTI required?

### ISSUE THREAD

**Issue by jelliottp** [abap2UI5/abap2UI5#767]
I've been exploring the project lately, good stuff here! I was interested in trying out table display and table maintenance since those seem to exist OOTB as samples. Seems like S-RTTI is required for the ability to display a tables dynamically, is that right? 

Unfortunately that project isn't currently compatible with a lot of system versions, is there any other way?

**Comment by oblomov-dev** [comment]
Hi @jelliottp 
yes you are right the repository is not compatible to lower releases. I adjusted the syntax for lower releases with [@abaplint](https://github.com/abaplint/abaplint) now and deleted the incompatible enum dependencies. Can you try again if the following (downported) s-rtti fork works on your system?

https://github.com/abap2UI5/S-RTTI-downport

Best regards.

**Comment by jelliottp** [comment]
Thanks. There's one more enum dependency here:
https://github.com/abap2UI5/S-RTTI-downport/blob/41624c91316b550f8400afc014ea36d6b0118101/src/zcl_srtti_typedescr.clas.abap#L72

**Comment by oblomov-dev** [comment]
thank you, should be fixed now.

**Comment by jelliottp** [comment]
Thanks! I no longer get the errors.

Although, is the table maintenance tool still available somewhere? It's mentioned in the blog post [here](https://blogs.sap.com/2023/04/02/abap2ui5-4-5-additional-features-demos/), but it's not actually in the abap2UI5-tools from what I can tell.

**Comment by oblomov-dev** [comment]
the link changed, check out this class:
https://github.com/abap2UI5/abap2UI5-tools/blob/main/src/z2ui5_cl_tool_app_04.clas.abap

It is just a demo and showcases the general functionality, but it has some bugs and limitations. I recommend just to take it as an example and build an own app for your specific use case around it.

**Comment by jelliottp** [comment]
Thanks again, closing this since S-RTTI is working.
