### ISSUE TITLE
Custom Control: File Uploader

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#768]
Hi,
I have a general question about the custom control file uploader.
I see that we are not loading the custom control JS anymore like before.

`*    client->view_display( Z2UI5_cl_xml_view=>factory( client
*         )->_z2ui5( )->timer(  client->_event( `START` )
*         )->_generic( ns = `html` name = `script` )->_cc_plain_xml( z2ui5_cl_cc_file_uploader=>get_js( )
*         )->stringify( ) ).`
* 

Now I encountered that each time we call the file uploader, it creates a new iFrame. 
Unfortunately, The iFrame doesn't disappear after the file uploader has been closed.
![image](https://github.com/abap2UI5/abap2UI5/assets/22371169/05e13b54-c078-4cde-9c6a-83363fcdf969)

Is this a normal behavior (as designed)?
Thanks,
Axel

**Comment by oblomov-dev** [comment]
Hi Axel,
the file uploader custom control is loaded as before, but not on app level anymore. It is now send with the index.html at the beginning:
![image](https://github.com/abap2UI5/abap2UI5/assets/102328295/a58fefcf-f04f-4068-987e-7d9ca8d061a0)

Thats why i would suggest that these iframes also existed before? Maybe the functionality with file loading creates these iframes, and yes maybe there are nicer solutions possible, but so far it is the "designed behaviour".

Best regards.

**Comment by axelmohnen** [comment]
OK, thanks for the answer.
