### ISSUE TITLE
Clarification: Tree - event for node color and action

### ISSUE THREAD

**Issue by OlegBash599** [abap2UI5/abap2UI5#773]
The issue is for clarification only (not bug found yet).

I am dealing with Tree control (like in the class Z2UI5_CL_DEMO_APP_007  ).
Is it possible:
1) to color node lines 
2) to hide columns (to make it technical column for coloring)
3) to implement lazy loading for upload data on node-expansion.

Thank you!

**Comment by oblomov-dev** [comment]
Hi @OlegBash599,

(1) + (2) it depends if there are attributes of the Tree Table Control which can change the color of nodes or make them technical. Did you check the UI5 Documentation for this?
https://sapui5.hana.ondemand.com/sdk/#/entity/sap.ui.table.TreeTable

If you find an example or attributes, please share it here and then we can extend abap2UI5 to use them als there.

(3) Lazy loading is in general not possible, we send the whole model at once to the frontend, but so for also without lazy loading i never head performance issues.

Best regards.

**Comment by oblomov-dev** [comment]
i close this one, just reopen it, if you further questions.
