### ISSUE TITLE
CROSS_APP_NAV_TO_EXT issue

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#775]
Hi @oblomov-dev 
Happy new year!
I install the latest tag 1.113.0 of ABAP2UI5 and the latest FLP integration approach.

Unfortunately, the cross application navigation "CROSS_APP_NAV_TO_EXT" in "EXT"  mode doesn't work anymore for my app.
I just see that the frontend event get's triggered and the parameters are passed, but nothing happened.
I don't see an error in the console.

Update: 
I found an exception while requesting the uShell service:
oCrossAppNavigator = sap.ushell.Container.getService("CrossApplicationNavigation");
![image](https://github.com/abap2UI5/abap2UI5-launchpad_on_premise/assets/22371169/ad4b8c46-3a7f-413d-bde4-b86ce04fc085)

Could you please try to reproduce the error. Do you have the same behavior?
Thanks,
Axel

**Comment by oblomov-dev** [comment]
i close this one, just open in a new issue if you have further problems.
