### ISSUE TITLE
launchpad not work on premise

### ISSUE THREAD

**Issue by dcriaco** [abap2UI5/abap2UI5#776]
Hi,
I created an app demo and I would to link on my launchpad.
I followed the guide but still get errors:
![Screenshot 2024-01-04 104952](https://github.com/abap2UI5/abap2UI5-launchpad_on_premise/assets/155626415/cad90c73-390c-45a1-97c4-052e00a6105a)

thanks in advance.
kind regards.
domenico

**Comment by oblomov-dev** [comment]
i close this one, just reopen it if you have further questions.
