### ISSUE TITLE
Brainstorming: Passing parameter via cross application navigation

### ISSUE THREAD

**Issue by axelmohnen** [abap2UI5/abap2UI5#777]
Hi @oblomov-dev,

I have the requirement to pass data back from called ABAP2UI5 application to the calling Fiori element app.
Within normal SAPUI5 apps you could archive this via cross application navigation using some events from the extension API.
e.g "modifyStartupExtension", "adaptNavigationContext", "doCustomNavigation", etc...

Schema:
FLP -> Calling app (Fiori element) -> Intent based Navigation -> Called app (ABAP2UI5)
           Calling app (Fiori element) <- Intent based Navigation (with returning data) <- Called app (ABAP2UI5)

In ABAP2UI5 we have to return the data via variable "sap.z2ui5" I guess (like for APP_START) just the other way around and inside the "View1.controller.js" we have to push the data to the navigation context somehow.

Did you every had such a strange requirement ;-)
Do you have an idea how to implement this?
Thanks a lot.
Kind regards
Axel

**Comment by oblomov-dev** [comment]
some of this funcitonality is integrated now, just open a new issue if you need more functionality, i will close this one for now.
