### ISSUE TITLE
logs in console

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#790]
hi @oblomov-dev 
the console printing might be irrelevant as of new debugger tools

               `            if (sap.z2ui5.checkLogActive) {` && |\n|  &&
               `                console.log('Request Object:');` && |\n|  &&
               `                console.log(sap.z2ui5.oBody);` && |\n|  &&
               `            }` && |\n|  &&

this code in get_js method of Z2UI5_CL_FW_HTTP_HANDLER

**Comment by oblomov-dev** [comment]
Thank you for the hint, deleted it with https://github.com/abap2UI5/abap2UI5/pull/791
