### ISSUE TITLE
Demo 147 - Error 

### ISSUE THREAD

**Issue by Hhpy410** [abap2UI5/abap2UI5#806]
hi @oblomov-dev

![22](https://github.com/abap2UI5/abap2UI5/assets/38339002/fc00c65d-5cd0-4499-b0f4-efaa41fbcf98)

**Comment by choper725** [comment]
hi @Hhpy410 
demo 147 is irrelevant check demo148 instead

**Comment by Hhpy410** [comment]
Thanks
