### ISSUE TITLE
Usage of the Action Sheet

### ISSUE THREAD

**Issue by LadwigDev** [abap2UI5/abap2UI5#808]
Hi  @oblomov-dev ,
it's me again. I have seen that the action sheet has already been implemented in the z2ui5_cl_xml_view class. My goal is to build something like this:

https://sapui5.hana.ondemand.com/sdk/#/entity/sap.m.ActionSheet/sample/sap.m.sample.ActionSheet/code

I tried to figure out how to do it by myself but unfortunately I can't find this method being used in any of the demo classes. Would it be possible to create a demo for it so that everyone is able to see how you can build a menu in your app?

Best regards
Jan

**Comment by choper725** [comment]
Hi @LadwigDev 
ill try bulding a demo for this control, i think this control is called from a button which open a popup with actionsheet control and all the buttons inside of it.

**Comment by oblomov-dev** [comment]
thank you @choper725 
<img width="476" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/fc7d1287-5224-487a-bebe-700c1c6b3f53">

added the app also to the overview demo_000.

**Comment by LadwigDev** [comment]
Great, thanks a lot for your help! @choper725 @oblomov-dev
