### ISSUE TITLE
oViewPopup update

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#811]
hi @oblomov-dev 
recent change in http handler oViewPopup.getVisible
breaks model update,
the scenario i encountered it is uaing nested views..

do you havw this problem also ?

ill try to demo it later..

**Comment by oblomov-dev** [comment]
ah ok thanks for the hint. yes i needed to change it because otherwise i run into problems with the table select dialog, mhh yes a small demo would be nice than i can check all use cases and switch the if clause again to make it work with every scenario.

**Comment by oblomov-dev** [comment]
found the issue also on my system, fixed it with https://github.com/abap2UI5/abap2UI5/pull/813

But i made a bigger change out of it and refactored the logic of popup, popover and nest handling. its a lot easier now, but it would be great if you test it for all your use cases on your side. 

feel also free to send demos if you have more specific uses cases, then i have an example i can use in the future for testing. It helps to ensure that i don't add incompatible changes, i always test against unit tests and all the demos in the samples repository.

**Comment by choper725** [comment]
great, ill check also on my end that nothing breaks..
