### ISSUE TITLE
Make left column in sample Z2UI5_CL_DEMO_APP_069 scrollable?

### ISSUE THREAD

**Issue by CalvinwithHobbes** [abap2UI5/abap2UI5#814]
Hi,
is there a possibility to make the left column of your sample Z2UI5_CL_DEMO_APP_069 (Flexible Column Layout - Master details with tree) scrollable?
I don't find a solution.... 
Regards,
Calvin.

**Comment by oblomov-dev** [comment]
Hi @CalvinwithHobbes,

i thought the scroll function comes automatically when the tree gets too big, but never tried it by myself. Otherwise maybe use a scroll container?

Best regards.

**Comment by CalvinwithHobbes** [comment]
Hi @oblomov-dev,

thank you for your kind reply,
Unfortunately, the scroll bar does not appear, when the list gets bigger. I tried it within the sample class by just enhancing the table mt_tree.

I'll look how to integrate a scroll container.

Regards,
Calvin

**Comment by oblomov-dev** [comment]
yes or check the samples page:
https://sapui5.netweaver.ondemand.com/sdk/#/controls

there is also scroll functionality on the left side, you can check with the ui5 debugger tools which ui5 controls they use and try to create the same.

feel free to share your demo if you need further support.

**Comment by oblomov-dev** [comment]
i close this one, just reopen it, if you further questions.
