### ISSUE TITLE
Update Package Structure

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#822]
Updated the package structure, the project is now separated into two main packages:

* internal - should not be accessed from outside, APIs change all the time
* external - can be used outside in apps, API changes are kept to a minimum

<img width="516" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/beaf11f9-1f83-4ab0-8167-d6a16e1cde17">

I don't want to make this project too big, but a basic amount of popups should be available, otherwise every app has to be developed from the scratch and every app needs to develop its own 'POPUP_TO_CONFIRM' all the time. Therefore i added a folder for popups (the old gui FM POPUP* are my idea what can be placed in here). And there is also one folder for apps if needed.

**Comment by choper725** [comment]
on the changes note,

i see there is a new parameter in bind called struc..
what is the difference when using it or not ?? as before i didnt encounter any issues binding a field in a struc

**Comment by oblomov-dev** [comment]
yes i am also not sure if this is really needed but check demo 166, you can send values to the frontend like this now:
<img width="727" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/91b39c5f-4668-46d3-a97c-3d9224fa97cc">

And when you use the normal way, they are send as separated values:
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/f592c585-5a99-420e-a00c-9bc93e945900">

maybe this will be useful for certain custom controls, but we will see, also no use case so far, just added the possibility.

**Comment by choper725** [comment]
structured json, insted of concatinated one... good idea.. more organized
