### ISSUE TITLE
Demo App 160 - Displaying number 0 in ui.table

### ISSUE THREAD

**Issue by LadwigDev** [abap2UI5/abap2UI5#827]
Hi,
I think since update 1.115 if you bind an attribute of type p to a text control in the ui.table the value 0 does not get displayed anymore. Is it possible to revert that change or do I have to use something else than the -> text( ) method to display numbers in the table? This is also an issue with the ->input( ) control. You can see it in Demo Class 160.

Best regards
Jan

**Comment by oblomov-dev** [comment]
Thank you for the hint! I updated the demo, per default initial values are not sent to the frontend anymore to keep the payload smaller, but if you need them you can change the compression to "none" with the binding. I updated demo 160, just check it out to see how it works.
Best regards.

**Comment by LadwigDev** [comment]
Great, thank you! :)
