### ISSUE TITLE
nav container in popup

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#834]
hi @oblomov-dev 

been trying to implement navContainer in popup (which uses _event_client

in latest PR in demo repository i added a demo (170) to show this example.

using the same logic to navigate using .to method of navContainer not working on a Fragment.

the way i got it to work is by adding this case to the controller.
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/82330b93-f904-4f78-b709-a97eeaea6505)

as this uses sap.ui.getCore() which is not used anymore.

is there a way getting the controls in the Fragment ??
oViewPopup does not contain the controls, as its not the Fragment view. 

thanks for the help

**Comment by oblomov-dev** [comment]
oViewPopup is not the fragment view? mhh i thought i created the popupview with this object...
you have also oControllerPopup, maybe with oControllerPopup.getView() you get the information you need? otherwise i can check this in a few days, but spontaneously i have also no idea. sap.ui.getCore() was always the easy way but yes for fiori 2.x compatibility we hopefully find a better way.

**Comment by choper725** [comment]
oControllerPopup.getView() is null.. :\

but i think i figured it out using this post:
https://stackoverflow.com/questions/39660161/how-to-access-elements-from-xml-fragment-by-id

by an id, to Fragment.load method
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/6efce65d-07e3-4f96-a0c2-7abc2b5c6057)


and using the Global Fragment object in event_client, like this:
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/c05448e5-1310-49f4-9bb4-334d9130fa77)



let me know if you want me to PR this..
seems to make it work..

**Comment by oblomov-dev** [comment]
Nice, looks good to me! Yes PR would be great!

**Comment by choper725** [comment]
it got deleted with recent PR

**Comment by oblomov-dev** [comment]
ah, PR so much at the moment. seems i overlooked it. thank you for the hin, can you PR again? sorry!

**Comment by oblomov-dev** [comment]
or wait, i found it, can fix it with my next PR

**Comment by oblomov-dev** [comment]
done with https://github.com/abap2UI5/abap2UI5/pull/839
but please check one more time :)

added and recommend to use this constant, that we have the option to change the name in the future and your apps still continues to work:
https://github.com/abap2UI5/abap2UI5/blob/9b15a1055c9874320c46405aa781d05ac71b2039/src/02/z2ui5_if_client.intf.abap#L15
