### ISSUE TITLE
Chart.js & ajson binding

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#842]
Unfortunately i have a small problem with the new ajson logic and chart js:

Not every chart is displayed:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/c3e37284-0064-4962-9c92-a43a63cb0988">

I implemented a new custom compression:
https://github.com/abap2UI5/abap2UI5/blob/c9e154d02e4cdf6395ea88a7eb70a486cdd162eb/src/01/05/z2ui5_cl_cc_chartjs.clas.abap#L616

The model at the frontend looks very similar to the former version now:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/12dc323f-3c75-4afd-b688-4399fde9c2c3">

@choper725 i have no time to check the whole frontend logic. maybe you have a chance to see what we need to add here? when you set a breakpoint at the new compression implementation you see that you have all freedom now to decide which attribute is send to the frontend.

**Comment by oblomov-dev** [comment]
reason for the change here https://github.com/abap2UI5/abap2UI5/issues/843

**Comment by choper725** [comment]
in the json there is a parameter called scaleid which should be scaleID and  also there are some keys i change syntax in the CC class set method..
which i see is not working thats why some charts dont show up

**Comment by oblomov-dev** [comment]
ah thanks, good hint 
yes scaleid stays scaleid because it is not written in snake case. it is just defined as:
scaleid
the others which get camelcased are defied in snake case like:
border_color  
border_width 
etc.
they become:
borderColor
borderWidth
etc.

Mhh i think fixing is no problem, but the old approach than would not work anymore.

Maybe you can ensure first if all your other sceanrios and apps run with the new json logic and then we can adjust chart.js in the end.

**Comment by choper725** [comment]
ill check all of my custom control and let you know if something behaves wierd

**Comment by oblomov-dev** [comment]
with the latest PR, one chart more works again:
<img width="1360" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/7101e70b-19cd-45a3-9882-efe7baae4d68">

**Comment by oblomov-dev** [comment]
see https://github.com/abap2UI5/abap2UI5/issues/843
