### ISSUE TITLE
error in index.html

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#844]
getting this error sometimes upon calling an event...

![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/6bc67f5c-b31e-4849-8abd-a4730f962aaa)

edit:
something is weird with events
getting the same error in demo 141.

comes up when calling html control or calling a custom js function even one entred at custom_js paremeter in the handler..

**Comment by oblomov-dev** [comment]
thanks, saw it also on my machine, hope it is fixed now with
https://github.com/abap2UI5/abap2UI5/pull/845

**Comment by choper725** [comment]
works on my end.. thanks
