### ISSUE TITLE
Demo 152: 500 Internal Server Error

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#870]
Demo 152 gives a 500 Internal Server Error
![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/9f7542b1-b4c8-41a1-9c33-9d81e356bd29)
![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/b75a2da9-cc8a-411c-bd56-4bc3052752df)

I guess it's related to the recent ajson changes.

**Comment by choper725** [comment]
are you pulled to the latest demo repo?
this demo was changed like a week ago

**Comment by christianguenter2** [comment]
yes latest demo repo. Does it work for you?

![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/bcbad512-1828-499b-8ab5-fafec8ff19e3)
![grafik](https://github.com/abap2UI5/abap2UI5/assets/17437789/a1b54f9e-b2e3-4315-96e3-9eedb4da2bb9)

**Comment by oblomov-dev** [comment]
@christianguenter2 thank you for finding this, yes its a bug, i will check it and update it soon.

**Comment by oblomov-dev** [comment]
should be fixed now with https://github.com/abap2UI5/abap2UI5/pull/871 
expect some more bugs in the next days, i took the chance and did a lot of refactoring with the switch to ajson, just open an issue, thank you for bug hunting!

**Comment by christianguenter2** [comment]
Thanks for the fast response and the fix. Works. Thanks again for this amazing project.
