### ISSUE TITLE
favicon and jsDelivr

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#876]
@choper725 

checked the favicon demo more in detail, bootstrapping with jsDelivr - interesting idea.

I created a new folder:
https://github.com/abap2UI5/abap2UI5/tree/main/resources

The demos can now also load it from here and more files can be added:
<img width="1342" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/cf0be2c0-a788-45f2-ac65-35e8cacdba51">

Never thought about this approach before and also did not tried it out till now, maybe custom controls can also use this folder to load their min-js libraries?

**Comment by choper725** [comment]
yes, its a nice feature yet again.
well i just put local js data in there because of private network.
but this can be an option if you dont want to pull the latest

**Comment by oblomov-dev** [comment]
yes in private environments unfortunately this does not work, but good to have it as an additional option.
