### ISSUE TITLE
/abap2UI5-samples/tree/downport - many Type "XXX" is unknown

### ISSUE THREAD

**Issue by everton-demo** [abap2UI5/abap2UI5#879]
Hi @oblomov-dev ,

I tried to use https://github.com/abap2UI5/abap2UI5-samples/tree/downport, and the following errors occurred:

Object import failed.
Literals that take up more than one line are not permitted.
Z2UI5_CL_DEMO_APP_101 > Z2UI5_SET_DATA
Line 10.

Z2UI5_CL_DEMO_APP_113 > Z2UI5_SET_DATA
Line 66.

Z2UI5_CL_DEMO_APP_114 > Z2UI5_SET_DATA
Line 10.

I could easily correct these, but I'll share them if you want to adjust them at the source.

Below are others that I did not take action on:

Z2UI5_CL_DEMO_APP_060
Type "I_CurrencyText" is unknown
I believe it refers to CDS, perhaps this is not applicable to the version.

These are using other project objects, which are not contained in the version https://github.com/abap2UI5/abap2UI5-downport/tree/v_702:

Z2UI5_CL_DEMO_APP_066
Type "Z2UI5_CL_CC_MESSAGING" is unknown
z2ui5_cl_cc_messaging=>ty_t_items

Z2UI5_CL_DEMO_APP_102
Type "Z2UI5_CL_CC_BWIPJS" is unknown
z2ui5_cl_cc_bwipjs=>ty_t_barcode
z2ui5_cl_cc_bwipjs=>ty_s_barcode

Z2UI5_CL_DEMO_APP_119
Type "Z2UI5_CL_CC_DRIVER_JS" is unknown
z2ui5_cl_cc_driver_js=>ty_config
z2ui5_cl_cc_driver_js=>ty_config_steps

Z2UI5_CL_DEMO_APP_130
Type "Z2UI5_IF_TYPES" is unknown
z2ui5_if_types=>ty_t_name_value

Z2UI5_CL_DEMO_APP_135
Type "Z2UI5_CL_CC_MESSAGING" is unknown
z2ui5_cl_cc_messaging=>ty_t_items

Z2UI5_CL_DEMO_APP_142
Type "Z2UI5_CL_CC_IMAGEMAPSTER" is unknown

Z2UI5_CL_DEMO_APP_145
Type "Z2UI5_CL_CC_IMAGEMAPSTER" is unknown

Z2UI5_CL_DEMO_APP_147
Type "Z2UI5_CL_CC_CHARTJS" is unknown
z2ui5_cl_cc_chartjs=>ty_chart

Z2UI5_CL_DEMO_APP_148
Type "Z2UI5_CL_CC_CHARTJS" is unknown
z2ui5_cl_cc_chartjs=>ty_dataset
z2ui5_cl_cc_chartjs=>ty_chart

Thanks for all the support.

**Comment by larshp** [comment]
@everton-demo which version are you on exactly? and please post links to the exact source code, or include it in the description, so we have the same information on which statements are not working

**Comment by everton-demo** [comment]
Sorry @larshp , I mentioned oblomov because I was dealing with issue 807 with him, which we closed today.
I'm using environment 7.31, with https://github.com/abap2UI5/abap2UI5-downport/tree/v_702.
And the examples repository https://github.com/abap2UI5/abap2UI5-samples/tree/downport.

Below print of all errors.

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/c993eefa-32f4-45ac-949c-536bc47dbeb2)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/5779668f-c727-4429-8c3f-531f4d537128)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/ada2262b-f3bd-48f1-8b6f-8415551f5936)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/0f60046c-7ee8-4ce2-ab8c-eaf166d7a1a6)

Also used here:
![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/62295d24-f2b5-4878-8394-53b1207e0beb)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/6f664f61-164a-4f14-8c13-0122992d19e9)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/89072c46-9fb1-4cda-ba25-2c5c0b9e7e08)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/a9524ebe-c0e8-44b5-a439-0efd73d0a6d2)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/4dc8c655-fba5-49b8-a229-1e0660f617df)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/000914e4-266d-4201-a165-34c922094a1f)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/46937bde-f976-4700-8573-5efe5462dd86)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/de42ccc5-b02c-4b18-8458-d7f9c1ba612d)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/d64c0a23-1777-4d8b-9250-87e7a3a80554)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/560cddd8-b43a-40e8-a92c-e6ec4a3527f8)

Thanks

**Comment by everton-demo** [comment]
Another error, when I test an example:
![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/58264fae-17f9-4921-a243-8b5a08305ae5)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/159a5a03-8917-4c46-bcfd-ec182becfaea)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/ffe568c7-754c-4e0a-b287-d11b0d5bd1aa)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/b04b81bd-4619-457c-b7ad-a9a012564898)

I believe that in this version they are using ajson instead of /ui2/cl_json.

Thanks

**Comment by oblomov-dev** [comment]
yes i think @larshp meant here that you can better refer to the source code on github, like this:
https://github.com/abap2UI5/abap2UI5-samples/blob/fa3cc89fd2b65e7edc1ce0017fedbee145daac5e/src/z2ui5_cl_demo_app_001.clas.abap#L28

Then its automatically clear which project, branch and line you mean.

But in this special case your abap 7.32 se80-sapgui screenshots have also a certain grace ;)

Yes the demos with the specific Custom Controls will not work, deleted them for your release. But i will check the other issues and if i find a bug of the downporter, i will create an issue on abaplint.

**Comment by larshp** [comment]
so, the first error is this line? https://github.com/abap2UI5/abap2UI5-samples/blob/downport/src/z2ui5_cl_demo_app_101.clas.abap#L84

**Comment by oblomov-dev** [comment]
yes there the abaplint syntax checks does not show an error and the downport creates lines without adding a line break after &&. lets continue with this one here https://github.com/abaplint/abaplint/issues/3235

i will take a look to the other issues later.

**Comment by everton-demo** [comment]
Thanks for the tips, I'll try to reference them better if other problems arise.

**Comment by oblomov-dev** [comment]
the downported code of the samples are updated now, you can check this repository:
https://github.com/abap2UI5/abap2UI5-samples-downport

**Comment by larshp** [comment]
think https://github.com/abaplint/abaplint/pull/3245 will fix the `TYPE REF TO any` problems

**Comment by larshp** [comment]
update to latest and try again

**Comment by oblomov-dev** [comment]
thank you @larshp 

Updated the main repo with:
https://github.com/abap2UI5/abap2UI5/pull/919

And extended the documentation (two maunal steps now, delete image mapster and adjust the position of "where" in selects).

@everton-demo you can try again!

**Comment by larshp** [comment]
downport changes in commit https://github.com/abap2UI5/abap2UI5-downport/commit/b788fe8d8e26ac99bffb3bf23991dc035807ba48

**Comment by everton-demo** [comment]
Hi, everything is ok with the project, thank you.

The only problem I've encountered so far is opening this matchcode:
![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/7ea1f509-414a-4792-9c93-ca25af087303)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/8127569f-8a1b-41a3-b48a-aea150950004)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/a643d0d7-39d9-4bf6-b9db-68e6ffac16f1)

https://github.com/abap2UI5/abap2UI5-downport/blob/main/src/01/02/z2ui5_cl_core_app.clas.abap#L85
![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/2e227f5b-c061-4188-ac9f-ac58bcfac8e8)

I pulled the samples, most of them also ran fine!
Only errors like these occurred:
![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/daaa3e60-8d2b-49a8-99b2-23f01f21ad60)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/8de3b172-acfa-4cb2-b205-897d3aa00278)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/3b518468-99eb-4eb3-b040-641fb760c855)

I think it could be a firewall restriction on the network I'm using, but I'll share if you have any other suggestions.

thanks

**Comment by everton-demo** [comment]
Right, for value help I observe the indicated error.

Sorry if the question seems silly, but as for the elements not available in openUI5, is there anything I can do, or would it really not be possible to run in these downport projects?

If they are limitations, I understand that you can close the issue, I have no more to report.

Thanks!

**Comment by oblomov-dev** [comment]
No problem to ask.

In this case the demos do not work because of the frontend UI5 library you use. UI5 also does have multiple versions and flavors etc. Check it out here:
https://sapui5.hana.ondemand.com/#/api

Which one you want to use, you can setup here:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/faq.md#2-how-to-change-the-bootstrapping-of-ui5

Per default openUI5 is used, because i don't which version is on the system and which licenses does every customer have etc.

**Comment by everton-demo** [comment]
Cool, thanks for the explanation. I will read more about it to understand which version we are using, and whether it is possible to use a more current one.

Still referring to your previous message, for value help, I downloaded the S-RTTI project indicated in the message, but unfortunately it also requires objects that do not exist in our version. This may not be the ideal place for details, but these were the problems:

ZCX_SRTTI
https://github.com/sandraros/S-RTTI/blob/main/src/zcx_srtti.clas.abap#L9
![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/f4c0c15a-a7cd-455d-aec3-52ebb48680c9)

ZCL_SRTTI_ENUMDESCR
https://github.com/sandraros/S-RTTI/blob/main/src/zcl_srtti_enumdescr.clas.abap#L14
![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/10b78bbb-2d2b-40ab-a139-77a705576157)

Tomorrow I will be absent, any interaction I will only be able to respond after two days.

Thanks

**Comment by everton-demo** [comment]
I changed the branch, now we have another error:

ZCL_SRTTI_ELEMDESCR
https://github.com/sandraros/S-RTTI/blob/7.50/src/zcl_srtti_elemdescr.clas.testclasses.abap#L80
![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/8f6ea83f-230b-47dc-9057-854783dacdfa)

![image](https://github.com/abap2UI5/abap2UI5/assets/13936273/1fa54935-1b58-4ffd-bc00-f359b9b676c7)

**Comment by oblomov-dev** [comment]
yes you need a lower version than 7.50 without int8. i already asked for this here:
https://github.com/sandraros/S-RTTI/issues/5

But it seems not be created so far, maybe you can ask one more time in the S-RTTI repository for this? We could also easily solve this by ourselves here but i don't want to create redundancies and this should be part of S-RTTI itself.

**Comment by everton-demo** [comment]
Yes, I understand perfectly, thanks for the reference and all the support. I will interact there.

**Comment by oblomov-dev** [comment]
nice that looks good! so by now all issues are fixed?

**Comment by everton-demo** [comment]
Yes, thanks! I just have the task of reading more about the frontend UI5 libraries, but the issue can be closed.

**Comment by oblomov-dev** [comment]
yes there is a lot to explore, all frontend and backend complexity in one project but after making it run for the first time it gets easier. just open an issue again if you need more help. thank you for your documentation of the problems with your 7.3x release, abap2UI5 got a lot more compatible with this issue. best regards.
