### ISSUE TITLE
refactoring changes & additions

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#882]
hi @oblomov-dev 

i see that alot of changes are being made,
is it possible if you got time, to explain whats been changed, or added to the framework ?

**Comment by oblomov-dev** [comment]
yes of course! But nothing new added so far, just try to clean up everything to make the codebase easier to maintain. 

(1)
Splitting up the logic into smaller classes, for example this folder is new:
https://github.com/abap2UI5/abap2UI5/tree/main/src/01/02/01

Before the logic of these classes was contained in other ones and the classes had mixed tasks. try now to have single classes for every task, eg. creating the json, searching for class attributes, binding logic...

(2)
Changed the payloads of requests and responses, they are smaller now and reduced only to the needed information (eg. deleted new lines in the xml, shorted the event notation...)

(3)
Try to clean up some redundant code which was added from time to time.

(4)
Added more unit tests and static code checks. For example:
https://github.com/abap2UI5/abap2UI5/blob/main/src/01/02/z2ui5_cl_core_http_get.clas.testclasses.abap

And some renaming etc.

Hope it breaks nothing! Still work in progress...

**Comment by oblomov-dev** [comment]
Besides that, added just now the source code view for the debugger tools:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/9dd8078b-2c2d-45c4-9f49-719e20b8c4a1">

**Comment by oblomov-dev** [comment]
lets continue in the more specific issues now...
