### ISSUE TITLE
UI Table usage with Variant Manger

### ISSUE THREAD

**Issue by Marchl-Woid** [abap2UI5/abap2UI5#887]
Hello togehter,
I'm not sure, if I can't figure it out, or if there is something not working.
I want to build a protoype similar to the Demo z2ui5_cl_demo_app_100:

Uasage of the ui_table Element for filtering etc. and the Variant Manager for savinging the setting as reusable variant.

On the first sight, it looks like he can save it:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/937a6895-8ec3-4e5c-b485-dc05a6aad417)

But if I switch between the variants nothing happens. And also I didn't find out, how to make it persistent, means that the variants are available also after refresh or new entry.

Last thing would be, to hide column and save it like a variant, but this would be the second step..

Thanks in advance

**Comment by choper725** [comment]
left this project of variant management as this seems to not work correctly with a2ui5,

infact anything with presistence seems to behave wierd, and also it looks like it needs to be run via launchpad in order to make everything work

**Comment by Marchl-Woid** [comment]
Hello @choper725 
ah okay. Means it is more ore less obolete, right? Thanks for the quick response

**Comment by abapsheep** [comment]
Hi @Marchl-Woid, 
I am currently working on a generic layout function. I have not yet found a possibility at the frontend. If you give me another week, I can provide you with the function I am currently working on. ;)

**Comment by choper725** [comment]
its not obsolete its just wasnt able to figure out how to make it work with frontend only,
you can check the p13n demo, if i remember correctly that was the latest try on presistence

**Comment by oblomov-dev** [comment]
yes i think you need some frontend logic and maybe a specific odata service to save the layout for it. there might be the possibility to develop a Custom control for this, but i want to keep abap2UI5 as a backend framework, and also keep most of the logic there. So i did not put more effort into it.

@abapsheep yes implementing this in the backend sounds good, if needed, take example 165 as an orientation.

**Comment by Marchl-Woid** [comment]
Hi toghether, 
thanks for your quick answers. 

@abapsheep : I'm curious to see your approach. I was think of building something by me self, but then I will wait :) 
My idea would have been a attribute of type ref to data and generical creating the fields of the structure depending and die Fields of the table and then binding the fields to the column attributes like visible. Then a popup as setting on te table, where the user can set some attribute to the columns. Persistance would be a simple name value table withe the view class a key.

**Comment by abapsheep** [comment]
Hi @Marchl-Woid, 

I'm ready, have a look at the samples app z2ui5_cl_demo_app_174. 

![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/b7a661b7-8226-48f5-9c65-6f754ebf62ae)
![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/cd43aa27-c8d6-46f4-93d3-7bb1f961beb4)

My first approach was also to build a generic structure, but @oblomov-dev was so good and added table cell binding for us. That made things much easier.  If you have any ideas or suggestions for improvement, please let me know ;)

**Comment by choper725** [comment]
its row or column there in the title ??

**Comment by Marchl-Woid** [comment]
HI @abapsheep 
wow, great work. I had to play around with it rigth away. :) 

First thing what happend was this error I got:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/29e1a313-68c1-4600-b772-da23115bac13)
The reason was the ->footer Method in the Popup, I just removed it, then it work fine.


I played around with it a little bit, I changed this two code snippets:

![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/7d55cc58-c891-41f5-b6e5-9f810ce9fd9b)

and 

![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/d307bf10-d7d5-4049-9cad-4ae87a32cf2c)

The reason is quite easy. If I use a DDIC type for my table strucutre, the texts come from the data element. I tried it out with your sample and change for product the data type from string to data element matnr:

Effect is quite nice:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/3710e6bb-8b71-4138-a2ec-cf58eb457b8f)

Names and texts are translated and are euqal to the other places where they are used. If you also like it, maybe you can just adopt the code.

Next thing I'm thinking of, how to use it with the UI_TABLE Element. The class sap.ui.table.Column has properties for visibility, align. So this should be easy. It don't know yet if it's work, but what would be genius, if you can also save as layout the column poisiton in the table and sorting and filtering.

I have seen, that the width is part of the properties and of the DB Table, but it is commented out in the UI. Is there a specific reason for that?

**Comment by abapsheep** [comment]
Hi @Marchl-Woid, 
the layout function is a first attempt. Depending on the UI element, you could of course add or hide columns, good idea. 
I have built the function so that it can theoretically also run in the cloud. There are no DFIES here, so only via detours and therefore I have left out the topic of texts for now ;) 
For me, I also need the warehouse number to control the layouts. Here I will see if I can solve this via handels as in the SAP ALV.
Why you get an error with the footer is unclear to me.

**Comment by oblomov-dev** [comment]
concerning the footer:
@Marchl-Woid do you bootstrap with openUI5? @abapsheep did you test with openUI5? very often this creates some problems with certain controls.

**Comment by Marchl-Woid** [comment]
HI @oblomov-dev ,
no I'm unsing an onPrem System with the local UI5 libs:
/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js

**Comment by oblomov-dev** [comment]
can you check the UI5 version by clicking:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/9e1e617e-8396-494b-aa87-998e11bc7e73">
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/a917ad06-82da-42d7-9084-63a6bddd19cf">

**Comment by Marchl-Woid** [comment]
HI @oblomov-dev 
if I use this, I get this message:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/6a74152f-9880-406c-b156-576cfe5d16c4)

But you search this one, I assume:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/a20e53cc-cfcc-4c2e-bff4-6c33f0564e28)

**Comment by oblomov-dev** [comment]
thank you, yes this is what i was looking. seems we need to make it more release compatible, i'll check this.

**Comment by oblomov-dev** [comment]
@abapsheep which version are you using? 

sap/m/footer seems not to be available on lower releases, possible workaround using beginbutton/endbutton as it is for example done here:
https://github.com/abap2UI5/abap2UI5/blob/9b48c01acd2f4c13c6cf803fba8972041cb79e8b/src/01/03/z2ui5_cl_core_app_info.clas.abap#L107

**Comment by choper725** [comment]
hi @abapsheep 
something wierd is happening,
upon loading a layout the order of the rows change

1. 1st load
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/51e651e8-d649-45ca-ac56-9ed4439897bd)

2. 2nd load
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/a1d6dd2e-b644-4ae7-8513-28b74f2b3049)

the order of the columns is changing, hence once changing the entire table order...

**Comment by abapsheep** [comment]
Hi everyone,
I'd like to take a further look at this topic. I already have a few extensions in mind. But I'm currently facing a big go-live that will keep me busy for at least the next 2 weeks.

**Comment by choper725** [comment]
@abapsheep 
surly, when you find the time for it.

digging around found that:
upon first load from demo 174 table columns are arranged per the TT binded to the table. (as expected).

  METHOD init_layout. work as expected.

once loading a variant from the db, columns get mixed,
the issue lies upon saving the layout to the db, as in the db the order gets changed:
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/606c1c81-6e00-4e18-b059-7aeab5b95ad9)

hope this helps..
