### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by abapsheep** [abap2UI5/abap2UI5#891]
Hi @oblomov-dev, 

have you already tryed templating? 

PLNKR:
https://embed.plnkr.co/plunk/vp8zcW

I created a Demo App, but I cant make it work. 
https://github.com/abap2UI5/abap2UI5-samples/pull/113

any Ideas?

**Comment by choper725** [comment]
i think changes should be made to the xml view in order for it to work,
need to define preprocessor in the xml view creation..

**Comment by oblomov-dev** [comment]
yes seems you need to import the model also as the meta model in the view creation, before it can work. Need to check this more.

**Comment by choper725** [comment]
@oblomov-dev 
take a look at,
https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.core.mvc.XMLView%23methods/sap.ui.core.mvc.XMLView.registerPreprocessor
seems to be possible to tie it glogaly, 
maybe with a cc once needed ??

**Comment by oblomov-dev** [comment]
thank you for the link. unfortunately get this error all the time:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/5ac24080-4bf6-47df-9583-722dddb180a3">

@choper725 can you start demo z2ui5_cl_demo_app_173, are the ressources loadable on your side?

this link seems not to work:
http://schemas.sap.com/sapui5/extension/sap.ui.core.template/1

**Comment by choper725** [comment]
maybe its not on openui5 ??

**Comment by choper725** [comment]
> checked both.

ill check on my end

**Comment by choper725** [comment]
hi @oblomov-dev ,

once adding (and reodering the model binding) this to http_get class.
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/a85a3dcc-b402-4095-aa3f-3b6fea8cdc3d)

demo 173 works
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/34223572-6a24-4303-a184-fc4cd06e0db8)

**Comment by oblomov-dev** [comment]
Nice! Then the problem was that I did not add the metamodel beforehand. Cool! thank you for checking this out. Feel free to to send a PR with the change, but otherwise I can also add this single line on my end.

**Comment by oblomov-dev** [comment]
ok added now with https://github.com/abap2UI5/abap2UI5/pull/925/files/9d8eb1578f8c0068617afccc1beb5c9db242ad47..3ccbc2eb1a35dcdb0c7e93bbf75eab9b15ac23b7

@choper725 thank you for your help. i still get the module load error. with which ui5 version are you bootstrapping?

@abapsheep you can give it a try.

**Comment by choper725** [comment]
the latest sapui5 version

**Comment by choper725** [comment]
if this works fine, this should be added to all views creations

**Comment by choper725** [comment]
was a typo in http_get class,
fixed it with #940

**Comment by oblomov-dev** [comment]
nice, thanks for the PR. this one was hard to find, did not see that an "s" was missing and the error did not tell me. now it works:
<img width="1728" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/6764bca9-9730-419e-8d93-ba85191164de">
@abapsheep now you can give it a try!

**Comment by abapsheep** [comment]
Hi @choper725,
thanks for your contribution, great work! I have built a slightly larger example and immediately run into problems. Unfortunately, I'm not really sure where the problem might lie. I have simply extended the class z2ui5_cl_demo_app_173 a little for the example.


CLASS z2ui5_cl_demo_app_173 DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES z2ui5_if_app.

    TYPES:
      BEGIN OF ty_s_data,
        name TYPE string,
        DATE type string,
        AGE  type string,
      END OF ty_s_data,
      ty_t_data TYPE STANDARD TABLE OF ty_s_data WITH EMPTY KEY.

    TYPES:
      BEGIN OF ty_s_layout,
        FNAME      type string,
        merge      TYPE string,
        visible    TYPE string,
      END OF ty_s_layout,
      ty_t_layout TYPE STANDARD TABLE OF ty_s_layout WITH EMPTY KEY.

    DATA mt_layout TYPE ty_t_layout.
    DATA mt_data   TYPE ty_t_data.

PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS z2ui5_cl_demo_app_173 IMPLEMENTATION.

  METHOD z2ui5_if_app~main.

    client->_bind( mt_data ).
    client->_bind( mt_layout ).

    mt_data = VALUE #( ( name = 'Theo' date = '01.01.2000' age = '5' )
                       ( name = 'Lore' date = '01.01.2000' age = '1' ) ).

    mt_layout = VALUE #( ( fname = 'NAME' merge = 'false' visible = 'true' )
                         ( fname = 'NAME' merge = 'false' visible = 'true' )
                         ( fname = 'DATE' merge = 'false' visible = 'true' )
                         ( fname = 'AGE'  merge = 'false' visible = 'false' ) ).

    DATA(xml) =
`<mvc:View xmlns="sap.m " xmlns:core="sap.ui.core " xmlns:mvc="sap.ui.core.mvc " displayBlock="true " height="100% ">` &&
`  <Shell>` &&
`    <Page>` &&
`      <Table items="{/MT_DATA}">` &&
`        <columns>` &&
`          <template:repeat list="{meta>/MT_LAYOUT} " var="MT_LAYOUT">` &&
`            <Column` &&
`           mergeDuplicates="{MT_LAYOUT>MERGE}"` &&
`           visible="{MT_LAYOUT>VISIBLE}"/>` &&
`          </template:repeat>` &&
`        </columns>` &&
`        <items>` &&
`          <ColumnListItem>` &&
`            <cells>` &&
`              <template:repeat list="{meta>/MT_LAYOUT}" var="MT_LAYOUT">` &&
`                <ObjectIdentifier text="{MT_LAYOUT>FNAME}"/>` &&
`              </template:repeat>` &&
`            </cells>` &&
`          </ColumnListItem>` &&
`        </items>` &&
`      </Table>` &&
`    </Page>` &&
`  </Shell>` &&
`</mvc:View> `.

    client->view_display( xml ).

  ENDMETHOD.

ENDCLASS.


Would be nice if you could take a look at the example, thanks in advance!

**Comment by choper725** [comment]
try prefixing the meta in the binding, like it is in the plnkr link above

**Comment by abapsheep** [comment]
Hi @choper725,

PR is done. Thanks alot

**Comment by choper725** [comment]
sent a pr , and added template to xml_view

see demo 173
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/3b5aad4c-f7fb-4549-aaf6-1a0fd8a961fa)

**Comment by abapsheep** [comment]
Hey @choper725, 
super cool, thanks. But I'm afraid it doesn't quite fit yet. 
![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/f9846cc4-f71b-4036-b389-d4d88d53880e)
Currently only the column names are displayed and not the actual values. 
![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/44be19fd-5cdd-4a83-9813-0595e70935bb)

For now I added a workaround, maybe you have an idea how to solve this more effectively. I did not manage to set the Binding Value in extra {} 
![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/a8cfb4ef-3241-484b-afe4-a123882ad9c0)

I also added the possibility to use templating in Nested Views.
![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/fd707e7e-3643-4ab5-839a-4b20c231427b)

**Comment by abapsheep** [comment]
Hi @choper725,

I have tried the whole thing in the Nested View but unfortunately I get an error message here. 
Sample Z2UI5_CL_DEMO_APP_176
![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/a7ee6e39-d5b9-46a3-bc48-50e5502c460a)


I have changed Z2UI5_CL_CORE_HTTP_GET:
![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/dbc7db6a-8c61-4a94-b42d-d4a307c3a252)
Maybe you can think of some ideas ;)

Thanks.

**Comment by oblomov-dev** [comment]
thank you for your help and PRs @choper725 and for the demos and trying this out @abapsheep 

fyi demo 176 works on my side:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/3508e2c6-ad69-4c8f-a757-f05de48a1ef5">

**Comment by choper725** [comment]
hi @abapsheep

as far as i understand this template control,
the table you binded in the list of repeat and the table you binded to the table are different, you must reorder the data in the tables or refer to the binded table of the table control in the repeat control.

what you expect the table to be.  ?
can you sketch it so i can understand ?

regarding template in nested view ill table a look at it.

**Comment by abapsheep** [comment]
hi @choper725, 

the Text value of the object_identifier defines the binding to on table row. This values needs to be in "{ }".
```abap 
             )->object_identifier( text = `{LO2>BINDING}` ).
```
But using the templating syntax I found no way of getting it done. It's a workaround, but honestly not that nice.

The sample Z2UI5_CL_DEMO_APP_173 works fine now, by adding a row with the value already in "{ }". 

![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/5f49d428-ccbb-4468-9963-7f6a16d2f05a)

**Comment by choper725** [comment]
i dont think this is how it suppose to work,
i think the problem is in the logic of the tables, you want to repeat and build a table based on a different table if i understand correctly,
not sure if thats the way to do so..
if you join the data and the layout table toghther it should work as you expect

**Comment by abapsheep** [comment]
@choper725 

```abap 
 )->object_identifier( text = `{= '{' + ${LO2>FNAME} + '}' }` ).
```
this is what I was loking for :) 

Hmm I am still getting the error in Demo 176
![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/67e0481a-bfd5-4ab3-92b0-15ae7dc89eaa)
I will do some more research

**Comment by choper725** [comment]
bot really sure why is that… as on my end its works fine in nested view..

btw, @oblomov-dev as far as i know in fragment template should not work as its implemented differently..

**Comment by oblomov-dev** [comment]
thank you @choper725 for the hint, did not check this further and just added it to the fragment too. now removed it again with: https://github.com/abap2UI5/abap2UI5/pull/961
as i saw it here, unfortunately its not possible without further actions in popups:
https://community.sap.com/t5/technology-blogs-by-members/sapui5-using-xml-templating-with-fragments/ba-p/13355809

btw. 176 works also on my end.

**Comment by choper725** [comment]
hi @abapsheep 

check pr #964 + recent pr in demo repo for templating changes made + extra feature in deubgger.

cheers.

**Comment by oblomov-dev** [comment]
@choper725 hmm are you sure this this running as expected?
at the moment i can not see tables etc. when not using templating:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/d517631f-20fe-47f7-8dd2-08cc23a6fca4">

**Comment by abapsheep** [comment]
@choper725, @oblomov-dev, 
Dumbest mistake to think of, The JS was blocked due to security guidelines of Compay. Now everything works, I don't get any more error messages. :)

**Comment by choper725** [comment]
great, can we change back rhe meta to undefined ?
this shouldnt have break things anyway, its just semantic upon binding

**Comment by oblomov-dev** [comment]
when i switch back to undefined my normal tables are empty, check for example demo 019:
<img width="1344" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/55950a12-bd5a-425c-9059-f7fe14859fb5">

**Comment by choper725** [comment]
well, its shouldnt have any issue with the default model, anyway if this the issue, i guesa maybe changing the meta model name to template might be more meaningful

**Comment by oblomov-dev** [comment]
means you can also reproduce the problem on your side? too bad, because leaving the name away was in general a nice idea.
but yes i am flexible with the name if template fits better, just feel free to change it and send a PR.

**Comment by choper725** [comment]
ill try reproduce it on my side see whats wrong, and pr accordingly.

**Comment by oblomov-dev** [comment]
@choper725 thank you for your work, checked both, works fine on my side!
fyi - adjusted the demos slightly (added back button+title etc)

@abapsheep works for you too? can we close this issue?

**Comment by abapsheep** [comment]
Sorry, a go-live came in between. I have tested everything and everything works for me now. Thank you all.
