### ISSUE TITLE
Thousands separators in text and input fields

### ISSUE THREAD

**Issue by LadwigDev** [abap2UI5/abap2UI5#907]
Hi,
I just showed a preview of an ABAP2UI5 app to one of our users and he asked me if there is a possibility to add thousands separators to the numbers I am displaying in the text and input fields. It is not possible to achieve this with CSS and I would like to renounce doing the conversion in the backend for every roundtrip. Is there a possibility to achieve this using JS so that the values stay the same and the dots are added only for displaying purposes by the browser? Unfortunately I have no JS experience, otherwise I would try to add this functionality to the framework myself.

(Field USR01-DCPFM as source for the notation like in dynpro applications)

Best regards
Jan

**Comment by choper725** [comment]
look at Number format type in the sdk, you can do so also in abap2ui5 via binding

https://sapui5.hana.ondemand.com/#/api/sap.ui.core.format.NumberFormat%23methods/sap.ui.core.format.NumberFormat.getFloatInstance

**Comment by oblomov-dev** [comment]
yes ui5 delivers multiple possibilities for this, check also the following demos:
Z2UI5_CL_DEMO_APP_047
Z2UI5_CL_DEMO_APP_067
Maybe this is what you need?

**Comment by LadwigDev** [comment]
Yeah, I think the contents of App 067 are what I need. But is this also possible with ui5.table columns, because I am not using the _bind method there but instead I am referencing the columns of the internal table by using {COLUMN_NAME}

Can you give an example for the syntax with sap.ui.model.type.Integer with the format option groupingSeparator in Demo 160?

Your help is much appreciated
Thanks

**Comment by choper725** [comment]
yes its possible also in a table its the same syntax

**Comment by LadwigDev** [comment]
I have tried it like this now but it seems I am missing something. Here is a snippet of the XML from the debugging tools:

      <table:Table alternateRowColors="true" fixedRowCount="1" rows="{/EDIT/MT_OUTPUT}" selectionMode="None" visibleRowCountMode="Auto">
        <table:columns>
          <table:Column filterProperty="IS_TOTAL" sortProperty="IS_TOTAL" width="5rem">
            <Text text="Ist"/>
            <table:template>
              <Text text="{ parts: ['{IS_TOTAL}'], type: 'sap.ui.model.type.Integer', formatOptions: { groupingSeparator: &quot;.&quot; } }"/>
            </table:template>
          </table:Column>

**Comment by choper725** [comment]
remove the curly braces of IS_TOTAL it should work, but maybe there is another problem in the binding

@oblomov-dev

**Comment by oblomov-dev** [comment]
you can also check demo 66, there the parts command is used. And if it still does not work on your side, maybe you can make a little example app and paste it here. then we can copy&paste it to our system and take a look.

**Comment by LadwigDev** [comment]
I was able to solve the problem. For sap.ui.model.type.Integer you have to use "path" instead of parts, remove the curly braces as @choper725 said and additionally you have to provide the format Option "groupingEnabled" with the value true.

So for anyone reading this and interested in achieving the correct result, this would be the syntax:

->text( text = `{ path: 'IS_TOTAL', type: 'sap.ui.model.type.Integer', formatOptions: { groupingSeparator: '.', groupingEnabled: true } } ` )

**Comment by oblomov-dev** [comment]
nice, thank you for sharing the solution!
