### ISSUE TITLE
imagemap demo issue

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#913]
regarding previous binding topic,

see demo 142 for /EDIT/ usage as an expression.
which now works with /XX/ ... but this seems to be a breaking change ..

previously invoking an event outside of the controller used to work like this
 `sap.z2ui5.oController.onEvent( { 'EVENT' : 'TEST', 'METHOD' : 'UPDATE' , 'CHECK_VIEW_DESTROY' : false })`

i know it was changed, just dont really know to what..

**Comment by choper725** [comment]
yes l try to do that

**Comment by oblomov-dev** [comment]
and if there is the chance, the best would be if you use the event function, it gives you back the exact string, means:
```
client->_event( "MY_EVENT") 
```
should return:
```
oB(["MY_EVENT"])
```
And when you use this returning parameter, i can change the event string in the future easily without messing up your funcitonality.

Same for the binding:
```
client->_bind_edit( mv_val )
```
gives back the correct string:
```
/XX/MY_VAL
```
etc.

**Comment by choper725** [comment]
> and if there is the chance, the best would be if you use the event function, it gives you back the exact string, means:
> 
> ```
> client->_event( "MY_EVENT") 
> ```
> 
> should return:
> 
> ```
> oB(["MY_EVENT"])
> ```
> 
> And when you use this returning parameter, i can change the event string in the future easily without messing up your funcitonality.
> 
> Same for the binding:
> 
> ```
> client->_bind_edit( mv_val )
> ```
> 
> gives back the correct string:
> 
> ```
> /XX/MY_VAL
> ```
> 
> etc.

ill check if it work in this context, or a cc will be needed for that

**Comment by choper725** [comment]
created a PR with fixes

**Comment by oblomov-dev** [comment]
Thank you for the PR!
