### ISSUE TITLE
demo 66 binding issue

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#914]
hi @oblomov-dev 

got an unexpected behavior in demo 66,

once typing in the input of the nested view and pressing the event button, a toast with the value should apper,
but instead the valule gets deleted,

i remeber this issue once we started implementing nested view, and nested bindings... and you fixed it before of course..

**Comment by oblomov-dev** [comment]
looks like the same problem we have in this issue:
https://github.com/abap2UI5/abap2UI5/issues/916#issuecomment-1953865965

Message Manager works:
<img width="898" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/887db9e3-3b78-4183-9c13-4b04269b7c42">
But field is not written in the model:
<img width="700" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/b8579792-c84e-452b-95c7-4cc17ed7633b">
But naming looks correct:
<img width="700" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/bf750b3b-7701-4a18-8625-1db92692b059">

**Comment by oblomov-dev** [comment]
should be fixed with https://github.com/abap2UI5/abap2UI5/pull/923

**Comment by choper725** [comment]
well, its still not working on my side in demo 66...

**Comment by choper725** [comment]
btw,

every time the messaging occur the entire screen is re-rendering.. not sure why thats happening..

**Comment by oblomov-dev** [comment]
good to know, i will try to check this in the next days.

**Comment by choper725** [comment]
> good to know, i will try to check this in the next days.

great, thx, maybe its something with the CC ??

**Comment by oblomov-dev** [comment]
checked it again, yes the cc seems to be the problem. the following lines create somehow the rerendering:
https://github.com/abap2UI5/abap2UI5/blob/f6acde18093325b1798af5b6e831d435cc5dc586/src/01/05/z2ui5_cl_cc_messaging.clas.abap#L104

now they are deactivated, and rerendering only appears after a roundtrip (which is still not perfect). Demo 135 also needs a roundtrip now before the model gets updated. Mhhh not sure if this is solvable and what could be a good compromise here.

did the old message manager also cause this problems? maybe its a bug in the new version?

**Comment by choper725** [comment]
i checked the old one didnt rerender,
and yes its the cc like you said.

rerendering is not part of message manager only value state change and “builtin” model update.

ill check it later and post back

**Comment by oblomov-dev** [comment]
what do you mean exactly with "only for the binded table", isn't this what we are doing?

i also used the resBinding.attachChange command in this context the first time, so I am sure there might be more elegant ways.

**Comment by choper725** [comment]
yes what i was asking is that without full roundtrip,
what i did t checked is if this happen on previous sdk versions with this cc ( the one i did for older versions).

attachChange also did full roundtrip ?

**Comment by oblomov-dev** [comment]
yes i also would not call myself an UI5 expert too, so messing around till it works is also most of the time my way to go ;)

ok attachChange causes the rerendering... too bad because we need this to find out if the model of the message manager changes.

**Comment by choper725** [comment]
yeah was messing around with it also, didnt work on my end :/

so i guess forced call to update the model is the way to go ?

**Comment by oblomov-dev** [comment]
yes so far i have no more ideas than the ones i showed here, but i also don't use the message manager as much as you till now i think, so feel free to change the message manager as it fits best for your needs.

**Comment by choper725** [comment]
i didnt reqlly did tests on what tou changed, but if it works just upon model update its ok i guess..
ill run tests today and update the same in the old message manager cc..

**Comment by oblomov-dev** [comment]
yes but the only downside is that demo 135 behaves slightly different now, but you could also keep both logics and activate the one you need via property in the backend depending on your app. so yes... just check it out and implement it as needed.

**Comment by choper725** [comment]
ill see what you did on messaging and test out demo 66 and fix demo 135,
btw, how can i know which sdk runtime version is runinng??

**Comment by oblomov-dev** [comment]
i read it in a custom control:
z2ui5_cl_fw_cc_info_frontend
and here is an example how i get the information in the backend:
z2ui5_cl_core_app_info

but there might be better ways...

**Comment by oblomov-dev** [comment]
nice, thank you very much for the study! yes never used this third parameter before and never expected that this could cause this behaviour. But good to know now that it helps in this specific situation :)
