### ISSUE TITLE
Missing types z2ui5_if_ajson_mapping and z2ui5_cl_xml_view_cc

### ISSUE THREAD

**Issue by lautor80** [abap2UI5/abap2UI5#918]
After downloading the packages ABAP2UI5 and ABAP2UI5_EXAMPLES the activation is failing due to missing types

- z2ui5_cl_xml_view_cc
- z2ui5_if_ajson_mapping

In addition to that the index file is not found. 

I pull the latest version as of this morning.

**Comment by lautor80** [comment]
Hi,
thanks for you fast response! 

I added the class and the interface manually. During activation it reports further more missing objects. 
Please find attached the screenshots.
![Z2UI5_CL_XML_VIEW_CC](https://github.com/abap2UI5/abap2UI5/assets/64456153/2e449c6e-19ab-441a-bbd6-75f93cb6f32a)
![Z2UI5_IF_AJSON_MAPPING](https://github.com/abap2UI5/abap2UI5/assets/64456153/e9856bda-caac-4f85-a067-0bbcad2ea840)

**Comment by oblomov-dev** [comment]
Hi @lautor80,
ok i think then something with abapgit or the installation is wrong. It seems that the classes are not pulled correctly. 

Can you start abapgit, go into the abap2UI5 project and refresh the view again? Normally you can see there the classes in your system compared to the classes in the remote repository. And at the moment you should see some diferences.

**Comment by oblomov-dev** [comment]
did you create a new http handler? 

you can also install this repository instead:
https://github.com/abap2UI5/abap2UI5-launchpad_proxy_app

**Comment by lautor80** [comment]
It worked quite well and is up and running now.
Thanks for the super support !
