### ISSUE TITLE
New Search App and Customer Namespaces "/" are not working

### ISSUE THREAD

**Issue by abapsheep** [abap2UI5/abap2UI5#921]
Hi @oblomov-dev,

I found a Error in the new Search App - please check.
I guess it is the NameSpace, the slashes seem to create a probelm (/***/)

![image](https://github.com/abap2UI5/abap2UI5/assets/135960093/15588d21-c8a9-4b0d-801f-b117e07fb0fa)

Thanks in advance!

**Comment by oblomov-dev** [comment]
fixed with:
https://github.com/abap2UI5/abap2UI5/pull/922

you can try again.

**Comment by abapsheep** [comment]
Runs perfectly, thanks!
