### ISSUE TITLE
Sample 80 - Planning Calender no data

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#968]
z2ui5_cl_demo_app_080 - no data
checked it quickly, but so for everything looks fine, @choper725 if you have a quick guess let me know.
i think something changed because of the new JSON handling. maybe uppercase/lower case problem somewhere...

<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/2215b69c-7ab5-4006-ace5-30d00a0b88b0">
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/e551f3d6-352e-483b-8cdf-4d3a60322c91">
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/75f8a91f-82bd-47e3-8013-b5007232f147">

**Comment by choper725** [comment]
long time since working on that, feels like ages !!
if i remember correctly something with the dates ??
nothing on console ??

**Comment by oblomov-dev** [comment]
console looks good (no messages). its maybe something with the Helper function and date and its probably not the JSON change which messed it up, it might be the changes for Fiori 2.0 but i am sure i tested this... mhh i try to check this more.

and yes some demos feel also for me like created it ages ago

**Comment by oblomov-dev** [comment]
defined here:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/69c55360-dc42-4355-8932-9bf127435fd7">

creates this:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/2f422b8a-9b34-4c14-bed6-9b03307f6074">

**Comment by choper725** [comment]
getting some errors once i change 
the bind_local to bind on here
` rows = `{path: '` && client->_bind( val = lt_people path = abap_true ) && `'}``

**Comment by choper725** [comment]
let me pull again and check,

the busy indicator i got once i got abap error upon binding..

**Comment by choper725** [comment]
fixed with latest pr in demos.

but this means that _bind_local is broken ??

**Comment by oblomov-dev** [comment]
Ab it was again the Boolean, thank you for finding this. Then the error came with the json change. 

Now I think it should also work with local binding (there was just randomly a general bug I found and fixed)

**Comment by choper725** [comment]
just checked nott working with bind_local... getting no data again...

**Comment by oblomov-dev** [comment]
Ok thanks for the hint, I'll check and fix this.

**Comment by choper725** [comment]
i also think its not a2ui5 related.

**Comment by oblomov-dev** [comment]
ok so lets close this for now, and reopen if it somehow makes sense to investigate it further.
