### ISSUE TITLE
Binding of variables of type p / Generic Tile

### ISSUE THREAD

**Issue by LadwigDev** [abap2UI5/abap2UI5#975]
Hi,
I have two findings:

1) It seems that it works to transfer variables of type p from backend to frontend but not vice versa (s. Demo App 047). If I am correct the issue is that the value is assigned to a field symbol of type any but in order for this to work a casting type needs to be added, otherwise the value of the field symbol will be 0
-> `ASSIGN COMPONENT a OF structure <b>  TO <c> CASTING TYPE p DECIMALS i.`
(maybe there is also a better solution)

2) Is there a reason why the generic_tile method returns "me" instead of the result of the _generic method? If you want to add tile content below it you first have to use the get_child method because of this.
<img width="584" alt="Capture" src="https://github.com/abap2UI5/abap2UI5/assets/155659152/c68483b9-e672-435e-b130-392fdd9fc220">

Best regards

**Comment by oblomov-dev** [comment]
hi @LadwigDev,

thank you for the findings!

(1) could reproduce the first error in demo 47, will fix this.
(2) yes sometimes the controls return itself, sometimes their child. there is no specific rule, i just made it depending if its more common to continue with the child (e.g. toolbar) or just continue with a new control on the same level (e.g. content). i think this case is on the edge: when you want to add multiple tiles it is easier as it is now but if you always want to add additional content then your idea would be better. 

best regards.

**Comment by LadwigDev** [comment]
Thanks a lot!

(2) Ah I see, this makes sense. You just have to know it :)
