### ISSUE TITLE
Actual Changes

### ISSUE THREAD

**Issue by oblomov-dev** [abap2UI5/abap2UI5#981]
@choper725 @abapsheep 

(1)
Someone using the "check_view_destroy" parameter of the _event method?
https://github.com/abap2UI5/abap2UI5/blob/c045cd1805ab79ddf6ba084c9a302e94bf78b876/src/02/z2ui5_if_client.intf.abap#L110

It is replaced now with the following control structure and i would delete this importing parameter soon:
https://github.com/abap2UI5/abap2UI5-samples/blob/ea41cf116ba350d732adda1ac9977ab7e61abedb/src/z2ui5_cl_demo_app_001.clas.abap#L32

This structure can now be extended with additonal control flags in the future.

(2)
It is now possible to send requests to the backend before the processing of the previous request is finished, as it is done here:
https://github.com/abap2UI5/abap2UI5-samples/blob/ea41cf116ba350d732adda1ac9977ab7e61abedb/src/z2ui5_cl_demo_app_059.clas.abap#L126
For example helpful when users make inputs and you want to show suggestion always on the latest changes of the input field.
Check demo 59:
![gif_multi](https://github.com/abap2UI5/abap2UI5/assets/102328295/48ede887-d6f5-4b04-b393-38d276fc2603)

(3)
We were running often into compatibility problems concerning the UI5 version. I adjusted now the abap2UI5 core apps that they are compatible from very low to very high UI5 releases and they are independent from UI5 and OpenUI5:
<img width="379" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/82d43d58-73d2-4bfa-b01a-cf5c67225452">

That's why i replaced for example the Illustrated Message in the Error Popup which is less beautiful but compatible to all UI5 versions:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/2b2eaa68-5dee-42db-a60e-c206dea389a8">
 
Running now from the old version 1.6 to the newest 2.x (nightly).

(4)
Adjusted the sample section, all samples listed here are now also compatible to UI5/OpenUI5 and are release independent:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/1e53c155-224f-48d0-baae-e3af6859e95d">

Version and release specific Samples are collected here:
<img width="800" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/04002bae-b147-49af-af6d-18eb5b89b4a9">

I hope these changes reduce compatibility issues in the future.

**Comment by choper725** [comment]
thanks for the summery @oblomov-dev 
i never used it, maybe beacuse i never knew what it does… :)

great feature to chain requests.. just the implementation is wierd, the cnt struc, there are other featurea to it ? or just abap bool value?
cant that feature be chained to the binding as a bool ?

one note on compatibility, chasing this project to be working on all sdk version, will be a hard task,
as we see the great sap are removing support for older versions every time.. just an idea of the path ahead i guess..

**Comment by oblomov-dev** [comment]
yes making it compatible to all ui5 sdk is indeed a hard task and will be not the plan :) i just wanted to make the core a bit more compatible and organize the samples that it is more obvious which sample is running where. we can then set up the lowest needed release from time to time in the future.

i have in mind to collect some control variables in this structure:
https://github.com/abap2UI5/abap2UI5/blob/570aebd68756d121b267f08f9ad4189a6f742ec8/src/02/z2ui5_if_types.intf.abap#L47
then it is also easily extendable in the future if more checks are needed (eg. display no busy indicator) and also other types than booleans are posssible.

technically i see no chance to import this value with the binding because it is event related and i need this information there.

**Comment by choper725** [comment]
maybe last_request ? or something along this line. ?

**Comment by oblomov-dev** [comment]
deleted the parameter with https://github.com/abap2UI5/abap2UI5/pull/984
yes it is named like this now:
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/93166f03-bde0-4b86-9fc6-8e5f584288c3">

**Comment by choper725** [comment]
@oblomov-dev 
can you explain when the check_view_destroy does?

**Comment by oblomov-dev** [comment]
it destroy immediately the view (before sending the backend request). but to be honest, i don't know if this is really needed.

**Comment by choper725** [comment]
ohh, i built like 50 apps by now and never used it, never had any issues regarding destryoed view or something like that..

**Comment by oblomov-dev** [comment]
It's fine it's nothing about issues, it's just a visual effect.

**Comment by oblomov-dev** [comment]
i close this, just open a new one if there are more questions.
