### ISSUE TITLE
Sample z2ui5_cl_demo_app_142 

### ISSUE THREAD

**Issue by nomssi** [abap2UI5/abap2UI5#986]
I have a syntax error because the parameter auto_resize does not exist I method  z2ui5_on_rendering.
`    view->_generic( ns = `html` name = `script` )->_cc_plain_xml( z2ui5_cl_cc_imagemapster=>set_js_config( is_config = ls_map_cfg auto_resize = abap_true ) ).`
I hope I have the latest code.

**Comment by choper725** [comment]
i think i fixed it, maybe you dont got the latest ?

**Comment by nomssi** [comment]
OK, I had the latest demo code, but I did not had the latest z2ui5_cl_cc_imagemapster code.
Somehow abapgit is having problem with overwriting local objects, I assume because of change in package assignment.

**Comment by choper725** [comment]
yes i have those issues also once package is changing
