### ISSUE TITLE
Enlarge Gantt Chart with element Relationsships

### ISSUE THREAD

**Issue by Marchl-Woid** [abap2UI5/abap2UI5#988]
Hello together,
maybe someone has a hint for me. What I try to do:
I use this sample as basis Z2UI5_CL_DEMO_APP_076:
I try to enhance the setup to get a gantt chart like in the SAPUI5 samples:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/ee0485b7-1c71-4c32-bf04-73660ce37d37)

Or at least to create the releationship between the item.

![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/afd9daf6-594d-47b0-8443-5cd08c6a6a44)

With the enhancement of z2ui5_cl_xml_view with the item relationships and relationship the xml looks more or less similar the the sample:

https://ui5.sap.com/#/entity/sap.gantt.simple.GanttChartWithTable/sample/sap.gantt.sample.GanttChart2Relationship

But it has more or less no effect. Could you gibe me a hint, what I am missing?

**Comment by oblomov-dev** [comment]
Hi @Marchl-Woid
Never used the relationship so far. Can you make a little sample out of your code with the gant using the relationship property? Then we can take a look to it and check if we see a away to realize this.
Best regards.

**Comment by Marchl-Woid** [comment]
HI @oblomov-dev 
Here would be the status of my current experiement:

I added theses two methode to Z2UI_CL_XML_VIEW

METHOD relationship.
    result = _generic( name = `Relationship`
                       ns = `gantt`
                        t_prop = VALUE #( ( n = `shapeId`           v = id )
                                         ( n = `type`           v = type )
                                         ( n = `SUCCESSOR`           v = successor )
                                         ( n = `PREDECESSOR`           v = predecessor )

                                          ) ).

  ENDMETHOD.


  METHOD RELATIONSHIPS.
    result = _generic( name = `relationships`
                       ns = `gantt` ).
  ENDMETHOD.

And here my current adaption of the demo class:

CLASS z2ui5_cl_demo_app_076_adapt DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_serializable_object .
    INTERFACES z2ui5_if_app .


    TYPES:
      BEGIN OF ty_s_RELATIONSHIPS,
        id           TYPE string,
        successor    TYPE string,
        presuccessor TYPE string,
      END OF ty_s_RELATIONSHIPS.

    TYPES ty_t_relation TYPE STANDARD TABLE OF ty_s_relationships WITH DEFAULT KEY .



    TYPES:
      BEGIN OF t_subtask5,
        id        TYPE string,
        starttime TYPE string,
        endtime   TYPE string,
      END OF t_subtask5 .
    TYPES:
      tt_subtask5 TYPE STANDARD TABLE OF t_subtask5 WITH DEFAULT KEY .
    TYPES:
      BEGIN OF t_task3,
        id        TYPE string,
        starttime TYPE string,
        endtime   TYPE string,
      END OF t_task3 .
    TYPES:
      BEGIN OF t_children4,
        id        TYPE string,
        text      TYPE string,
        subtask   TYPE tt_subtask5,
        relations TYPE ty_t_relation,
      END OF t_children4 .
    TYPES:
      tt_task3 TYPE STANDARD TABLE OF t_task3 WITH DEFAULT KEY .
    TYPES:
      tt_children4 TYPE STANDARD TABLE OF t_children4 WITH DEFAULT KEY .




    TYPES:
      BEGIN OF t_children2,
        id            TYPE string,
        text          TYPE string,
        task          TYPE tt_task3,
        children      TYPE tt_children4,
        relationships TYPE ty_t_relation,
      END OF t_children2 .
    TYPES:
      tt_children2 TYPE STANDARD TABLE OF t_children2 WITH DEFAULT KEY .
    TYPES:
      BEGIN OF t_root6,
        children TYPE tt_children2,
      END OF t_root6 .
    TYPES:
      BEGIN OF t_json1,
        root TYPE t_root6,
      END OF t_json1 .

    DATA mt_table TYPE t_root6 .
    DATA zoomlevel TYPE i .
  PROTECTED SECTION.

    DATA client TYPE REF TO Z2UI5_if_client .
    DATA check_initialized TYPE abap_bool .

    METHODS Z2UI5_on_init .
    METHODS Z2UI5_on_event .
    METHODS Z2UI5_set_data .

  PRIVATE SECTION.
ENDCLASS.



CLASS z2ui5_cl_demo_app_076_adapt IMPLEMENTATION.


  METHOD Z2UI5_if_app~main.
    me->client = client.

    IF check_initialized = abap_false.
      check_initialized = abap_true.

      Z2UI5_set_data( ).
      Z2UI5_on_init( ).
      RETURN.
    ENDIF.

    Z2UI5_on_event( ).

  ENDMETHOD.


  METHOD Z2UI5_on_event.

    CASE client->get( )-event.
      WHEN 'BACK'.
        client->nav_app_leave( client->get_app( client->get( )-s_draft-id_prev_app_stack ) ).
    ENDCASE.

  ENDMETHOD.


  METHOD Z2UI5_on_init.


    DATA(view) = z2ui5_cl_xml_view=>factory( ).

    view->_generic_property( VALUE #( n = `core:require` v = `{Helper:'z2ui5/Util'}` ) ).

    DATA(page) = view->page( id = `page_main`
            title          = 'abap2UI5 - Gantt'
            navbuttonpress = client->_event( 'BACK' )
            shownavbutton = xsdbool( client->get( )-s_draft-id_prev_app_stack IS NOT INITIAL )
            class = 'sapUiContentPadding' ).

    DATA(cont) = page->scroll_container(
*               height     =
*               width      =
*               vertical   =
                   horizontal = abap_True
*               id         =
*               focusable  =
*               visible    =
                 ).

    DATA(tool) = cont->container_toolbar(
      EXPORTING
        showsearchbutton          = abap_true
        showdisplaytypebutton     =  abap_true
        showlegendbutton          =  abap_true
        showsettingbutton         =  abap_true
        showtimezoomcontrol       =  abap_true
        findButtonPress = client->_event(
                            val                = 'FIRE'
                                          )
*    stepcountofslider         =
*    zoomcontroltype           =
        zoomlevel                 = client->_bind_edit( zoomLevel )
*  RECEIVING
*    result                    =
    )...


    DATA(gantt_container) = cont->gantt_chart_container(   ).
    DATA(gantt) = gantt_container->gantt_chart_with_table( id = `gantt` shapeselectionmode = `Single` ).

    gantt->axis_time_strategy(
      )->proportion_zoom_strategy( zoomLevel = client->_bind_edit( zoomLevel )
        )->total_horizon(
          )->time_horizon( starttime = `20181029000000` endtime = `20181231000000` )->get_parent( )->get_parent(
        )->visible_horizon(
          )->time_horizon( starttime = `20181029000000` endtime = `20181131000000` )->get_parent( )->get_parent( )->get_parent( )->get_parent(
  ).
    DATA(table) =  gantt->gantt_table( )->tree_table( rows = `{path: '` && client->_bind( val = mt_table path = abap_true ) && `', parameters: {arrayNames: ['CHILDREN'],numberOfExpandedLevels: 1}}`
        ).
    DATA(gantt_row_template) =   table->tree_columns(
           )->tree_column( label = 'Col 1' )->tree_template( )->text( text = `{TEXT}` )->get_parent( )->get_parent( )->get_parent(
*            )->tree_column( label = 'Col 1' template = 'text' )->get_parent( )->get_parent(
         )->row_settings_template(
           ).

    DATA gantt_rs TYPE REF TO z2ui5_cl_xml_view.
    gantt_RS =  gantt_row_template->gantt_row_settings( rowid = `{ID}`
                                  shapes1 = `{path: 'TASK', templateShareable:false}`
                                  shapes2 = `{path: 'SUBTASK', templateShareable:false}`
                                  relationships = `{path:'RELATIONSHIPS', templateShareable:false}`
            ).



    gantt_rs->shapes1(
            )->task( id = 'TSK1' time = `{= Helper.DateCreateObject(${STARTTIME} ) }`
            endtime = `{= Helper.DateCreateObject(${ENDTIME} ) }` type = `SummaryExpanded` color = `sapUiAccent5`  connectable = abap_True )."->get_parent( )->get_parent(

    gantt_rs->shapes2(
      )->task( id = 'TSK2' time = `{= Helper.DateCreateObject(${STARTTIME} ) }`
      endtime = `{= Helper.DateCreateObject(${ENDTIME} ) }`
      connectable = abap_True ).




    DATA lo_s TYPE REF TO z2ui5_cl_xml_view.
    lo_s = gantt_rs->relationships( ).


*                 <gnt2:relationships>
*                   <gnt2:Relationship shapeId="{data>RelationID}"
*                   predecessor="{data>PredecTaskID}" successor="{data>SuccTaskID}" type="{data>RelationType}" tooltip="{data>RelationType}"
*                   selectable="true"/>
*                 </gnt2:relationships>




    CALL METHOD lo_s->relationship
      EXPORTING
        id          = '{ID}'
        successor   = '{SUCCESSOR}'
        predecessor = '{PRESUCCESSOR}'
        type        = 'StartToFinish'
      RECEIVING
        result      = DATA(lo_rel).

*  RECEIVING
*    result =.



    client->view_display( view->stringify( ) ).

  ENDMETHOD.


  METHOD Z2UI5_set_data.


    mt_table = VALUE #( children = VALUE #( ( id = `line`
   text = `Level 1`
   task = VALUE #( ( id = `rectangle1` starttime = `2018-11-01T09:00:00` endtime = `2018-11-27T09:00:00` ) )
   relationships =  VALUE #( ( id = '34' successor = `chevron1` presuccessor = `chevron2` ) )


children = VALUE #( ( id = `line2` text = `Level 2`
                         subtask = VALUE #( ( id = `chevron1` starttime = `2018-11-01T09:00:00` endtime = `2018-11-13T09:00:00` )
                                            ( id = `chevron2` starttime = `2018-11-15T09:00:00` endtime = `2018-11-27T09:00:00` ) )
                                               relations =  VALUE #( ( id = '34' successor = `chevron1` presuccessor = `chevron2` ) )


)  ) ) ) ) .

  ENDMETHOD.
ENDCLASS.

**Comment by oblomov-dev** [comment]
Thank you! Feel free to send a PR next time, its ok when samples do not work and its the easiest way to share code. I added now manually your code as demo 179 and extended the xml view with: https://github.com/abap2UI5/abap2UI5/pull/993

But some more adjustments were needed and i am not sure if i messed something up. Do you get the same error when starting demo 179?
<img width="1351" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/e23dbf97-2eb6-4511-ad40-489f93ddd4df">

**Comment by Marchl-Woid** [comment]
HI @oblomov-dev 
just pulled the current versions, on my site I don't get this error:
![image](https://github.com/abap2UI5/abap2UI5/assets/54766892/159d7a5f-557c-4393-bc99-a7f2d4bdd758)

**Comment by oblomov-dev** [comment]
oh, it was my ui5 version. now it also works on my side, thanks for checking this.

**Comment by oblomov-dev** [comment]
i checked the demo, but the ui5 sdk provides the model as table and you used a tree structure. i adjusted the demo that it is using a table as in your example and added some xml extensions: https://github.com/abap2UI5/abap2UI5/pull/995

The demo is now closer to the ui5 sdk example:
![image](https://github.com/abap2UI5/abap2UI5/assets/102328295/2125f8b4-8a4f-468e-a387-46cddfa9cf3f)

But there are still some differences, maybe you can continue with this demo 179 and try to extend the xml class and the demo to make the xml output similar to: 
https://ui5.sap.com/#/entity/sap.gantt.simple.GanttChartWithTable/sample/sap.gantt.sample.GanttChart2Relationship

Then it should work and if not please PR your result and i can check it again.

**Comment by Marchl-Woid** [comment]
didn't get it working. stopped working on this topic.

**Comment by Marchl-Woid** [comment]
didn't get it working. stopped working on this topic.
