### ISSUE TITLE
Feature Request for Popup to Select

### ISSUE THREAD

**Issue by LadwigDev** [abap2UI5/abap2UI5#998]
Hi @oblomov-dev,
is it possible to add the parameters contentWidth, contentHeight and growingThreshold for the table_select_dialog to the factory method of the class Z2UI5CL_POPUP_TO_SELECT? Right now the popup takes a lot of space when used on a big screen when you have not that much table columns to be displayed.

If not, it is no big deal, I will then copy the class to our namespace :)

Have a nice weekend.

Best regards

**Comment by oblomov-dev** [comment]
Hi @LadwigDev,

yes this is a good idea! These parameters are very useful. 

Are you familiar with github and PRs? You can just add the parameters you need to the popup and then send PR. I will merge it and then the new parameters are available for everyone.

Best regards.

**Comment by LadwigDev** [comment]
To my shame, I have never worked with Git. I have attached the edited
 class here. Next time I might send you a PR ;)

[z2ui5_popup_to_select.txt](https://github.com/abap2UI5/abap2UI5/files/14540852/z2ui5_popup_to_select.txt)

**Comment by oblomov-dev** [comment]
thank you, added now with https://github.com/abap2UI5/abap2UI5/pull/1001
you can check again if it works on your side.

no worries, but recommend to take a look to the PRs. abap2UI5 is open for all contributions and you can extend the popups easily with additional parameters as you need which avoids having redundant code lines, reducing testing effort etc.

**Comment by LadwigDev** [comment]
Thanks a lot, works fine on my side :)
