### ISSUE TITLE
Syntax error in Demo 128

### ISSUE THREAD

**Issue by christianguenter2** [abap2UI5/abap2UI5#999]
![image](https://github.com/abap2UI5/abap2UI5/assets/17437789/01c986c7-8aa5-4737-a627-a671f603b2ab)

**Comment by oblomov-dev** [comment]
thank you for the hint, should be fixed now with https://github.com/abap2UI5/abap2UI5/pull/1001

**Comment by oblomov-dev** [comment]
I close this, just reopen if needed

**Comment by christianguenter2** [comment]
Thx. Forgot to close. Works.
